### PR TITLE
Do not scale player's model in the 1st-person view depending on race

### PR DESCRIPTION
**Pull request by akortunov**
Fixes [bug #4383](https://gitlab.com/OpenMW/openmw/issues/4383).

Now Bosmers-archers should be playable.

### CODE REVIEW

**Comment by Capostrophic** [comment]
Not especially happy about camera.cpp becoming dependent on world to do something that's not directly related to the camera, but hey, if it works...

**Comment by AnyOldName3** [comment]
I agree about camera depending on world being weird. Is there definitely no cleaner way of doing things?

**Comment by akortunov** [comment]
> Is there definitely no cleaner way of doing things?

Well, I can update scale manually after every toggleViewMode() in six different places. I'd not consider this way as a "cleaner", though.

**Comment by psi29a** [comment]
Executive override, merging.

If there are any issues; track with @akortunov

**Pull request merged**
