### PR TITLE
Fix some issues with attack animations

### PR DESCRIPTION
**Pull request by akortunov**
1. Fixes a recent regression, when player can not attack with melee weapon, if he shoot from bow before.
2. Fixes [bug #4591](https://gitlab.com/OpenMW/openmw/issues/4591), so attack strength calculation for player should be more corrent.
3. Since some attack animation contain movement, add a threshold when turning to target in melee combat - we use cone shapes anyway.
4. In vanilla turning animations do not reset idle ones. Replicate this behaviour.
3 and 4 together fix [bug #4371](https://gitlab.com/OpenMW/openmw/issues/4271).
5. Since we update mIdleState directly in character controller, we should update idle animations also when mIdleState == CharState_None. Fixes [bug #4531](https://gitlab.com/OpenMW/openmw/issues/4531).
6. We should not reset idle animations in the spellcasting stance.
7. Fix incorrect spelling of "preparing" word.

### CODE REVIEW

**Comment by akortunov** [comment]
Goblins now behave better than in 0.44 too. Nice.

**Comment by akortunov** [comment]
Tested by me and Capostrophic, no severe issues found yet.

**Comment by psi29a** [comment]
Fixed a merge conflict... this one ready? :)

**Comment by Capostrophic** [comment]
Unless you can find a regression somehow, go ahead.

**Pull request merged**
