### PR TITLE
Options to show hidden weapon parameters

### PR DESCRIPTION
**Pull request by akortunov**
1) Option to show damage of arrows and bolts through tooltip ([Feature #2923](https://bugs.openmw.org/issues/2923)).
Disabled by default. Add 
`show projectile damage = true`
to [Game] section in settings.cfg to enable it.

2) Option to show attack speed and reach of melee weapons through tooltip
This option is not needed for clean Morrowind, but it useful for plugins ([Weapon Range Balance](http://www.nexusmods.com/morrowind/mods/6051/) for example).
Disabled by default. Add 
`show melee info = true`
to [Game] section in settings.cfg to enable it.

### CODE REVIEW

**Comment by scrawl** [comment]
Can you do a rebase to remove the last two commits?

**Comment by akortunov** [comment]
Rebased.

**Comment by scrawl** [comment]
Although I'm not a big fan of merging tons more options that (ideally) would be addressed with enhanced modding capabilities in the future instead, this one is simple enough that I'll make an exception.

But first, can you update the documentation too?
https://github.com/OpenMW/openmw/blob/master/docs/source/reference/modding/settings/game.rst

**Comment by akortunov** [comment]
I updated the documentation.

**Pull request merged**
