### PR TITLE
Multiple spelling fixes

### PR DESCRIPTION
**Pull request by lkrieg**
Fixed multiple spelling mistakes. Most of the changes only affect comments, but there are also two modified variable names (not referenced from anywhere else). I double-checked everything and made sure the code is building without errors.

Files with changes to variable names are:
- apps/opencs/model/world/idtree.cpp
- apps/wizard/inisettings.cpp

NOTE: I'm not quite sure if I should open separate pull requests for each fix since there are quite a few. If you would like to have them seperate, just say so and I'll resubmit.

This is my first pull request, please be gentle! :-)

### CODE REVIEW

**Comment by psi29a** [comment]
Thank you for doing this.

**Comment by scrawl** [comment]
Thanks, but could you squash these into one commit, no need to make a commit for every word changed.

**Comment by lkrieg** [comment]
Of course! I'll do that as soon as I get back home.

**Comment by lkrieg** [comment]
Done!

**Pull request merged**
