### PR TITLE
Minor fix to OpenMW-CS tool outline

### PR DESCRIPTION
**Pull request by unelsson**
Adds `-1`

### CODE REVIEW

**Comment by akortunov** [comment]
Can you make commit name a more descriptive, please?

**Comment by elsid** [comment]
I'd expect some more explanation. Why `-1` is a fix, why not `+1`? What is broken?

**Comment by Capostrophic** [comment]
Quoting unelsson:
>About the OpenMW-CS PR above, should I make another PR for having ESM::Land::LAND_SIZE - 1 instead of just ESM::Land::LAND_SIZE? It's really a minor thing, but the tool outline has now slightly wrong scale... The difference is something like 1/65 vs 1/64, so hardly visible, but still.

**Comment by unelsson** [comment]
Yeah, it's -1 because there are 65 vertexes, of which one is shared with the next cell, therefore there are 64 bits between the vertexes.

**Comment by psi29a** [comment]
Is this for 0.46 ?

**Comment by Capostrophic** [comment]
Yeah it was.

**Comment by psi29a** [comment]
cherry-picked; thanks

**Pull request merged**
