### PR TITLE
Remove setting CMAKE_BUILD_TYPE to Debug

### PR DESCRIPTION
**Pull request by slothlife**
Setting was causing single-target configurations (ninja, make) to
incorrectly link vs debug runtimes on Windows.

### CODE REVIEW

**Comment by scrawl** [comment]
Great find. I really don't think this was meant to be committed in the first place. Blame shows commit f6203cac2ab29712a.

**Comment by kcat** [comment]
Though I would recommend setting it to RelWithDebInfo if it's not set, i.e.
```
IF(NOT CMAKE_BUILD_TYPE)
    SET(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING
        "Choose the type of build, options are: Debug Release RelWithDebInfo MinSizeRel."
        FORCE)
ENDIF()
```
CMake has a habit of not setting a build type if one isn't explicitly set on the command line, so it defaults to having no optimization or debug flags, which is a pretty useless build.

**Comment by slothlife** [comment]
Perhaps the top level CMakelists.txt is a good candidate for that kcat. I always explicitly set it via batch scripts when I build, so I haven't run into that.

**Comment by slothlife** [comment]
Sorry, but are you waiting on me to make the change in this Pull Request?

**Comment by zinnschlag** [comment]
kcat's remark is worth considering IMO.

**Comment by psi29a** [comment]
@slothlife Please implement kcat solution, then we can merge this in.

**Comment by slothlife** [comment]
Sorry for the delay. My free time wasn't as free as I had hoped.

**Pull request merged**
