### PR TITLE
Expand AiWander by 50% (Fixes #2726)

### PR DESCRIPTION
**Pull request by dteviot**
When AiWander distance has < 2 waypoints, expand distance by no more than 50%.

### CODE REVIEW

**Comment by scrawl** [comment]
Yeah, I'm not fond of the expanding idea. The correct fix is to support wandering with no pathgrid nodes. This PR is much better than the current behaviour though (not sure how that slipped past review). So let's merge it.

**Comment by dteviot** [comment]
@cc9ii, @scrawl 
> FWIW, I don't believe vanilla works this way at all. i.e. AIWander does not require pathgrid points.

I'm aware of this.  I'm working on what to do when there are no points, but it's more tricky.  As scrawl says, this is at least an improvement over the existing behaviour.

**Comment by TorbenCarrington** [comment]
This is not correct. Expansion may feel nice for now but it is entirely a
band-aid solution and I don't think merging would be a good idea.
Wandering with no pathgrid nodes was an issue involved in the pathgrid
format itself if I remember correctly, which is why I didn't implement it.
The true pathgrid also creates nodes for the initial position of each NPC
on the map and also allows for stopping in between path nods. Meaning
everywhere there is a line between nodes, the NPC can go there as a final
destination with AIWander. As well as anywhere (even places not linked to
with path nodes) that an NPC was placed on the ground when initially
loading the cell, is also a usable destination for building a path.

I am heavily against merging this, but it is not up to me.

**Comment by TorbenCarrington** [comment]
@cc9cii 
Actually, creatures do rely on pathgrids in vanilla if I remember correctly. Morrowind generates a blanket pathgrid for exterior cells that do not have one, this pathgrid is very basic and just has holes for static objects and water (being the reason NPCs and creatures in the wild walk around like idiots a lot of the time).

If we correct the pathgrid generation in OpenMW and adjust AIWander to work with it, the current implementation would be vanilla accurate.

**Comment by dteviot** [comment]
https://forum.openmw.org/viewtopic.php?f=6&t=2970
Created thread to continue discussion, so we can have a permanent, more easily findable record of my screw-up.

**Comment by zinnschlag** [comment]
@scrawl What is your opinion about TorbenCarrington's comments. Should we go ahead with the workaround anyway or wait for the discussion to continue?

**Comment by scrawl** [comment]
> Expansion may feel nice for now but it is entirely a
band-aid solution and I don't think merging would be a good idea.

This PR did not introduce the range expansion problem. It's already in master now. Therefore I stick to my previous statement:

> This PR is much better than the current behaviour though

**Comment by cc9cii** [comment]
> Morrowind generates a blanket pathgrid for exterior cells that do not have one, this pathgrid is very basic and just has holes for static objects and water 

@TorbenCarrington do you have any more information about this?  I don't believe vanilla does this.

**Comment by zinnschlag** [comment]
Right. This does not merge cleanly though.

**Comment by TorbenCarrington** [comment]
I don't :/ It has been a year since I worked on the AI. Perhaps Gus would
know more.

**Comment by dteviot** [comment]
@scrawl
Conflict is Scrawls OSG work.  (Big surprise.)
I'd suggest I just cancel this PR and do a new one that just rips out the code I put in for #1317. This will fix #2726 and reintroduce #1317. (IMHO, 2716 is a more serious bug than 1317)  I can then supply a new fix for #1317, as proposed in thread https://forum.openmw.org/viewtopic.php?f=6&t=2970.
Question: Does the proposal on the thread sound like the correct way to fix #1317?

**Comment by scrawl** [comment]
#648

**Pull request closed without merging**
