### PR TITLE
http to https for supported urls

### PR DESCRIPTION
**Pull request by GitHaarek**

### CODE REVIEW

**Comment by scrawl** [comment]
I used grep to find some more, can you fix those?

<pre>
./CONTRIBUTING.md:http://bugs.openmw.org/
./README.md:* Website: http://www.openmw.org
./README.md:* [Report a bug](http://bugs.openmw.org/projects/openmw) - read the [guidelines](https://wiki.openmw.org/index.php?title=Bug_Reporting_Guidelines) before submitting your first bug!
./README.md:* [Known issues](http://bugs.openmw.org/projects/openmw/issues?utf8=%E2%9C%93&set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=%3D&v%5Bstatus_id%5D%5B%5D=7&f%5B%5D=tracker_id&op%5Btracker_id%5D=%3D&v%5Btracker_id%5D%5B%5D=1&f%5B%5D=&c%5B%5D=project&c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=updated_on&group_by=tracker)
./files/settings-default.cfg:#   http://openmw.readthedocs.io/en/master/reference/modding/settings/index.html
./components/settings/settings.cpp:            ostream << "#   http://openmw.readthedocs.io/en/master/reference/modding/settings/index.html" << std::endl;
</pre>

Of course there are even more links to non-OpenMW sites. I guess we can't fix those if we can't guarantee they're always going to be https. Hopefully, people are anyway using a browser that defaults to https when it's supported.

**Comment by GitHaarek** [comment]
I think it should be safe to fix all remaining urls for domains that are supporting https today. It's less likely that any would want to downgrade as the web is moving towards https only and non-encrypted websites are increasingly being penalized by browsers and search engines.

**Comment by akortunov** [comment]
Is there a reason to keep a separate commit for every single link?
Maybe just squash commits and keep the name from the first one?

**Comment by Capostrophic** [comment]
Rebase plz.

**Comment by psi29a** [comment]
We can merge and squash here in the PR, so that isn't a problem.

**Comment by GitHaarek** [comment]
The remaining urls are either not supporting https yet or they are dead urls that I could not find a substitute for. There are also some remaining urls to be found in the SVG files, but the namespaces don't connect anywhere and I assume they cannot be changed anyway without making the SVG files invalid.

I have no more changes to add if everything looks good to you.

**Comment by psi29a** [comment]
Done and done, thank you! :)

**Pull request merged**
