### PR TITLE
Utilize inventory character preview lighting fallback settings

### PR DESCRIPTION
**Pull request by Capostrophic**
DirectionalDiffuseR/G/B, DirectionalAmbientR/G/B, DirectionalRotationX/Y.

### CODE REVIEW

**Comment by Capostrophic** [comment]
Currently trying to implement DirectionalRotationX/Y.

**Comment by scrawl** [comment]
* Just so we're on the same page, what's in your INI? Mine is:
```
DirectionalDiffuseR=1.0
DirectionalDiffuseG=1.0
DirectionalDiffuseB=1.0
DirectionalAmbientR=0.5
DirectionalAmbientG=0.5
DirectionalAmbientB=0.5
```
* With the settings above, some sections of the model will probably be capped at light contribution of 1.0, unless ```[Shaders] clamp lighting``` is false, in which case everything will look much brighter. Will that still look OK?
* The total ambient is determined by scene ambient (GL_LIGHTMODEL) plus the light's ambient. See this line: ```lightmodel->setAmbientIntensity(osg::Vec4(0.25, 0.25, 0.25, 1.0));```. Should the INI entry determine the total ambient? An easy way to test would be to set all values to 0 and see if the picture is black, then set everything to 0 except ambient = 1 and see if it's perfectly bright.

**Comment by Capostrophic** [comment]
1. Huh.
Mine goes

```
DirectionalDiffuseR=1.0
DirectionalDiffuseG=1.0
DirectionalDiffuseB=1.0
DirectionalAmbientR=0.0
DirectionalAmbientG=0.0
DirectionalAmbientB=0.0
DirectionalRotationX=110
DirectionalRotationY=90
```
and I swear I never modified Morrowind.ini.
2. It's too bright when ambient settings are 0.5 and lighting is unclamped: [screenshot](https://pp.userapi.com/c846320/v846320492/33764/F2BxSPD10zc.jpg).
3. I'll look into it.

**Comment by scrawl** [comment]
Oh, right. My ini is the same. I was reading off the commented 'defaults' thinking the uncommented ones had been edits by me. Nevermind.

**Comment by Capostrophic** [comment]
About 3: looks like it.

**Comment by Capostrophic** [comment]
Ok, these look pretty similar: [vanilla](https://cdn.discordapp.com/attachments/328579673229361152/438681223825588255/2018-04-25_15-42-13.png)/[PR(https://cdn.discordapp.com/attachments/328579673229361152/438681269526855680/screenshot020.png)

**Pull request merged**
