### PR TITLE
Find freetype

### PR DESCRIPTION
**Pull request by kpp**
FindFreetype.cmake sets FREETYPE_* variables, which is incorrect according to CMake docs. I fixed that.
Tested for freetype versions 2.5.2, 2.4.8

### CODE REVIEW

**Comment by scrawl** [comment]
I can't test this (nor can our CI) because OpenMW doesn't directly use Freetype. MyGUI does. The find freetype module is just there for use with static MyGUI builds (which I have never done before). Anyone using a static MyGUI build can verify that it works?

**Comment by kpp** [comment]
Place unconditional `find_package(Freetype)` inside root CMakeLists.txt or FindMyGUI.cmake.

**Comment by scrawl** [comment]
Looks like FindMyGUI.cmake still uses ```FREETYPE_LIBRARIES```, not ```Freetype_LIBRARIES```.

**Comment by kpp** [comment]
Right. I wanted to create PR for MyGUI right after this one is accepted. I ll fix it!

**Comment by kpp** [comment]
@scrawl done

**Comment by scrawl** [comment]
The change of ```FREETYPE_HOME``` -> ```FREETYPE_SDK``` will break the build instructions on the wiki and thus everyone's workflow. Maybe we should add backwards compatibility for using ```FREETYPE_HOME```?

**Comment by scrawl** [comment]
Forget that, freetype is not used in non-static builds, so it's not even in the build instructions... but what about the FFMPEG_HOME / FFMPEG_SDK from last PR?

**Comment by kpp** [comment]
> but what about the FFMPEG_HOME / FFMPEG_SDK from last PR?

Frankly speaking your FindFREETYPE module was never tested in CI. Actually you set FFMPEG_SDK in CI and searched for FFMPEG_HOME. It failed to find libraries but due to explicit manually set `DAVCODEC_LIBRARIES="$FFMPEG_SDK/lib/avcodec.lib"...` builds passed.

https://github.com/OpenMW/openmw/pull/940/files#diff-5732a79d0837L408
https://github.com/OpenMW/openmw/pull/940/files#diff-9df58364beef9L103

> will break the build instructions on the wiki and thus windows people's workflow. Maybe we should add backwards compatibility for using FREETYPE_HOME?

I was confused with FFMPEG_HOME / FFMPEG_SDK and decided to unify env paths. Now I see I should have followed wiki instructions. The new PR is coming.

**Pull request merged**
