### PR TITLE
fix building with Opengl ES1 on linux

### PR DESCRIPTION
**Pull request by sandstranger**
it is building now  and working with shared osg . sdl2 must be build only with  enabled gles1

### CODE REVIEW

**Comment by scrawl** [comment]
We shouldn't need to link against EGL for a non-static build.

**Comment by sandstranger** [comment]
Ok , Than it will be link only to Android , because all libraries for this platform building statically

**Comment by pcercuei** [comment]
It fails at runtime here, if OSG is compiled for GLES1 and with OSG_WINDOWING_SYSTEM=None. I get "Failed to create pbuffer, failing back to normal graphics window.". It comes from components/sdlutil/sdlcursormanager.cpp, apparently the cursor manager doesn't use the SDL2 context to render?

**Comment by scrawl** [comment]
The cursor manager uses OSG windowing system. SDL doesn't support pbuffers as far as I know.

**Comment by pcercuei** [comment]
I sent a separate PR to work around the issue.

**Comment by sandstranger** [comment]
I suppose  this issue is resolved now

**Pull request closed without merging**
