### PR TITLE
Update OS X packaging to work with OSG

### PR DESCRIPTION
**Pull request by corristo**
TODO:
- [x] Add attribution & licence to borrowed cmake modules

### CODE REVIEW

**Comment by zinnschlag** [comment]
Merge now or wait for the to do part? Ideally license/attributing statement should be added at the same time as the borrowed code.

**Comment by corristo** [comment]
@zinnschlag I'll add an attribution before merge.

**Comment by corristo** [comment]
@zinnschlag @scrawl added the attribution, is it okay?

**Comment by scrawl** [comment]
Looks ok to me.

**Pull request merged**
