### PR TITLE
needs this head for getuid

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by psi29a** [comment]
Where are you building?

**Comment by devnexen** [comment]
OpenBSD

**Comment by psi29a** [comment]
I'll merge in a minute. :) This is one area we struggle in, no *BSD CI. Do you know of any?

**Comment by devnexen** [comment]
I heard FreeBSD is using Jenkins. Otherwise, do not know real widely used CI tool.

**Comment by psi29a** [comment]
Thank you for the PR.  If you see anything BSD/CI related, let me know.  I'll get it setup to avoid things like this. :)

**Pull request merged**
