### PR TITLE
Permanent barter disposition

### PR DESCRIPTION
**Pull request by worstperson**
This adds a setting to allow temporary disposition changes to apply to an npc's permanent disposition similar to the option in MCP. The goal is to help remove the aspect of bartering where the user will always choose an improbably good deal and offer until it's accepted for maximum profit and experience. This is not a fix-all and works best balancing mods(like mods that raise merchant speechcraft skill, make speechcraft harder to raise, set iBarterSuccessDisposition to 0, etc).

### CODE REVIEW

**Comment by scrawl** [comment]
@zinnschlag is this ok? Seems like this should rather belong in the game files (new GMST?) post 1.0, but for now a settings file option is the best we can do.

**Comment by jeffreyhaines** [comment]
@worstperson do you have an active bug ticket for this issue? One needs to be created before we proceed to merge and/or close this pull request. Please post a link to that new ticket here, thanks

**Comment by zinnschlag** [comment]
Post 1.0 change. Do we really need this now as a setting? 1.0 isn't that far way.

**Comment by worstperson** [comment]
Did not mean to leave this open for so long, closing...

**Pull request closed without merging**
