### PR TITLE
Vanilla-style rain

### PR DESCRIPTION
**Pull request by akortunov**
An attempt to implement a vanilla-style rain using a reverse-engeneered logic from Morrowind.
Should fix the [bug #3404](https://gitlab.com/OpenMW/openmw/issues/3404).

Unfortunately, a particles-based rain works faster than a drawables-based approach.
So we basically should decide - either we keep a backward compatibility here and sacrifice performance, or we claim our current approach to be a more advanced and close mentioned bug as WON'T FIX.

### CODE REVIEW

**Comment by psi29a** [comment]
This is one of those things... do we want to have 1:1 Morrowind or do we want a more modern Morrowind?

Are there mods that change the rain that would take advantage of this?

Is it done similar with Oblivion, Skyrim etc?

**Comment by Pop000100** [comment]
Is the current implementation at default settings visually identical to Morrowind and will Particle based rain make no negative difference to modding(preventing more complex modifications).

If both of those statements are true then I'd say the current method is better.

**Comment by Capostrophic** [comment]
Neither are true.

**Comment by Pop000100** [comment]
Then how much slower is the mesh based way of doing things and will it make things like rain occlusion more complicated?

**Comment by akortunov** [comment]
> Then how much slower is the mesh based way of doing things and will it make things like rain occlusion more complicated?

It is unknown. That's why this PR is marked as NEEDS TESTING.

**Comment by akortunov** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
