### PR TITLE
Moving up in water

### PR DESCRIPTION
**Pull request by thegriglat**
Moving up player when idle in water .

### CODE REVIEW

**Comment by kcat** [comment]
Does vanilla do this?

**Comment by akortunov** [comment]
> Does vanilla do this?

No.
Another drawbacks:
1. An engine handles player differently from other actors.
2. Underwater battles become a bit annoying: the player is still moving up.
3. The player will have to move constantly to solve the Puzzle Canal quest (when you need to drown the player).

Anyway, what's the reason for this change?

**Comment by thegriglat** [comment]
Yes, in vanilla there is no such behaviour.
But I think it more physically based behavior (as in real life), than just "fly" in the water and adds dynamic in water fights.
It will be even more physically if flotation of player depends on his weight. E.g. heavy armored player will sink.
P.S.: Really I don't know the best place to insert corresponding code (as it is a first my effort to change something in openmw code), at the moment it just work.
BTW, it is OK to close PR if you don't see it applicable, it is just idea.

**Comment by akortunov** [comment]
> But I think it more physically based behavior (as in real life)

Do you mean buoyant force? A human with a heavy equipment will sink fastly instead of moving up.
And yes, a Morrowind behaviour is not realistic.
IMO, a realistic physics is a far more complex question than just two lines of code, executed for player only.

**Pull request closed without merging**
