### PR TITLE
Fix many Coverity Scan warnings

### PR DESCRIPTION
**Pull request by akortunov**
I still suggest to filter autogenerated files and external dependencies again since they cause spam of warnings which we can not fix.

### CODE REVIEW

**Comment by psi29a** [comment]
Working on it. ;)

**Comment by psi29a** [comment]
Looks like I've been able to fix things. Again, caused by local build. I made the regex's position independent.

**Comment by psi29a** [comment]
After this is merged, I'll run another round.

**Comment by akortunov** [comment]
Build error is fixed.

**Comment by psi29a** [comment]
Wonderful work, thank you! :)

Going to re-run coverity in a minute.

**Pull request merged**
