### PR TITLE
Switch to downloading dependencies from Github releases

### PR DESCRIPTION
**Pull request by Assumeru**
PR for testing actions.

https://gitlab.com/OpenMW/openmw/-/merge_requests/4450

### CODE REVIEW

**Comment by Assumeru** [comment]
Uhh, this wasn't supposed to be merged.

I guess it's fine because the sync will override it?

**Comment by AnyOldName3** [comment]
https://github.com/OpenMW/openmw/actions/runs/11778077287 says it didn't work anyway.

When I had to test the Actions after making a change, I made a branch on my fork and didn't need to make a PR for it to run. Except in the Actions tab, I can't see an attempted run for this branch in any of the normal places, so I guess that's just what it does when there's a syntax error.

**Comment by Assumeru** [comment]
Yeah, I've got them running happily on my own branch now. I think the first one was weird because I didn't push the master branch first (so the Actions tab just said some stuff about adding them at all.)

https://github.com/Assumeru/openmw/actions/runs/11782120683

**Comment by AnyOldName3** [comment]
That run's dying on https://gitlab.com/OpenMW/openmw/-/blob/master/components/config/launchersettings.cpp?ref_type=heads#L295, which I originally did with a default capture, and then had to stop because Clang `-Werror`ed out because nothing was being captured as `constexpr` things don't need capturing. I'm guessing it's been broken since the relevant MR was merged.

**Comment by AnyOldName3** [comment]
Yep https://github.com/OpenMW/openmw/actions/runs/11540499199/job/32121398575#step:12:711

It was failing before that pretty often due to the tests failing. That seemed to start with https://github.com/OpenMW/openmw/actions/runs/10697010351/job/29653330876#step:22:3202 a couple of months ago.

**Comment by Assumeru** [comment]
That's https://gitlab.com/OpenMW/openmw/-/issues/8183

**Comment by Assumeru** [comment]
That does look pretty convincing. Hmm.

**Pull request merged**
