### PR TITLE
Fix crash on destructed stream usage

### PR DESCRIPTION
**Pull request by elsid**
When error is logged [here](https://github.com/OpenMW/openmw/compare/master...elsid:fix_startup_fail_crash?expand=1#diff-49ce11037ce13ce089b6bc20160d5afbL146) streams constructed in [try](https://github.com/OpenMW/openmw/compare/master...elsid:fix_startup_fail_crash?expand=1#diff-49ce11037ce13ce089b6bc20160d5afbL110-L138) block are already destructed. This happens when `SDL_Init` is failed and causes segmentation fault.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff847352d in std::ostream::sentry::sentry(std::ostream&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff847352d in std::ostream::sentry::sentry(std::ostream&) () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff8473ba8 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000000c0afbb in std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*) (__out=warning: can't find linker symbol for virtual table for `std::basic_ostream<char, std::char_traits<char> >' value
warning:   found `typeinfo for std::ostream' instead
..., __s=0x7ffffffede30 "\001\tn\370\377\177") at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/ostream:561
#3  0x0000000000c0afbb in Debug::Tee::writeImpl(char const*, long, Debug::Level) (this=0x7ffffffeddb0, str=0x1208821 "Error: Could not initialize SDL! No available video device\n", size=59, debugLevel=Debug::Error) at /home/elsid/dev/openmw/components/debug/debugging.hpp:97
#4  0x0000000000c099a7 in Debug::DebugOutputBase::write(char const*, long) (this=0x7ffffffed630, str=<optimized out>, size=60) at /home/elsid/dev/openmw/components/debug/debugging.cpp:47
#5  0x0000000000c0b604 in boost::iostreams::detail::write_device_impl<boost::iostreams::output>::write<Debug::Tee>(Debug::Tee&, boost::iostreams::char_type_of<Debug::Tee>::type const*, long) (t=..., s=0x7ffffffede30 "\001\tn\370\377\177", n=60) at /usr/include/boost/iostreams/write.hpp:117
#6  0x0000000000c0b604 in boost::iostreams::write<Debug::Tee>(Debug::Tee&, boost::iostreams::char_type_of<Debug::Tee>::type const*, long) (t=..., s=0x7ffffffede30 "\001\tn\370\377\177", n=60) at /usr/include/boost/iostreams/write.hpp:49
#7  0x0000000000c0b604 in boost::iostreams::detail::device_wrapper_impl<boost::iostreams::output>::write<Debug::Tee, boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> > >(Debug::Tee&, boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> >*, boost::iostreams::char_type_of<Debug::Tee>::type const*, long) (dev=..., s=0x7ffffffede30 "\001\tn\370\377\177", n=60) at /usr/include/boost/iostreams/detail/adapter/concept_adapter.hpp:194
#8  0x0000000000c0b604 in boost::iostreams::detail::concept_adapter<Debug::Tee>::write<boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> > >(char const*, long, boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> >*) (this=0x7ffffffed630, s=0x7ffffffede30 "\001\tn\370\377\177", n=60, snk=<optimized out>) at /usr/include/boost/iostreams/detail/adapter/concept_adapter.hpp:85
#9  0x0000000000c0b604 in boost::iostreams::detail::indirect_streambuf<Debug::Tee, std::char_traits<char>, std::allocator<char>, boost::iostreams::output>::sync_impl() (this=0x7ffffffedd68) at /usr/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:407
#10 0x0000000000c0b604 in boost::iostreams::detail::indirect_streambuf<Debug::Tee, std::char_traits<char>, std::allocator<char>, boost::iostreams::output>::sync() (this=0x7ffffffedd68) at /usr/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:312
#11 0x00007ffff8472d7e in std::ostream::flush() () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x000000000070fcc8 in std::flush<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&) (__os=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/ostream:613
#13 0x000000000070fcc8 in std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&) (__os=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/ostream:591
#14 0x000000000070fcc8 in std::ostream::operator<<(std::ostream& (*)(std::ostream&)) (this=<optimized out>, __pf=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/ostream:113
#15 0x000000000070fcc8 in Log::~Log() (this=0x7ffffffed830) at /home/elsid/dev/openmw/./components/debug/debuglog.hpp:59
#16 0x0000000000c0a863 in wrapApplication(int (*)(int, char**), int, char**, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (innerApplication=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
0xaca180 <runApplication(int, char**)>, argc=7, argv=0x7ffffffee098, appName=)
    at /home/elsid/dev/openmw/components/debug/debugging.cpp:146
#17 0x0000000000aca264 in main(int, char**) (argc=-74192, argv=0x31007fffffffefd3) at /home/elsid/dev/openmw/apps/openmw/main.cpp:271
```

Solution is to make lifetime for streams longer (tested on linux).

### CODE REVIEW

**Comment by AnyOldName3** [comment]
How do I reproduce the crash so I can test a before and after on Windows?

**Comment by elsid** [comment]
I have this on WSL when X server is not running. Not sure how to repeat this on windows. One approach is to change code and throw exception before `SDL_Init` is called to simulate same behavior.

```
diff --git a/apps/openmw/engine.cpp b/apps/openmw/engine.cpp
index 7c92236ed..2020c094b 100644
--- a/apps/openmw/engine.cpp
+++ b/apps/openmw/engine.cpp
@@ -239,6 +239,7 @@ OMW::Engine::Engine(Files::ConfigurationManager& configurationManager)
     if(SDL_WasInit(flags) == 0)
     {
         SDL_SetMainReady();
+        throw std::runtime_error("Could not initialize SDL!");
         if(SDL_Init(flags) != 0)
         {
             throw std::runtime_error("Could not initialize SDL! " + std::string(SDL_GetError()));
```

**Comment by elsid** [comment]
Bump

**Comment by psi29a** [comment]
@elsid can you give steps to @AnyOldName3 on how to reproduce this?

**Comment by psi29a** [comment]
Another question, why are we using boost here and not just std::ostream?

**Comment by akortunov** [comment]
> Another question, why are we using boost here and not just std::ostream?

Actually, we use the `std::ostream` here. We just use the `boost::iostreams::stream_buffer` instead of `streambuf` since we need to delegate I/O to the `Debug::Tee` to copy data from `cout` to the log file.

**Comment by akortunov** [comment]
> Another question, why are we using boost here and not just std::ostream?

Just for reference: as I understood, usually we use boost file streams since they support non-ASCII characters in file paths.

**Pull request merged**
