### PR TITLE
Flavor Text support

### PR DESCRIPTION
**Pull request by kunesj**
Adds in "Flavor Text" text field in OpenMW-CS for all item types. 
- Items that don't have this value empty will display tooltip with flavor text next to standard tooltip (after specified delay).
- Flavor text will be displayed only in "Inventory mode" (right click, merchants, etc...)
- Width of flavor text tooltip and delay between displaying standard tooltip and flavor text tooltip can be changed with new options in settings-default.cfg

Screenshots: https://imgur.com/a/7yGT9
Forum thread: https://forum.openmw.org/viewtopic.php?f=3&t=3802

Note: 
I am still not sure if I completely understand how code for OpenMW-CS works, so someone who does should probably check that I did not forget to do something important.

EDIT:
bug ticket: https://bugs.openmw.org/issues/3688

### CODE REVIEW

**Comment by scrawl** [comment]
Zini should weigh in on this, but from what I remember, the plan was to keep the ESM format compatible with the vanilla game until after version 1.0, so the changes to the format would be out of the question for now.

**Comment by kunesj** [comment]
I was under the impression that editor saved addons as *.omwaddon because they were not compatible...

**Comment by scrawl** [comment]
.omwaddon/.omwgame in theory can be renamed to .esp/.esm and should work in the vanilla game (barring any bugs in the editor).

**Comment by Aesylwinn** [comment]
Yes, in theory it should work, but honestly, no one tests that... Anyway, it looks like the Morrowind engine ignores data it doesn't use. Converting an omwaddon with the added flavor text to an esp file doesn't cause it to outright crash.

**Comment by kcat** [comment]
Any omwaddon/game that uses scripts won't immediately work as esp/m files since they're not compiled.

**Comment by jeffreyhaines** [comment]
@kunesj do you have an active bug ticket for this issue? One needs to be created before we proceed to merge and/or close this pull request. Please post a link to that new ticket here, thanks

**Comment by kunesj** [comment]
Here is the bug ticket. https://bugs.openmw.org/issues/3688

**Comment by jeffreyhaines** [comment]
Thanks :)

**Comment by zinnschlag** [comment]
Post 1.0 feature. Sorry.

**Pull request closed without merging**
