### PR TITLE
C++17 [DO NOT MERGE YET; Needs MacOS support]

### PR DESCRIPTION
**Pull request by psi29a**
Let's see what works and what doesn't...

### CODE REVIEW

**Comment by psi29a** [comment]
Win... C++17 is ready to go.

Going to experiment now with some de-boosting.

**Comment by psi29a** [comment]
@ace13 would you be able to help get msvc2017 up and running? I would love to ditch as much boost as possible, that includes boost::any which has a std::any replacement, but is not available in msvc2015...

**Comment by psi29a** [comment]
@nikolaykasyanov can you take a look at the osx side? I tried bumping it to use xcode9.1 but it complains that clang is 'broken' and it can't compile. Is there something I'm doing wrong?

**Comment by scrawl** [comment]
Just to make it clear, there are no plans of merging C++17 any time soon (see #1520), and anyone working on this is doing so out of their own curiosity.

**Comment by psi29a** [comment]
What @scrawl said, this is just to figure things and see what it gains us. Many of the functions are still in the std::experiment namespace.

**Comment by zinnschlag** [comment]
Technically this is a post-1.0 PR too, right?

**Comment by psi29a** [comment]
This is me playing around, hence the do not merge yet.  Not so much post-1.0 (unless that is just right around corner), but it can't be merged until supported by macOS. Believe or not, GCC/Clang/MSVC all support this... but macOS does not and no one knows when they will add std::filesystem (let alone std::experimental::filesystem into XCode/Clang.

**Pull request closed without merging**
