### PR TITLE
Add support for service-specific refusals

### PR DESCRIPTION
**Pull request by akortunov**
Implements [feature #5580](https://gitlab.com/OpenMW/openmw/-/issues/5580).
Note that the feature request description is a quite vague, so it requires verification, better with a couple of mods which actually use this feature.

### CODE REVIEW

**Comment by akortunov** [comment]
@psi29a, should I close this PR?

**Comment by psi29a** [comment]
@akortunov I was hoping to get more conversation/opinions about this. Also from @Assumeru since he created the ticket.

**Comment by Assumeru** [comment]
I threw it on the tracker because it seemed like a simple enough feature and it sounded neat.

I think item 1 and maybe 3 can be considered tested at least.

**Comment by psi29a** [comment]
Looks like we have a conflict...

**Comment by psi29a** [comment]
Is it just me or is Travis somehow not happy?

**Comment by Assumeru** [comment]
It doesn't look like Travis even tried to build it that last time.

**Pull request merged**
