### PR TITLE
Fix FindSphinx.cmake

### PR DESCRIPTION
**Pull request by kpp**
- Reduce the number of copypaste in FindSphinx.cmake
- Make argument processing for function Sphinx_add_targets user-friendly

### CODE REVIEW

**Comment by psi29a** [comment]
Thank you for this!

**Comment by scrawl** [comment]
I don't have sphinx. @psi29a could you test and merge this PR?

**Comment by kpp** [comment]
You may test it like that:
```

if (Sphinx_FOUND)
    Sphinx_add_targets(NAME sphinx
        SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/docs/source/
        DST_DIR ${CMAKE_CURRENT_BINARY_DIR}/sphinx/
        CONFIG_DIR ${CMAKE_CURRENT_SOURCE_DIR}/docs/source/
    )
endif()
```
Call `cmake .. -DBUILD_DOCS=ON` and `make sphinx_html`

**Comment by psi29a** [comment]
Great work!  Works as described. I'll be lifting this for others projects (with credit). :)

**Pull request merged**
