### PR TITLE
[Not for merging] Empirical testing for AppVeyor build performance

### PR DESCRIPTION
**Pull request by ace13**

### CODE REVIEW

**Comment by ace13** [comment]
*Release* build timed out after an hour, definitely slower than *Debug*.
*RelWithDebInfo* next.

**Comment by ace13** [comment]
*RelWithDebInfo* also times out one hour into compiling, also definitely slower than *Debug*.
Time to finish the testing off with *MinSizeRel*

**Comment by scrawl** [comment]
What about *None*, is that not available on VS?

**Comment by ace13** [comment]
Build type *None* doesn't exist on VS, no. If you try to force something like that you just end up with *Debug*.

**Comment by ace13** [comment]
From this testing I can conclude that the only build type fast enough to be able to complete in time, is *Debug*.

**Pull request closed without merging**
