### PR TITLE
Further updating of normal map conversion documentation

### PR DESCRIPTION
**Pull request by lysol90**
Ok, so another update then. Sorry for another one so soon after the first PR, but I think (or hope) that this will be the last edit for some time. It looks good to me now.

Mainly, I changed changed some "=" headers to "-", and while at it, I fixed some typing errors and just edited some text to read better.

### CODE REVIEW

**Comment by psi29a** [comment]
^5  looks great
https://openmw.readthedocs.io/en/master/

Feel free to spread the news on the forums :)

**Comment by psi29a** [comment]
Spoke too soon: https://openmw.readthedocs.io/en/master/openmw-mods/index.html

'Index:' shouldn't be there, probably because Index: is an anchor? You can click on it, I think you can drop the Index: honestly, does it add anything?

**Comment by psi29a** [comment]
Fixed it. :)  Great job and thank you!

**Comment by lysol90** [comment]
> Fixed it. :)

Haha, that explains it. I just though "what index?" when I clicked the link. Thanks for fixing it for me. No, the index does not need to be there.

**Pull request merged**
