### PR TITLE
Update coverity scan branch

### PR DESCRIPTION
**Pull request by Capostrophic**
It's been a while since November, so it's a good time to trigger a coverity build.

### CODE REVIEW

**Comment by psi29a** [comment]
It will fail. Builds take too long now.

**Comment by Capostrophic** [comment]
Hm. And disabling building of *all* additional apps but openmw will not work?

**Comment by psi29a** [comment]
We've already done that I think, I'll check again.

**Comment by akortunov** [comment]
> We've already done that I think, I'll check again.

Last time I checked, we enabled analyze for the OpenMW-CS as well.
From what I can tell, earlier we did not build the editor as well.

**Pull request merged**
