### PR TITLE
Add collision for dropped items (configurable via settings)

### PR DESCRIPTION
**Pull request by terabyte25**
[#4687](https://gitlab.com/OpenMW/openmw/issues/4687)
https://forum.openmw.org/viewtopic.php?f=6&t=4465&p=48339#p48339

### CODE REVIEW

**Comment by terabyte25** [comment]
Should this be configurable from the Advanced menu?

**Comment by terabyte25** [comment]
Seems like tes3mp and OpenMW have 2 different ways of handling collision for an item. For tes3mp, actors can land normally, but in OpenMW the actors "land" on the items, and "levitate" as if they are jumping. This causes the physics system to shit itself whenever an actor is on an object.

**Comment by terabyte25** [comment]
Here's the omwsave to test with for this PR. 
[save.zip](https://github.com/OpenMW/openmw/files/2497697/save.zip)

**Comment by kcat** [comment]
I don't think this is the correct way to do this. The way objects have collisions is (mostly) consistent with vanilla, and I don't think a settings option is really the way to make it configurable. It should be handled by the game data since it has a significant effect on the game. It should be up to the content creator rather than the user.

**Comment by davidcernat** [comment]
> Seems like tes3mp and OpenMW have 2 different ways of handling collision for an item. For tes3mp, actors can land normally, but in OpenMW the actors "land" on the items, and "levitate" as if they are jumping. This causes the physics system to shit itself whenever an actor is on an item.

No, they don't. That's just you giving the items actor-style collisions by default. Is there even a way to turn off collisions for items again in your implementation? It looks like you've made them have world collisions if the actor-style collisions are turned off. If you're going to copy-paste functionality from TES3MP, perhaps you should at least do it in a way that makes sense.

**Comment by zinnschlag** [comment]
Can we please cut down on new settings? The more we add now the more we need to clean up later.

**Pull request closed without merging**
