### PR TITLE
Show starting abilities, powers and spells in stat-review window

### PR DESCRIPTION
**Pull request by MiroslavR**
Fixes: https://bugs.openmw.org/issues/2410

### CODE REVIEW

**Comment by scrawl** [comment]
The spells section is not complete. In addition to the race and birthsign spells, you may get additional starting spells depending on major/minor skills chosen (see buildPlayer() function).

**Comment by MiroslavR** [comment]
Interesting, I had no idea you get auto-calculated starting spells.

**Comment by MiroslavR** [comment]
Done.

**Comment by scrawl** [comment]
* Shouldn't the spells be sorted alphabetically for display? 
* What is the reason for aggregating the spells manually? Wouldn't just using the player's current spells result in shorter code?
* What is the reason for adding onFrame()? Why not do updates right away?

**Comment by MiroslavR** [comment]
> Shouldn't the spells be sorted alphabetically for display?

They're not in vanilla.

> What is the reason for aggregating the spells manually? Wouldn't just using the player's current spells result in shorter code?

I was trying to preserve the vanilla display order (generated spells->racial spells->birth sign spells). Player's spells are stored in a map. Also I wanted to keep the "Review" class unaware of the player.

> What is the reason for adding onFrame()? Why not do updates right away?

Because otherwise updateSkillArea() would get called 30 times (in a single frame) after changing the character, which results in a noticeable freeze.

**Comment by scrawl** [comment]
Makes sense.

**Comment by Allofich** [comment]
There's some Clang warnings you may not have noticed.
https://travis-ci.org/OpenMW/openmw/jobs/177323057

**Comment by MiroslavR** [comment]
Yeah, gcc doesn't have that warning. Thanks for letting me know.

**Pull request merged**
