### PR TITLE
Adding buy page to Wizard

### PR DESCRIPTION
**Pull request by Thunderforge**
Fixes [Feature #3983](https://bugs.openmw.org/issues/3983). It is my hope that this will make things easier for users who downloaded OpenMW not realizing that they needed to purchase Morrowind, and hopefully encourage sales of the game.

This changes the method installation page to have the "Buy the Game" option:

method installation

And choosing it leads to this page:

buy the game

Clicking on any of the hyperlinks leads to the appropriate store links. The links are the basic links for the store pages and do not contain referrers or anything (which supports the statement described at the bottom of the window).

The basket icon is a [GNOME Desktop icon](https://commons.wikimedia.org/wiki/GNOME_Desktop_icons) under the GNU General Public License version 2. The other retailer icons are simple geometric shapes or text and are not eligible for copyright, and are thus in the public domain (see statements to this effect on, for instance, Wikipedia's usage of the [Steam](https://en.wikipedia.org/wiki/File:Steam_icon_logo.svg) and [GOG.com](https://en.wikipedia.org/wiki/File:Gog-logo-2014.svg) icons).

### CODE REVIEW

**Comment by Thunderforge** [comment]
I'm not understanding why Appveyor failed with this error:

       "C:\projects\openmw\MSVC2013_32\OpenMW.sln" (Build target) (1) ->
       "C:\projects\openmw\MSVC2013_32\apps\wizard\openmw-wizard.vcxproj.metaproj" (default target) (12) ->
       "C:\projects\openmw\MSVC2013_32\apps\wizard\openmw-wizard.vcxproj" (default target) (22) ->
       (ClCompile target) -> 
         C:\projects\openmw\apps\wizard\mainwizard.cpp(338): error C2061: syntax error : identifier 'BuyPage' [C:\projects\openmw\MSVC2013_32\apps\wizard\openmw-wizard.vcxproj]

The file `mainwizard.cpp` has `#include "buypage.hpp"` at the top of of it's file, and CLion can build without error. What am I doing wrong?

**Comment by scrawl** [comment]
I am not sure if we would want to list these sources in the launcher itself. A user who selects to buy from there might be disappointed that their game isn't installed automatically for them, and they might even have to use WINE to get to their game files. Even for sources that are linux-friendly (GOG and Steam) we are lacking official documentation for how to install them, and the launcher has no ability to do so yet.
While all of this is an issue regardless of whether or not we have a Buy page with fancy buttons in the launcher, having these will set certain expectations, I think.

In any case, I imagine the list of retailers will change all the time and we can't push out OpenMW updates whenever this happens - so, maintaining the list on a wiki instead might be better.

As to the disclaimer - "does not endorse" - well, the phrase 'Here's how to get it:' sure does sound like an endorsement.

**Comment by Thunderforge** [comment]
> Even for sources that are linux-friendly (GOG and Steam) we are lacking official documentation for how to install them, and the wizard has no ability to do so yet.

GOG.com support is part of [Bug #3032](https://bugs.openmw.org/issues/3032) (although personally I think that it should be spun off into its own bug report). And I was actually planning on working on automating Steam importing after this (per [this thread](https://forum.openmw.org/viewtopic.php?f=20&t=4372)). All of the other retailers provide Steam or GOG.com keys, so if those two were implemented, would that address your concerns?

> As to the disclaimer - "does not endorse" - well, the phrase 'Here's how to get it:' sure does sound like an endorsement.

I'd be open to suggestions for alternatives.

**Comment by PlutonicOverkill** [comment]
Re the compiler error: It is because you put `#include "buypage.hpp"` inside the `#ifdef OPENMW_USE_UNSHIELD` so the BuyPage type is not declared.

**Comment by Thunderforge** [comment]
@PlutonicOverkill Thanks, I've fixed that.

**Comment by scrawl** [comment]
> GOG.com support is part of Bug #3032 (although personally I think that it should be spun off into its own bug report). And I was actually planning on working on automating Steam importing after this (per this thread). All of the other retailers provide Steam or GOG.com keys, so if those two were implemented, would that address your concerns?

More or less, assuming this is implemented before we merge this PR. I'm still not too keen on depending on a third party to not break their workflow lest we get complaints from users, but I guess that can't be avoided.

> All of the other retailers provide Steam or GOG.com keys,

Is there any value in listing them, then? Buying from a reseller just adds an extra step for the user (i.e. buy, redeem key rather than just buy), and they have to create two accounts rather than one. I've also heard that some key retailers use less-than-legitimate ways of obtaining keys (buying them in bulk on a sale or even buying them from credit card fraudsters). How would we tell the good ones from the bad ones?

**Comment by kcat** [comment]
> I've also heard that some key retailers use less-than-legitimate ways of obtaining keys (buying them in bulk on a sale or even buying them from credit card fraudsters). How would we tell the good ones from the bad ones?

Bethesda should have a list of official sellers somewhere, that we can assume are legitimate (but don't guarantee, hence the no-endorsement statement). Though I'm having a hard time finding said list on bethesda.net...

**Comment by MaxMaslov** [comment]
Do we really need this functionality? I mean, is not so hard to buy a Morrowind, just googled it. Links to sellers in Wizard looks redundantly.

**Comment by Gaerzi** [comment]
> I'd be open to suggestions for alternatives.

Top text: "If you do not already own _The Elder Scrolls III: Morrowind_, you can purchase a downloadable version from any one of these retailers. These links are provided for convenience only and should not be construed as an endorsement."

**Comment by AnyOldName3** [comment]
If we can't manually keep this synchronised with a published list from Bethesda, then I'm not hugely keen on listing some retailers, but not others that may be completely above-board. We could potentially link to a site like IsThereAnyDeal.com, which should keep track of which retailers are legitimate itself.

As for Scrawl's idea of just suggesting GoG and Steam, as this effectively promotes them maintaining a monopoly, I'm not hugely keen, and I imagine there'll be others who've contributed to OpenMW who wouldn't like it either. If we do that, I'd be happier if there was a bit of text saying that other authorised retailers exist, and this list is not exhaustive or an indication of where to find the best price/customer service/whatever.

**Comment by Thunderforge** [comment]
> Bethesda should have a list of official sellers somewhere, that we can assume are legitimate (but don't guarantee, hence the no-endorsement statement). Though I'm having a hard time finding said list on bethesda.net...

When I started developing this feature, they did have a list of suggested retailers for [The Elder Scrolls Anthology](https://elderscrolls.bethesda.net/en/anthology), which was a set of all Elder Scrolls games on physical CD/DVDs. It was the only way that Bethesda endorsed at the time to get Morrowind on disc. Unfortunately, a week or two after I made my official mockups, they removed the retailer links.

It does not appear that Bethesda has a similar list of retailers for Morrowind in digital form. Frustratingly, the "Buy it Now" link on the Morrowind page of their website takes you [to Skyrim](https://elderscrolls.bethesda.net/en/skyrim/order). But on the other hand, Skyrim lists three links for digital downloads: Xbox Marketplace, PlayStation Store, and Steam. This seems like a pretty clear endorsement that Bethesda endorses Steam (and sadly, not GOG.com).

Given this my recommended course of action is this:

 - Reject this PR and the associated feature request (it's not a total loss for me, I got some good Qt practice)
 - Add links to the retailers linked on this PR to the wiki (and sort out legitimacy disputes on there; anybody want to argue that Humble Bundle is a fly by night operation selling stolen keys?). We can throw in a link to IsThereAnyDeal.com too.
 - When we add Steam download integration to the launcher, do one of the following (to be decided then):
   - Link to the Steam page, since Bethesda seems to endorse them
   - Link to the aforementioned wiki page
   - Just don't mention where to get it
 - When we add GOG.com download/installation to the launcher, do the same

How does that sound?

**Comment by kcat** [comment]
GoG can be considered legitimate since they're licensed by Bethesda to sell them. They're not a key reseller and don't sell games they're not licensed to.

**Comment by Thunderforge** [comment]
@kcat Game companies do work directly with key resellers as well. For instance, [CDProjektRed works with a number of key resellers](https://www.reddit.com/r/pcgaming/comments/36n8lc/is_dlgamer_a_legit_site_it_has_the_witcher_3_for/crfgxth/) for The Witcher 3. I guess we don't know for sure which key resellers Bethesda is working with, but I strongly suspect they are working with others.

I guess we do have a fourth option:

 - Do what that Redditor did and contact Bethesda and ask which retailers they work with.

I don't know if OpenMW is in regular communication with Bethesda (or we only talk to them when they contact us, as with the Android guidelines), but yeah, I guess that would clear up a lot of confusion to know which retailers they are working with, aside from Steam.

**Comment by kcat** [comment]
> Game companies do work directly with key resellers as well.

Probably, But my point was that GoG aren't. GoG (who are owned by CD Projekt, parent company of CD Projekt RED) only sells games that they have licenses for. Bethesda has also promoted the fact that you could buy it there when they started to sell it, so until they say otherwise, we can consider them an official seller. Other places may also be official sellers, but it's less clear which ones are.

> Do what that Redditor did and contact Bethesda and ask which digital retailers they work with.

Also a good idea.

**Comment by AnyOldName3** [comment]
Asking Bethesda could get complicated if it turns out they sell keys to a wholesaler who then sells it on to a bunch more retailers/resellers. When Fallout 4 was released, they also had issues where GreenManGaming, one of the biggest 'legitimate' key retailers, IIRC had more keys to sell than Bethesda said they should. GMG claimed it had bought them from another retailer, which had a surplus, at wholesale prices, and that they'd checked their agreement with Bethesda, and they weren't violating it. I'm not sure if that was resolved in public, but everyone did get the keys they'd paid for.

**Comment by Thunderforge** [comment]
I've decided to close my pull request, per [this comment](https://github.com/OpenMW/openmw/pull/1429#issuecomment-328316940). Thanks to everyone who provided feedback on this.

**Pull request closed without merging**
