### PR TITLE
since focal is default; use default clang

### PR DESCRIPTION
**Pull request by psi29a**

### CODE REVIEW

**Comment by akortunov** [comment]
Are you sure that we need 32-bit packages here? It seems that Travis can not find suitable 32-bit libc version.

**Comment by akortunov** [comment]
Also looks like "ubuntu9.3" update was removed due to regressions, and 9.2 should be used instead. I wonder why Travis still tries to install buggy version... Probably maintainers of one of mirrors forgot to remove broken packages.

**Comment by psi29a** [comment]
looks like something broke, I'm assuming that they are using focal proposed and focal backports... that can lead to problems.

**Comment by akortunov** [comment]
I suppose that this PR can be closed.

**Comment by psi29a** [comment]
Maybe, I don't think it's simple any more to maintain these. Including MSVC2017, though I think that can be fixed if someone took the time to setup MSVC2017.

**Pull request closed without merging**
