### PR TITLE
Fix hidden node with NiVisController optimization

### PR DESCRIPTION
**Pull request by Capostrophic**
Geometry that such a node could have could be erroneously optimized out because the check for whether the node has a NiVisController controlling it assumes the node will have the NiVisController as its last controller.

This optimization will have to be redesigned anyway in the future because controllers can control any parent node, but for now it should just not be broken.

### CODE REVIEW

**Comment by akortunov** [comment]
Is it for 0.46 or for 0.47?

**Comment by Capostrophic** [comment]
Either will do.

**Comment by AnyOldName3** [comment]
Might this be simpler with an `|=`?

**Comment by Capostrophic** [comment]
Wouldn't that mean we'll have to check every single controller of the node instead of just getting to the NiVisController?

**Comment by Capostrophic** [comment]
I guess you mean leaving a check for hasVisController value and break in and putting hasVisController |= whatever before it. That saves one line, but does it really improve readability?

**Comment by AnyOldName3** [comment]
🤷‍♂️

**Comment by psi29a** [comment]
Merged and cherry-picked to 0.46

**Pull request merged**
