### PR TITLE
Simple line numbering and fixed-width fonts for the script dialogue.

### PR DESCRIPTION
**Pull request by cc9cii**
Based on Qt examples.  Should resolve Bugs #2505 and #2512.

### CODE REVIEW

**Comment by cc9cii** [comment]
view

**Comment by cc9cii** [comment]
Opps, found some issues.  Closing for now.

**Comment by cc9cii** [comment]
Fixed the issues.

**Comment by zinnschlag** [comment]
Looks mostly good. However the line number area deserves its own user setting option. I don't agree with tying it to the status bar mode.
And the mono-space setting does not belong to windows. This section is exclusively about window management.
I suggest to make a new settings page for the mono-space setting and the line number area setting.

**Comment by cc9cii** [comment]
Done.

**Comment by zinnschlag** [comment]
Nice. One more issue. Open script editors do not update when switching monospace font mode on or off.

**Comment by cc9cii** [comment]
Done.

**Pull request merged**
