### PR TITLE
Bug #2281 NPCs don't scream when they die

### PR DESCRIPTION
**Pull request by jeffreyhaines**

### CODE REVIEW

**Comment by scrawl** [comment]
Did you read my last 3 comments?

**Comment by jeffreyhaines** [comment]
I did. What did you want? Play the sounds while the console is open? I will continue to investigate the moan roar and scream..

**Comment by scrawl** [comment]
The one line change that you made in your first pull request, nothing else. The soundgen tags aren't being used by the vanilla engine, or at least can't be relied upon.

**Comment by jeffreyhaines** [comment]
Oh, now I see what you were talking about. You should be more specific next time xD

**Comment by scrawl** [comment]
Sorry about that, I have a bad habit of being indirect.

**Pull request closed without merging**
