### PR TITLE
make local documentation development easier

### PR DESCRIPTION
**Pull request by psi29a**
fix warnings, replace fonts with font, make breath/doxygen/cmake imports optional

### CODE REVIEW

**Comment by rhtucker** [comment]
Agree this is better! And you got all the misc edits, so I'll close my PR.

**Comment by scrawl** [comment]
How do I test this? Could we add some kind of Makefile or build-docs.sh ?

**Comment by psi29a** [comment]
@scrawl sure, normally there should be a make file to help automate this a bit.

For now I do the following:
```
cd openmw/docs
virtualenv venv
pip install -r requirements.txt
sphinx-build source build
```

The results are in the build, per default html.

**Comment by psi29a** [comment]
Still working on this PR, but I'll get it ready ASAP so that others can get to documenting. :)

**Comment by psi29a** [comment]
Right, this is it for now. I'll open another PR for the rest of my doxygen/autodoc magic. ;)  This one should be ready to go.

**Comment by scrawl** [comment]
> For now I do the following:
> cd openmw/docs
> virtualenv venv
> pip install -r requirements.txt
> sphinx-build source build


That didn't work for me. Some bug specific to Trusty?

<pre>
Installing collected packages: breathe, parse-cmake, sphinx, docutils, pyPEG2, Jinja2, babel, snowballstemmer, Pygments, imagesize, alabaster, MarkupSafe, pytz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/breathe-4.5.0.dist-info'

Storing debug log for failure in /home/scrawl/.pip/pip.log
</pre>

I did use the virtualenv command so it's odd that it's trying to install into /usr.

**Comment by psi29a** [comment]
Sorry...

For now I do the following:
```
cd openmw/docs
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
sphinx-build source build
```

missed a step, `source venv/bin/activate` this it make sure when you install things with pip, that it happens in the venv. any python commands are done in that venv as well.

**Pull request merged**
