### PR TITLE
[Feedback needed] Quick load inconsistent with original

### PR DESCRIPTION
**Pull request by MocquillonCedric**
I know that this bug need feeback but I tried this one to start with the base code.
The two first commits are enough to fix the bug but other add code consistency and (small) improvements (const correctness, variable construction avoided, ...)

### CODE REVIEW

**Comment by psi29a** [comment]
Wasn't this discussed in the forums? I thought the consensus was that it was good how it was now? Is there a issue/bug to track this on our tracker?

**Comment by Capostrophic** [comment]
>Is there a issue/bug to track this on our tracker?

[There is](https://bugs.openmw.org/issues/4394), and there was even a perfectly fine solution from akortunov - well, it was rejected.

**Comment by MocquillonCedric** [comment]
Sorry for that, I missed it! I'm ok with the conclusion to do not change the current behavior.

**Comment by MocquillonCedric** [comment]
I found the PR from akortunov (PR #1683), the code is effectively simpler but it does not work on all cases (when the number of quicksave is not set to one (the default), it load the first found, not necesserally the latests).
Nevertheless it does not change the fact that there is no concessus to change the current behavior.

**Pull request closed without merging**
