### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by Lazaroth**
Some tweaks to water, default sound level and mygui layouts. I've written more detailed info under each commit.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Agreed.

**Comment by Lazaroth** [comment]
I thought that might be the case, which is why I just did it on the quick ones. I'll remove the bars and leave it at the buttons tweaks.

**Comment by Lazaroth** [comment]
There. Just some pixels here and there on the buttons now, to make it line up better. Let me know if there's anything else.

**Comment by scrawl** [comment]
Ok, looks good now.

**Pull request merged**
