### PR TITLE
Editor: reset camera after cell drag and drop

### PR DESCRIPTION
**Pull request by rcutmore**
[Bug #3484](https://bugs.openmw.org/issues/3484)

When a cell is initially rendered a default camera position gets set [here](https://github.com/OpenMW/openmw/blob/master/apps/opencs/view/render/scenewidget.cpp#L312). If that cell is replaced by another via drag and drop the camera position isn't changed because *mCamPositionSet* is still set to true. When replacing cells, this change flags the camera position as not being set so it gets updated.

### CODE REVIEW

**Comment by zinnschlag** [comment]
I am seeing a problem here. If you drop a new interior cell into a scene sub view the camera jumps to a new position when you perform the first camera movement. A missing update problem maybe?

**Comment by rcutmore** [comment]
@zinnschlag You're right. I'm only seeing that issue with the orbiting camera, is that the same for you?

**Comment by zinnschlag** [comment]
Correct.

**Comment by rcutmore** [comment]
@zinnschlag The orbit cam controller needed to be re-initialized to properly center on the new cell, this contains the necessary change now.

**Pull request merged**
