### PR TITLE
Mutate base records when editing AI settings (#2798)

### PR DESCRIPTION
**Pull request by Assumeru**
Split from #2870. Following akortunov's advice a bit earlier than I initially expected.

I had assumed Add and RemoveSpell would require a similar change to AI settings, this is so far from true it's not even funny. So no reason to keep this change waiting.

### CODE REVIEW

**Comment by psi29a** [comment]
```
In file included from /home/travis/build/OpenMW/openmw/apps/openmw/mwrender/npcanimation.cpp:35:0:
2817/home/travis/build/OpenMW/openmw/apps/openmw/mwrender/../mwmechanics/actorutil.hpp: In function ‘void MWMechanics::setBaseAISetting(const string&, MWMechanics::CreatureStats::AiSetting, int)’:
2818/home/travis/build/OpenMW/openmw/apps/openmw/mwrender/../mwmechanics/actorutil.hpp:20:19: error: ‘MWBase’ has not been declared
2819         T copy = *MWBase::Environment::get().getWorld()->getStore().get<T>().find(id);
2820                   ^~~~~~
2821/home/travis/build/OpenMW/openmw/apps/openmw/mwrender/../mwmechanics/actorutil.hpp:20:74: error: expected primary-expression before ‘>’ token
2822         T copy = *MWBase::Environment::get().getWorld()->getStore().get<T>().find(id);
2823                                                                          ^
2824/home/travis/build/OpenMW/openmw/apps/openmw/mwrender/../mwmechanics/actorutil.hpp:20:76: error: expected primary-expression before ‘)’ token
2825         T copy = *MWBase::Environment::get().getWorld()->getStore().get<T>().find(id);
2826                                                                            ^
2827/home/travis/build/OpenMW/openmw/apps/openmw/mwrender/../mwmechanics/actorutil.hpp:38:9: error: ‘MWBase’ has not been declared
2828         MWBase::Environment::get().getWorld()->createOverrideRecord(copy);
2829         ^~~~~~
2830apps/openmw/CMakeFiles/openmw.dir/build.make:127: recipe for target 'apps/openmw/CMakeFiles/openmw.dir/mwrender/npcanimation.cpp.o' failed
```

**Comment by Capostrophic** [comment]
Probably shouldn't be put to actorutil header either.

**Comment by Assumeru** [comment]
Interestingly it builds just fine for me locally but I'm not sure why it would. Will fix... tomorrow.

> Probably shouldn't be put to actorutil header either.

Move it to the cpp then? Or did you have something else in mind?

**Comment by zinnschlag** [comment]
You are missing an include: ../mwbase/environment.hpp

**Comment by Capostrophic** [comment]
Too much stuff depends on actorutil.hpp, I don't want compilation times to be affected, move it to a dedicated header maybe.

**Comment by Assumeru** [comment]
Makes sense.

> You are missing an include: ../mwbase/environment.hpp

I know, I just find it concerning that my local build doesn't seem to care. At all.

**Comment by zinnschlag** [comment]
Something stuck in the build system maybe? Did you try a full rebuild?

**Comment by zinnschlag** [comment]
It seems that we are using this function only for two types (ESM::Creature, ESM::NPC). Sounds like a classical case for explicit template instantiation (http://www.cplusplus.com/articles/1C75fSEw/). Wow, that is a C++ feature that is rarely used.

**Comment by Assumeru** [comment]
I told it to Clean but it still worked afterwards. And then I just ended up changing the code instead of worrying too much. Guess I'll be deleting the folder and rerunning the CI script soon.

> explicit template instantiation

As a way to keep the code in actorutil but keep compilation time down or as an addition to the current version?

**Comment by zinnschlag** [comment]
> As a way to keep the code in actorutil but keep compilation time down

Correct.

**Comment by Assumeru** [comment]
> Wow, that is a C++ feature that is rarely used.

VS Code can't even seem to figure out how to highlight it:
image

**Comment by psi29a** [comment]
Cool, great work @Assumeru and thanks @akortunov and @zinnschlag for reviewing and helping.

**Comment by psi29a** [comment]
Unless I'm mistaken, this only partially solves https://gitlab.com/OpenMW/openmw/-/issues/2798 so no need for changelog entry yet.  That should be done in #2878 correct?

**Comment by Assumeru** [comment]
You are correct in that it only partially solves that issue. If I don't end up finishing the rest before the 0.47 release I think it might be worthwhile to create a new issue and put that in the changelog. No point worrying about that now though.

**Pull request merged**
