### PR TITLE
C++11

### PR DESCRIPTION
**Pull request by zinnschlag**
Let's see if travis is okay with it.

### CODE REVIEW

**Comment by jeaye** [comment]
Very happy to see this. :+1:

**Comment by jeaye** [comment]
Running the clang modernizer, assuming C++11 gets enabled, will help port the code to be cleaner and safer (range based for loops, auto for iterators, auto_ptr to unique_ptr, etc).

**Comment by scrawl** [comment]
Can we wait until 0.38 before merging this? I haven't heard from any OSX people having compiled the OSG version yet. We shouldn't make it even more difficult for them.

**Comment by psi29a** [comment]
Have a look at the failing clang build:
https://travis-ci.org/OpenMW/openmw/jobs/69862665

**Comment by zinnschlag** [comment]
@scrawl Really? The OSG branch has been merged into master a week ago. Everyone with a Mac on vacation? Maybe its time to ping a few people. I am okay with holding back the merge until OS X is sorted out. But I don't expect it to take so long that we can't be ready for 0.37.0.

**Comment by sandstranger** [comment]
gcc 4.9 from crystax ndk 10.2 successfully compiled it

**Comment by zinnschlag** [comment]
Regarding OS X and OSG: Got a PM back from corristo. He will get to it in a week or so.

**Comment by zinnschlag** [comment]
C++11/boost on OS X problem fixed. Just waiting for feedback from corristo about OSG and then we can merge this into master.

**Comment by scrawl** [comment]
> C++11/boost on OS X problem fixed. 

That was C++11/boost problem on Linux/Clang. We don't have an OSX travis at the moment, because there is no OSG package available.

**Comment by scrawl** [comment]
> I already switched the use of boost shared_ptr to the standard ones in c++11. If anyone wants to port over thread too, be my guest.

I am working on this now.

**Comment by jeaye** [comment]
On Fri, Jul 10, 2015 at 05:31:05AM -0700, scrawl wrote:
>      I already switched the use of boost shared_ptr to the standard ones in
>      c++11. If anyone wants to port over thread too, be my guest.

boost::function -> std::function is also, typically, a trivial conversion.

**Comment by scrawl** [comment]
Is anyone else seeing very slow build performance with C++11 enabled? I got:

<pre>
time make -j2 openmw

c++11:
real    32m37.921s

master:
real    11m58.101s
</pre>

This is on Ubuntu 14.04. Admittedly I am using an old laptop, so I would be interested in hearing some numbers for other systems.

**Comment by maqifrnswa** [comment]
travis' build (make -j2)
c++11=1148.59s (19m07s)
master=1081.00s (18m01s)
$ g++ --version
g++ (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
but it's variable based on which machine/cores you got assigned, so don't know if it's of any quantitative value

**Comment by Felix-Du** [comment]
with make -j2 for me : 
master=9m28.847s
c++11=19m45.493s

g++ (GCC) 5.1.0

Damn, it's really slower for me too.

**Comment by scrawl** [comment]
I can understand that using new language features increases compiles times, but a factor 3 seems extreme.

This could be related:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60976

I will try a downgrade to gcc-4.8 later to see if that helps.

**Comment by scrawl** [comment]
Downgraded to g++ 4.8. That performs better, but still not great:
<pre>
g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

c++11=16m22.019s
master=12m4.292s
</pre>

I know that our codebase uses lots of STL, but that hasn't been a problem till now.

With this in mind I am not sure if C++11 is universally a good thing for this project. Questions:

* How can we quantify the benefits that C++11 brings? Do they outweigh the increased build time (and thus slower development)?
* Is asking developers to downgrade their compiler a good solution? (no?)
* Is it a good idea to do a major shift in paradigms so close to our 1.0 release? By the [definition](https://forum.openmw.org/viewtopic.php?f=3&t=860&start=10#p7767) of a post-1.0 feature, is C++11 a post-1.0 feature?
* Build time is something that we're already struggling with now*. Do we really want to make it worse? 

*Tools that we want to use (Coverity Scan, Appveyor) are timing out their build. Ace did some [work](https://github.com/OpenMW/openmw/pull/655) recently to mitigate this.

**Comment by kcat** [comment]
Would precompiled headers help at all? Or whatever it is that compilers aim to use nowadays to reduce the amount of re-parsing of headers.

**Comment by jeaye** [comment]
>    With this in mind I am not sure if C++11 is universally a good thing for
>    this project. Questions:
> 
>      • How can we quantify the benefits that C++11 brings? Do they outweigh
>        the increased build time (and thus slower development)?

Absolutely yes with no questions to ask, in my opinion. The safety and modernization features provided by C++11 and C++14 are worth every bit of compile-time they add, and then some. Not only are we less reliant on boost, we have language features which will provide faster runtimes (move semantics) and a myriad of features which will help in the quality, performance, safety, and stability of openmw. Modern C++ is a landmark in developing zero-cost (runtime cost) abstractions which is unmatched in the C-based systems-level languages; the fact that it takes a while to compile the code is a drawback, sure, but it's also a testament to the fact that the C++11 compiler can do _so much_ more for us, including the addition of constexpr functions (which are relaxed in C++14 to allow local variables, loops, switches, etc).

We're four years behind already, in the adoption of C++11, though boost has been helping us _somewhat_ on that front. What we can get out of it, what we should expect and demand contributers get out of it, will make openmw a better product.

>      • Is asking developers to downgrade their compiler a good solution?
>        (no?)

No. Ask them to upgrade to GCC 5.1, which is the latest stable and fully implements C++11, as well as C++14.

>      • Is it a good idea to do a major shift in paradigms so close to our 1.0
>        release? By the [1]definition of a post-1.0 feature, is C++11 a
>        post-1.0 feature?
>      • Build time is something that we're already struggling with now*. Do we
>        really want to make it worse?

Precompiled headers and unity builds are two we can drastically improve compile-times; I've had success integrating both into large C++ codebases. I'd be interested to see the timing on GCC 5.1 versus 4.9 and 4.8.

**Comment by psi29a** [comment]
Is LTO (link time optimization) enabled by default? This can be a cause for slow compile times. It might be by default for c++11 and not for <= c++08. Just a guess.

**Comment by jeaye** [comment]
On Sat, Jul 11, 2015 at 12:45:52AM -0700, Bret Curtis wrote:
>    Is LTO (link time optimization) enabled by default? This can be a cause
>    for slow compile times. It might be by default for c++11 and not for <=
>    c++08. Just a guess.

C++98, C++03, C++11, and now C++14. C++08 doesn't exist. I'm not sure about OpenMW, but GCC doesn't enable LTO by default. You're certainly right about it sucking up a lot of time though, if it is enabled.

**Comment by zinnschlag** [comment]
Okay, here is my data:

c++11:

real	4m8.503s

master:

real	3m12.371s

Note that this is with -j8 (don't have time to wait for j2 right now) and for the entire project instead of just openmw. Shouldn't really matter, since we are interested only in the relative change.

gcc version is 4.8.4

Seems at least with 4.8 we have a consistent increase in build time by roughly 30%. That sounds somewhat realistic since c++11 is a more complex language. Of course the triple build time with 4.9 is a train wreck.


>    How can we quantify the benefits that C++11 brings? Do they outweigh the increased build time (and thus slower development)?

C++11 is a significant upgrade and I consider it to outweigh the 30% increase. Build times will increase over time anyway. That is unavoidable. And maybe Ace can dig up some other template improvements that can take the edge of the 30%.

The 3x increase is of course a completely different case.

>    Is asking developers to downgrade their compiler a good solution? (no?)

I would go with no. We should have it little requirements as possible regarding the tools used to build OpenMW. For people on fast boxes even a 3x increase doesn't really matter much, but I would still like to avoid putting additional requirements on people with slower boxes.

>    Is it a good idea to do a major shift in paradigms so close to our 1.0 release? By the definition of a post-1.0 feature, is C++11 a post-1.0 feature?

I do not consider C++11 a major shift in paradigms. Its still the same language, just with enhancements. Fundamentally its not much different from a compiler upgrade and definitely not a post-1.0 feature.

>    Build time is something that we're already struggling with now*. Do we really want to make it worse?

That's the important question. Build time will increase as the project progresses and that's something developer's will have to live with. Question is, can anything be done about tools struggling with build time? Is it possible to get the build time limit increased?

I am strictly against unity builds (I think we discussed that topic before). Looking into precompiled headers might make sense (would need to measure performance increase)

Of course the really interesting question here is why the 3x? (and 2x for later versions of gcc). Sounds rotten. All I was able to find is this here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60976


Summary: For the 1.3x build time the decision to accept c++ should be a clear yes. But for x3 things are less clear. Can't say I would be particularly happy about putting c++11 on hold again. But I am willing to do it, if necessary.

Maybe we should wait with a decision until Ace has finished his build time optimisation pass (assuming he has still things planned for that) and until someone did some measuring with precompiled headers, before we make a decision.

**Comment by LavenderMoon** [comment]
It might help to switch over to Travis CI's container-based format. Their documentation says "most projects see an improvement in build times," and also says that caching is "available for open source projects." Of course, that means you'd need to remove all instances of sudo and replace them with pulling whitelisted packages. Getting a package whitelisted hopefully shouldn't take too long.

**Comment by jeaye** [comment]
>    It might help to switch over to Travis CI's container-based format. Their
>    documentation says "most projects see an improvement in build times," and
>    also says that caching is "available for open source projects." Of course,
>    that means you'd need to remove all instances of sudo and replace them
>    with pulling whitelisted packages. Getting a package whitelisted hopefully
>    shouldn't take too long.

I have ported a couple of my C++14 projects to the container-based formats and can attest to the speed improvements. Not only do builds take less time, they also start within 10 seconds, which is a huge win.

**Comment by LavenderMoon** [comment]
To get the ball rolling, I've already added requests for them to whitelist the sources [ppa:openmw/openmw](https://github.com/travis-ci/apt-source-whitelist/issues/88) and [ppa:boost-latest/ppa](https://github.com/travis-ci/apt-source-whitelist/issues/89) and the packages [google-mock](https://github.com/travis-ci/apt-package-whitelist/issues/647), [libbullet-dev](https://github.com/travis-ci/apt-package-whitelist/issues/649), [libopenscenegraph-dev](https://github.com/travis-ci/apt-package-whitelist/issues/650), [libmygui-dev](https://github.com/travis-ci/apt-package-whitelist/issues/651), and [libunshield-dev](https://github.com/travis-ci/apt-package-whitelist/issues/648). Anyone who actually runs Linux, could you look through my Github issues linked in this post to make sure I didn't make any mistakes in my whitelisting requests?

**Comment by maqifrnswa** [comment]
Great!
From https://travis-ci.org/maqifrnswa/openmw/builds/71493424#L100
and the recently whitelisted packages, I agree with the list.

As a note: ppa:boost-latest/ppa is already whitelisted, and I don't know if there actually is a source for libsdl2-dev yet.

**Comment by LavenderMoon** [comment]
Travis has whitelisted the packages google-mock, libopenscenegraph-dev, libmygui-dev, and libunshield-dev. It looks we'll also need FFMPEG, though, judging by the errors Cmake is spitting out about missing libavcodec, libavformat, libavdevice, libavutil, libswscale, libpostproc, libswresample, and libavresample.

**Comment by maqifrnswa** [comment]
I think those errors are because there is no libav source (ppa) - they need to approve the openmw ppa so we could pull in libav

**Comment by jeaye** [comment]
What's the status of this?

**Comment by zinnschlag** [comment]
On hold. At least until 0.37.0 is out.

**Comment by Salgat** [comment]
Any updates on this?

**Comment by zinnschlag** [comment]
Sorry, nope. Everyone else is busy with other stuff at the moment.

**Comment by Salgat** [comment]
Hey @zinnschlag, just an update, the latest release of GCC now defaults to C++14. I know you guys are busy, but would love for the update, if only for some simple but very helpful things like auto and replacing boost. :grin:

https://gcc.gnu.org/gcc-6/changes.html

**Comment by zinnschlag** [comment]
No update, sorry. It looks more and more like we are moving to C++11 after OpenMW 1.0.

**Comment by Uramekus** [comment]
I know OpenMW is very near 1.0 release, any news on this? C++14  is on GCC since months and using autotypes its way easier to doing stuff, at least an C++11 rebase would make the code more friendlier to new people mess with it.

**Comment by jeaye** [comment]
Right, GCC6 (the latest stable as of 2016-04-27) defaults to `-std=c++14`, so C++11 is very much old news. I don't think, at this point, this is about compiler support; it's likely more about the big changes that would happen and who has time to make sure those don't train-wreck development.

With that said, I'd say OpenMW is at least 5 years late to the modern C++ party and waiting another year isn't going to make it any more ready.

**Comment by scrawl** [comment]
Closing, continued in #1017

**Pull request closed without merging**
