### PR TITLE
use c++11 and see what happens

### PR DESCRIPTION
**Pull request by psi29a**
Let's see what breaks...

### CODE REVIEW

**Comment by psi29a** [comment]
```
CMakeFiles/openmw.dir/engine.cpp.o: In function `boost::filesystem::copy_file(boost::filesystem::path const&, boost::filesystem::path const&)':
engine.cpp:(.text._ZN5boost10filesystem9copy_fileERKNS0_4pathES3_[_ZN5boost10filesystem9copy_fileERKNS0_4pathES3_]+0x38): undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[2]: *** [openmw] Error 1
make[1]: *** [apps/openmw/CMakeFiles/openmw.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by psi29a** [comment]
@zinnschlag or @scrawl any ideas?

**Comment by pcercuei** [comment]
CMake has a standard way to specify the C++ language:

set_target_properties(${PROJECT_NAME} PROPERTIES
	CXX_STANDARD 11
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

**Comment by Aesylwinn** [comment]
Seems to be a known [issue.](http://stackoverflow.com/questions/35007134/c-boost-undefined-reference-to-boostfilesystemdetailcopy-file)

**Comment by Aesylwinn** [comment]
The link in one of the comments on the question explains in more detail.

**Comment by kcat** [comment]
> CMake has a standard way to specify the C++ language

This unfortunately is only available in newer versions, 3.1.something as far as I can tell. Some systems are still on 3.0, so still need to check for/use ```-std=c++11``` explicitly.

**Comment by zinnschlag** [comment]
Sorry, wasn't kidding when I said I don't have time to look into this. The only hint I can give you is to look at my old C++11 branch. Most of the problems you will encounter here, are likely to have been fixed there (but probably not in the same area of the code base).

**Comment by psi29a** [comment]
One problem fixed, building on Linux looks good.  Now on OSX side:
```
In file included from /Users/travis/build/OpenMW/openmw/extern/osgQt/GraphicsWindowQt.cpp:14:
In file included from /Users/travis/build/OpenMW/openmw/extern/osgQt/GraphicsWindowQt:17:
In file included from /usr/local/opt/qt5/lib/QtOpenGL.framework/Headers/QGLWidget:1:
In file included from /usr/local/opt/qt5/lib/QtOpenGL.framework/Headers/qgl.h:40:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qwidget.h:38:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qobject.h:41:
/usr/local/opt/qt5/lib/QtCore.framework/Headers/qstring.h:756:55: error: no type named 'u16string' in namespace 'std'
    static inline QString fromStdU16String(const std::u16string &s);
```

**Comment by psi29a** [comment]
It's like wack-a-mole...

**Comment by nikolaykasyanov** [comment]
That's expected, I have to rebuild all dependencies against libc++.

**Comment by psi29a** [comment]
Ah!  so close then!

**Comment by sandstranger** [comment]
just successfully compile it with c++11 flag for Android. It seems it work for Android.

**Comment by psi29a** [comment]
:+1:

**Comment by psi29a** [comment]
@nikolaykasyanov do we have any rebuilt dependencies? :)  (no rush)

**Comment by nikolaykasyanov** [comment]
@psi29a [in progress](https://github.com/OpenMW/openmw-deps-mac/commits/c%2B%2B11)

**Comment by nikolaykasyanov** [comment]
@psi29a can you please give me access to this PR so I can edit CI script for OS X?

**Comment by psi29a** [comment]
this PR needs to be rebased, it can't be merged anymore.  how do I igive you access to the PR? can't you take this branch and make your own branch (fork)?

**Comment by nikolaykasyanov** [comment]
@psi29a https://github.com/blog/2247-improving-collaboration-with-forks

**Comment by psi29a** [comment]
Done: Allow edits from maintainers. (check)

**Comment by nikolaykasyanov** [comment]
@psi29a thanks!

Weird, I've made the change, but now GitHub complains about some conflicts and CI doesn't happen.

**Comment by nikolaykasyanov** [comment]
I'll try to build locally.

**Comment by psi29a** [comment]
As I said, this needed to be rebased  first as it won't merge cleanly.

I just rebased and pushed, it is now building... but without any commits you've done, if you have done anything.

**Comment by nikolaykasyanov** [comment]
@psi29a thanks, I reapplied my changes to rebased branch.

**Comment by nikolaykasyanov** [comment]
I need to tune linker flags for live++, it seems.

**Comment by psi29a** [comment]
Almost there! :)

**Comment by nikolaykasyanov** [comment]
I have to dig a bit more.

**Comment by nikolaykasyanov** [comment]
Just FYI, I'm on vacation till the beginning of October and won't be able to make any progress here.

**Comment by psi29a** [comment]
No worries, I'm not pushing on this.

**Comment by nikolaykasyanov** [comment]
It seems like MyGUI was built against libstdc++ instead of libc++. Fixing.

**Comment by psi29a** [comment]
Exciting...

**Comment by psi29a** [comment]
Almost there, timed out!

**Comment by psi29a** [comment]
Can we for the time being only compile openmw instead of openmw-cs and support tools?

**Comment by nikolaykasyanov** [comment]
@psi29a it builds locally, but C++11 seems to be too slow for Travis :(

**Comment by nikolaykasyanov** [comment]
@psi29a sure we can

**Comment by psi29a** [comment]
Maybe we can setup multiple travis-ci jobs, one for each component per OS?

**Comment by nikolaykasyanov** [comment]
@psi29a sounds reasonable.

**Comment by nikolaykasyanov** [comment]
Weird, now Travis isn't even showing OS X job.

**Comment by psi29a** [comment]
Does this need to be rebased against master?

**Comment by nikolaykasyanov** [comment]
@psi29a not sure. I've found that OpenMW can be built in C++11 mode on macOS just by passing `-D CMAKE_CXX_STANDARD=11` (it's supported only in recent CMake versions, though, but on macOS we're already have >= 3.1 limitation for various reasons anyway) to cmake call, without any changes to source files.

**Comment by psi29a** [comment]
That's awesome, but this patch doesn't touch any code either. It does however conflict with:
Conflicting files
CI/before_install.osx.sh
CI/before_script.osx.sh

so it needs to be rebased.

**Comment by nikolaykasyanov** [comment]
@psi29a rebased.

**Comment by psi29a** [comment]
Wooo... this time osx is building.

**Comment by nikolaykasyanov** [comment]
@psi29a yep, it was disabled in master for couple of weeks. I didn't know Travis refers to master .travis.yml for PR builds though.

**Comment by psi29a** [comment]
So close... 
```
ld: warning: object file (/tmp/openmw-deps/openmw-deps/lib/libavcodec.a(rv34dsp_init.o)) was built for newer OSX version (10.9) than being linked (10.8)
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _av_gettime_relative in libavutil.a(time.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [OpenMW.app/Contents/MacOS/openmw] Error 1
make[1]: *** [apps/openmw/CMakeFiles/openmw.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by nikolaykasyanov** [comment]
That must be new. Let me try something.

**Comment by psi29a** [comment]
We get a lot of warnings: 
was built for newer OSX version (10.9) than being linked (10.8)

that might be something to investigate.

**Comment by nikolaykasyanov** [comment]
Ooops

**Comment by nikolaykasyanov** [comment]
It actually builds, it's packaging process who fails. I'll look into it a bit later.

**Comment by psi29a** [comment]
It works! :)

**Comment by psi29a** [comment]
We've proven that without touching any code, we can get openmw to compile with c++11.

It is noticeably slower however. ;)

**Comment by psi29a** [comment]
@zinnschlag @scrawl what do you think? Worth stepping over to by default?

**Comment by BorisKourt** [comment]
As a bystander on the fence about contributing I would love for this to be made official. There are many small things about C++11 that make it more desirable to work with.

**Comment by scrawl** [comment]
Call me crazy, but I don't think C++11 is nearly as important for this project as some of you (mostly the bystanders) make it out to be. The bottleneck in our project at this point isn't coding (never was, to be honest), instead its figuring out what needs to be done and how to do it. 

We already have a huge codebase, the majority of which will not undergo any more changes until 1.0. The benefit of switching to a new language standard is somewhat alleviated when 98% of the code isn't going to use it. Mass-refactoring changes will not be accepted either, I don't want to waste time getting code "modernised" that works perfectly fine as is.

Using C++11 for new code I'd be ok with, however what still puts me off is the absurd increase in compilation time with C++11 enabled in the compiler. We'd also need to put new coding guidelines in place and make sure all our nightly build environments will still work. Overall the cost vs. benefit is not worth it at the moment, IMO.

**Comment by kcat** [comment]
> We already have a huge codebase, the majority of which will not undergo any more changes until 1.0.

The interesting thing is that we don't have to make any real changes to take advantage of it. Simply enabling C++11 will allow the compiler to perform better optimizations, for example by utilizing ```constexpr``` on standard functions which only gets enabled when compiling as C++11 (and relatedly, enabling C++14 will allow even more functions to be marked as ```constexpr``` that C++11 neglected). There's also things like move semantics that the compiler can utilize automatically without us having to explicitly code for it (though that option will obviously be there for any new or modified code we make).

There's also something to be said for C++11 enabling faster code turnaround. Changes that do need to be done on the road to 1.0, can be made quicker (and safer) by utilizing C++11 features (lambdas, variadic templates, and a host of new classes and algorithms to do what we'd otherwise need to do manually, find and pull in from Boost, or do sketchy workarounds for). So, when you say:

> figuring out what needs to be done and how to do it

C++11 will help with that too, by providing more built-in tools for doing things.

> Overall the cost vs. benefit is not worth it at the moment, IMO.

If it's not worth it now, when will it be? C++11 support is ubiquitous enough that I don't think alienating older compilers is much of a concern. Compiling with C++11 enabled will always be slower by virtue of the standard being more complex. The penalty can be alleviated some by reducing how much we use/include things like Boost, which is known to cause severe compilation slowdowns, but that will take some time to do thoroughly regardless of when the switch occurs. The cost vs benefit will be the same in the future as it is now. The only other option is to stick with C++03 forever, but that doesn't seem viable long term.

It's been noted too that MSVC doesn't even give you an option. If you have an MSVC version that supports C++11, it'll accept C++11 code and you compile as C++11, no questions. Same for C++14, and soon C++17. The only hangup is with Clang and GCC, where you have to explicitly enable C++11 (though as mentioned, newer versions of GCC are going to default to C++14). This discussion is effectively whether or not we'll pass ```-std=c++11``` in CXXFLAGS for earlier compilers, to accept code that requires it.

Sweeping codebase changes aren't going to occur given how large the codebase is. Any significant changes are going to be done piecemeal over time, generally while doing other work in the same vicinity. Delaying C++11 adoption is ultimately just creating more work by forcing new code/patches to be stuck with C++03, when it could be written with C++11 correctness, and need to be updated later when the switch is eventually made. More work later, to avoid passing the ```-std=c++11``` flag now.

**Comment by psi29a** [comment]
The only real drawback is the compilation, the rest that @scrawl pointed out has already been solved. We can switch over without any code changes and all build environments are working.

**Comment by NeveHanter** [comment]
It would be great to have C++11 at last as there's `constexpr`, `auto`which comes handy when using i.e. iterators, lambdas which would ease STL functional programming which I actually get more readable than specialized for's.

Difference between C++03 and C++11 is quite large as it's 1m on my 4.4Ghz 4770K which actually hit hard only when doing full rebuild.

Also as far as I've checked on my machine OpenMW compiles with C++14 without problems and compile times differs in negligible 1s (yes I know that one reason not to use C++14 is compiler support, but I don't know any modern compiler not supporting this standard).

**Comment by EmbraceUnity** [comment]
As a longtime "bystander," I see big benefits to moving to the latest standard, but no benefits that would be worth delaying the release of 1.0

After 1.0, not only should new code be using the new standard, but the entire codebase should be refactored and modernized. And not just using C++11, but at least C++14.

I would like to see usage of boost cut down, and all those compilation warnings gone. And hopefully the next version of OSG will be ready by then too.

**Comment by psi29a** [comment]
Did a quick conflict resolution, we're still good to go here. :)

I'm still thinking we can break down our travis builds to build specific 'apps' instead of one large monolithic build. This will work around the build time problem.

**Comment by psi29a** [comment]
Rebased... hope I got all the osx libs right.

**Comment by psi29a** [comment]
Last bit converts std::auto_ptr to std::unique_ptr

**Comment by Allofich** [comment]
Looks like you've got one warning in the Clang build:

`/home/travis/build/OpenMW/openmw/apps/openmw/mwgui/bookpage.cpp:1053:28: warning: 
      implicit conversion of NULL constant to 'boost::detail::sp_nullptr_t'
      (aka 'int') [-Wnull-conversion]
            if (newBook != NULL)`

**Comment by psi29a** [comment]
No more Clang warnings there. ;)

**Comment by Allofich** [comment]
Looks like all that happened is that it built successfully!

**Comment by nikolaykasyanov** [comment]
@Allofich yeah, but macOS build time is disappointing.

**Comment by psi29a** [comment]
For the time being, it is OK. We can later change up our build matrix to build based on APP which should help and be useful in that we know which part of the project failed to build just by looking at which build failed. This also helps increase parallelism since we can get at least 2 builds going on at once.  This however should not be a blocker for the merge, just something we can work on in the future.

**Comment by ehiggs** [comment]
I think a quicker/better solution will be to build CI with `-O0` and, of course, release builds with `-O3`. Of course this can slow down tests, so maybe some tuning with specific parameters or `-O1` or `-O2` could be used.

**Comment by jvoisin** [comment]
> Using C++11 for new code I'd be ok with, however what still puts me off is the absurd increase in compilation time with C++11 enabled in the compiler.

Is the compilation time issue addressed?

**Comment by psi29a** [comment]
I got a reply from one of the GCC developers about the compilation time with C++11 and this was his response:

> Jonathan Wakely:
> When I've looked into such slowdowns it's been because of all the new
> constructors added to every container for extra allocator support i.e.
> it's Bloomberg's fault!

If I understand this correctly, it is an known issue and we'll just have to deal with or not. There might be compiler fixes in the future.

Honestly, this isn't a problem for me as a developer (compile times are tolerable) and for travis-ci/appveyor.  We can do things to improve turn-around time on the CI side of things.

**Comment by ehiggs** [comment]
>I think a quicker/better solution will be to build CI with -O0 and, of course, release builds with -O3. Of course this can slow down tests, so maybe some tuning with specific parameters or -O1 or -O2 could be used.

I took a quick look at this  (using `-ftime-report`) and found that most of the compilation time is in parsing and template resolution. e.g. from `windowbase.cpp`:

```
 phase parsing           :   3.64 (39%) usr   0.79 (58%) sys   4.44 (41%) wall  699562 kB (61%) ggc
 phase lang. deferred    :   1.48 (16%) usr   0.21 (15%) sys   1.69 (16%) wall  225739 kB (20%) ggc
 phase opt and generate  :   3.95 (42%) usr   0.35 (26%) sys   4.31 (40%) wall  188647 kB (17%) ggc
 phase last asm          :   0.36 ( 4%) usr   0.01 ( 1%) sys   0.36 ( 3%) wall   23130 kB ( 2%) ggc
 |name lookup            :   0.49 ( 5%) usr   0.09 ( 7%) sys   0.69 ( 6%) wall   70889 kB ( 6%) ggc
 |overload resolution    :   1.30 (14%) usr   0.19 (14%) sys   1.40 (13%) wall  203167 kB (18%) ggc
 garbage collection      :   1.11 (12%) usr   0.00 ( 0%) sys   1.11 (10%) wall       0 kB ( 0%) ggc
 template instantiation  :   2.92 (31%) usr   0.46 (34%) sys   3.54 (33%) wall  551351 kB (48%) ggc
```

One solution here would be more use of the pimpl idiom to reduce the amount of (repeated) template instantiation at compile time for included headers since it needs to do this for every compilation unit that includes aforementioned headers.

**Comment by jwakely** [comment]
> There might be compiler fixes in the future.

Unlikely, since the additional constructors are required for conformance to the C++ standard, so there's nothing to "fix" (except for generally improving the compilation speed and memory usage of g++, which is always desirable but not always possible).

**Comment by ehiggs** [comment]
Does that really have a substantive positive effect? The parser (which takes the most time) is still parsing all these templates for each header included. I can see that it would reduce template instantiation time, but pimpl should reduce both template instantiation as well as parsing time (at the cost of indirection at runtime).

**Comment by jwakely** [comment]
Right, it won't reduce the parsing phase, but template instantiation was still a pretty significant chunk of the time in the report you showed above.

**Comment by nikolaykasyanov** [comment]
Enabling release config actually made macOS compilation faster ¯\_(ツ)_/¯

**Comment by ehiggs** [comment]
From offline discussions with @jwakely 

>It's not uncommon for optimised builds to compile faster. Sometimes
(especially with idiomatic C++) early inlining and other simple
optimisations reduce the overall size of the AST and symbol tables
(e.g. by removing any references to inlined functions) so the later
passes have less work to do (smaller trees to process, and less code
to generate, and fewer debug symbols to generate). G++ is often memory
bound, and so reducing the footprint of the code being compiled can
make it much faster.

**Comment by psi29a** [comment]
Honestly, for travis-ci, doing release builds shouldn't be a problem. The results are tossed anyway because T-CI doesn't host builds (unlike appveyor)

**Comment by psi29a** [comment]
I did some de-boosting work and managed to shave a minute off Linux build times. This will sit in another branch for now: psi29a/openmw/deboosting

**Comment by psi29a** [comment]
@scrawl Do we have your seal of approval? :)

**Comment by zinnschlag** [comment]
This does not merge cleanly with master.

CONFLICT (content): Merge conflict in CI/before_install.osx.sh

Don't have the time to investigate now. Ping we again once this is resolved.

**Comment by psi29a** [comment]
@nikolaykasyanov Can you resolve this?  Or tell me which is correct?

**Comment by psi29a** [comment]
@zinnschlag rebased and corrected output.   Original test before push -f was green: 
https://travis-ci.org/OpenMW/openmw/builds/241205115?utm_source=github_status&utm_medium=notification

This should be no different. :)

**Comment by psi29a** [comment]
\o/

**Comment by nikolaykasyanov** [comment]
@psi29a sorry for the delay, was busy at work on Friday.

Congrats everyone! I'll update dependencies for macOS after merging [respective PR](https://github.com/OpenMW/openmw-deps-mac/pull/14).

**Pull request merged**
