### PR TITLE
Downgrade MyGUI to 3.2.2 for Windows builds

### PR DESCRIPTION
**Pull request by ace13**
Have only just barely had time to build and push these, no idea if they'll even be able to build with.

If the CI works, could someone run some proper builds and report back?

### CODE REVIEW

**Comment by AnyOldName3** [comment]
Built fine, but I'm still getting the `Error in framelistener: MyGUI EXCEPTION : Trying to add same delegate twice.
 in MyGUI at b:\programming\libraries\mygui\source\myguiengine\include\MyGUI_DelegateImplement.h (line 255)` error when using settings dropdowns.

**Comment by ace13** [comment]
That's strange...

Can you look in the prerequest header, check the version in there?

On 28 Oct 2017 14:56, "AnyOldName3" <notifications@github.com> wrote:

Built fine, but I'm still getting the Error in framelistener: MyGUI
EXCEPTION : Trying to add same delegate twice. in MyGUI at
b:\programming\libraries\mygui\source\myguiengine\include\MyGUI_DelegateImplement.h
(line 255) error when using settings dropdowns.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenMW/openmw/pull/1528#issuecomment-340188998>, or mute
the thread

**Comment by AnyOldName3** [comment]
```C
#define MYGUI_VERSION_MAJOR 3
#define MYGUI_VERSION_MINOR 2
#define MYGUI_VERSION_PATCH 2
```
I'm going to try a full rebuild in case CMake hasn't marked dependencies properly.

**Comment by scrawl** [comment]
I'll merge for now because this purely changes the version number / file name, if there's any issue with the actual package that can still be resolved by uploading a new package without making another PR.

**Comment by AnyOldName3** [comment]
It's still broken for me after a full rebuild.

**Pull request merged**
