### PR TITLE
fix GCC warnings

### PR DESCRIPTION
**Pull request by akortunov**
1. Generally we should avoid of negative values shifting, because result can depend on platform.
SCHAR_MIN is -127 or less, depending on platform.
Since we divide result anyway, probably we do not need shifts here at all.
2. GCC complains about possibly uninitialized 'format' variable, it is more likely a false-positive.
I guess it is safe to initialize this variable just for sure.

### CODE REVIEW

**Comment by psi29a** [comment]
I'm OK with this.

@kcat  any thing trigger you?

**Comment by kcat** [comment]
May as well initialize `srate` as well. Otherwise, looks alright to me.

**Comment by akortunov** [comment]
> May as well initialize srate as well.

Done.

**Comment by psi29a** [comment]
Waiting on CI...

**Comment by Capostrophic** [comment]
One of Travis builds was successful.

**Comment by psi29a** [comment]
@Capostrophic no patience? :P

**Pull request merged**
