### PR TITLE
Add saving land and land textures.  Should resolve Bug #2447.

### PR DESCRIPTION
**Pull request by cc9cii**
Only tested by examining the saved file with a binary editor (for LAND and LTEX).

### CODE REVIEW

**Comment by psi29a** [comment]
*rubs hands together greedily*

**Comment by psi29a** [comment]
Terrain is still not being loaded by OpenMW. 

Tested by opening the ESM, saving it out as omwaddon then loading OpenMW. The result is the same, see only the water plain and falling through.

**Comment by cc9cii** [comment]
Ok, will have a look.

**Comment by zinnschlag** [comment]
IIRC some of the terrain data is loaded in asynchronously on demand. This would of course be a problem for saving, because the data you want to save might not be there.

Forcing a full load for everything in the modified section might be the solution here, because unless the user only wants to look at the content file without saving it, that needs to be loaded anyway. In this case it should be made sure that the data is completely loaded during the load process (and not just have the asynchronous loading triggered); maybe even.bypassing the asynchronous aspect of the loading process.

Another option might be to load the missing data when saving. This would save loading time in the case of the user only wanting to look at a content file without saving it. However I suspect that this approach would be a lot more complicated.

**Comment by cc9cii** [comment]
@psi29a please try this one.

@zinnschlag you fixed the data loading issue last time yourself.

**Comment by zinnschlag** [comment]
Really? can't remember ever working on that. Getting old, I guess.

**Comment by psi29a** [comment]
Well done!  File size jumped from 1MiB to 4MiB which is more inline with the original ESM file. In addition to this, I can now see terrain and do everything normally.  Great job and thank you!

@zinnschlag no worries, you've been at this awhile. ;)

**Pull request merged**
