### PR TITLE
SoundGens verifier (Feature #1999)

### PR DESCRIPTION
**Pull request by smbas**
Checks:
* Is the sound exist
* Is the creature exist (if it's specified)
* Is the creature of the type Type_Creature (if it's specified)

Example:

soundgencheck

### CODE REVIEW

**Comment by smbas** [comment]
Add check:
* Is the sound specified

**Comment by scrawl** [comment]
SoundGen.mCreature doesn't need to be a valid creature record. It can also be a string specified in a creature record's mOriginal field.

For example:

SoundGen.mCreature = "slaughterfish"

Creature: slaughterfish_big
mOriginal = "slaughterfish"

Creature: slaughterfish_small
mOriginal = "slaughterfish"

See the implementation in [OpenMW](https://github.com/scrawl/openmw/blob/master/apps/openmw/mwclass/creature.cpp#L674).

**Comment by smbas** [comment]
So, mOriginal may contain an ordinary string that isn't a creature ID. Right?

**Comment by smbas** [comment]
Perhaps, we need also a check for a original creature. For example, if SoundGen.mCreature = "slaughterfish_big", the checker informs that this creature has the original "slaughterfish" and it must be specified instead.

**Comment by zinnschlag** [comment]
There is a slaughterfish ID in my Morrowind.esm file. If the original field specifies an original creature, this implies that there is an original creature ID. Do we actually know of any use cases for a non-existent original creature or if that works in vanilla? If not I suggest we go for the strict version, because otherwise that would complicate things quite a bit on the OpenMW-CS side (we currently have no support for a string field that may or may not be an ID).

Also, when looking at the OpenMW code it seems the current implementation would not allow to specify a separate sound generator for a derived creature. Again, I don't know if vanilla does the same, but it sounds a bit unintuitive and even if that is the case allowing such a specialisation would be a natural expansion that should not break anything.

**Comment by smbas** [comment]
The checker doesn't find any non-creature ID, when checks the Morrowind.esm.

**Comment by scrawl** [comment]
Ok, then let's keep it simple for now. If the verifier doesn't find any false positives in official ESM's, then I'm ok with merging this PR as-is.

**Pull request merged**
