### PR TITLE
Replace volatile bools with std::atomic<bool>

### PR DESCRIPTION
**Pull request by xyzz**
Volatiles shouldn't be used for thread synchronization.

### CODE REVIEW

**Comment by psi29a** [comment]
Pulling in @kcat , but otherwise OK!

**Comment by kcat** [comment]
Looks like it should be okay. You could probably improve it by not using `memory_order_seq_cst` (the heavy-handed default for reading/writing atomic vars), but other than performance concerns it should be functionally fine.

**Comment by psi29a** [comment]
What kind of performance concerns are we talking about here? Anything we can look at later?

**Comment by kcat** [comment]
IIRC, std::memory_order_seq_cst employs a memory fence, while usually you just need acquire/release semantics to ensure correct ordering relative to other reads/writes (sometimes not even that). It shouldn't be a significant issue unless it's being done in a really hot loop, so it can be something to look at later.

**Comment by psi29a** [comment]
Merged, thanks! :)

**Pull request merged**
