### PR TITLE
Editor - Bug #2429: The cloned record does not have the original record's data.

### PR DESCRIPTION
**Pull request by cc9cii**
Should fix bug #2429.

~~Actually, maybe it should be "Added", closing until a new solution is pushed.~~

### CODE REVIEW

**Comment by cc9cii** [comment]
About to push a new solution.

**Comment by cc9cii** [comment]
@zinnschlag, I don't think this is correct, either.  It seems wrong to be copying stuff in a clone() command.  Maybe State_ModifiedOnly should mean the data is read from mBase rather than mModified?

**Comment by zinnschlag** [comment]
I don't follow what this PR is about.

> Maybe State_ModifiedOnly should mean the data is read from mBase rather than mModified? 

No. ModifiedOnly means that the record does not exist in base. Only in modified.

And cloning records should not clone base data. That would break revert. Base is immutable after loading. You are not allowed to change it at all.

**Comment by cc9cii** [comment]
> I don't follow what this PR is about

When a referenceable record is cloned, only mBase is copied then mState is set as State_ModifiedOnly.  That means later when the newly cloned record is inserted to the table, mModified (uninitialised at this point) is returned from the Record<ESXRecordT>::get() method.

Two possible solutions I can see are either:

(a) copy mBase to mModified during clone() which is what I've done, or
(b) have Record<ESXRecordT>::get() return mBase when mState == State_ModifiedOnly

Maybe you can see another way?

**Comment by zinnschlag** [comment]
Option (a) is actually correct. Guess I didn't get it because the back and forth stuff is a bit confusing. As mentioned before (b) would break pretty much everything. It is really, really wrong.

The implementation of (a) in this PR is a bit unfortunate and also not entirely correct (you don't set mState correctly). Maybe it is time to add a new constructor to CSMWorld::Record? Something like:

RecordBase (State state, const ESXRecordT *base = 0, const ESXRRecordT *modified = 0)

with mBase and mModified only set if the respective argument is not 0
?

You can then call this constructor with (ModifyOnly, 0, &(this->get())). This would allow writing the clone function in a single instruction that does not risk having a memory leak (in case of an exception).

**Comment by cc9cii** [comment]
Ok, will do. A question, though.  Commands use clone() methods for undo/redo.  Wouldn't they want both mBase and mModified (as well as mState) preserved?  i.e. do we also need another clone() method?

**Comment by cc9cii** [comment]
Seems to make every record for a new addon to be "Added", which doesn't seem correct.  Are they meant to be "Base"?

**Comment by cc9cii** [comment]
Fixed.

**Comment by zinnschlag** [comment]
>  A question, though. Commands use clone() methods for undo/redo. Wouldn't they want both mBase and mModified (as well as mState) preserved? i.e. do we also need another clone() method?

Well, shit! You are right. When I was looking at the clone function I was thinking of the clone command. But these are not the same. Sorry, got confused there.

It seems that the original Record clone function was correct. And when we look at the clone command, it actually does not make use of the clone function, but uses Collection<ESXRecordT, IdAccessorT>::cloneRecord, which seems to do the right thing too (what you proposed as (a)).

Actually, it looks like pretty much everything has been working as it is supposed to all along. So that brings us back to my original question. What problem do you want to address with this PR?

**Comment by cc9cii** [comment]
> What problem do you want to address with this PR?

The problem: Bug #2429. The cloned record does not have the original record's data.

**Comment by zinnschlag** [comment]
Okay. Now I get it. The problem was specific to RefIdCollection. Apparently the RefIdCollection::cloneRecord function is broken.

We are almost there now. Your modifiedCopy function still has a potential memory leak. Either go with the new constructor we had earlier or just use a std::auto_ptr. Also, remove the record->mBase = ESXRecordT() line. It is unnecessary and does not what you think what it is doing anyway. And while we are at it, you can construct the new Record object with the default constructor instead of the copy constructor. Anything that is copied is overwritten anyway.

**Comment by cc9cii** [comment]
Yeah, I've been sloppy :-(  Sorry about that.

**Comment by zinnschlag** [comment]
No problem. Shit happens.

One more round, unfortunately. We don't C++11 yet. Therefore the = default statement can not be used.

**Comment by cc9cii** [comment]
Done.  Not sure if I can safely let the compiler to generate copy constructor and assignment operator?

**Comment by zinnschlag** [comment]
You need the default constructor, because if there are any other constructors the compiler will not create one automatically. Copy constructor and assignment operator are not affected by this. The defaults will do fine.

I am going to quickly clean that up myself and then merge.

**Pull request merged**
