### PR TITLE
Reduce twitching for player turning animations

### PR DESCRIPTION
**Pull request by akortunov**
Fixes [bug #4574](https://gitlab.com/OpenMW/openmw/issues/4574). Related [forum topic](https://forum.openmw.org/viewtopic.php?f=6&t=5039).

During turning for small angles anim speed is near 0, so mTurnAnimationThreshold almost make no sense. As workaround, we use a smoothTurn function for NPCs, but we can not use it for player.

The main idea: play turning animation a bit for player after he stops to turn.
As for me, it is not ideal solution in its current state, but it definely better than our current behaviour.

### CODE REVIEW

**Comment by scrawl** [comment]
Isn't your solution framerate dependent? For the same turning speed, ```rot``` will be larger if your framerate is low.

**Comment by Capostrophic** [comment]
When turning animation is still playing and you jump the character might briefly continue to play turning animation and then immediately transition into jumping pose. It's jarring.

**Comment by zinnschlag** [comment]
Both scrawl and Capostrophic have reasonable concerns. Can these be addressed? If yes, I would be okay with a merge.

**Comment by Capostrophic** [comment]
There's a related [hack](https://github.com/OpenMW/openmw/blob/openmw-44/apps/openmw/mwmechanics/aiwander.cpp#L482) in AiWander. Something should be done about it.

**Comment by akortunov** [comment]
The only thing left is do determine when turning animations should be interrupted (as for greetings in AiWander), and when should not.

**Comment by Capostrophic** [comment]
I finally figured out what's wrong with spellcasting stance turning animation. Apparently there *are* unique animation groups, but they have uncommon naming format: they're SpellTurnLeft and SpellTurnRight, while OpenMW tries to find TurnLeftSpell and TurnRightSpell (and fails) as if they were usual weapon shortgroup turning animation groups.

**Comment by akortunov** [comment]
> I finally figured out what's wrong with spellcasting stance turning animation. 

Will you create a separate bugreport and PR, or it is up to me to fix this issue?

**Comment by Capostrophic** [comment]
Hm. I'll do it by myself.

**Comment by akortunov** [comment]
Since we already have smoothing for NPCs, I suggest to use a new behaviour only for player.

**Comment by akortunov** [comment]
Reworked a bit:
1. Use new behaviour only for player.
2. Fix regression in check if we need to reset the mTurnAnimationThreshold.
3. Limit turning speed multiplier from 1.0 to 1.5 - with slow turning spead multiplier was near 0 and mTurnAnimationThreshold was pretty useless - we did not actually play turning animation anyway.
@Capostrophic, can you retest this PR?

**Comment by Capostrophic** [comment]
I'll be able to do that some time next week.

**Comment by Capostrophic** [comment]
Tested. Seems to work fine, although turning animation continues if you jump during it and land again, which looks a bit odd. Possibly related to my changes to same-movement-anim handling.

Another, not exactly related to this PR, but annoying issue is that turning animations are framerate dependent (happens with traditional behavior too), which causes all kinds of issues during turning if vertical synchronization is turned off and there is no framerate limit. If the framerate is too high, it causes the turning animation to loop from the start endlessly without actually turning the character, and while in this case it's a bit better than the original behavior (because the animation has to run for a bit), it still looks bad.

**Comment by akortunov** [comment]
> Another, not exactly related to this PR, but annoying issue is that turning animations are framerate dependent (happens with traditional behavior too), which causes all kinds of issues during turning if vertical synchronization is turned off and there is no framerate limit. If the framerate is too high, it causes the turning animation to loop from the start endlessly without actually turning the character, and while in this case it's a bit better than the original behavior (because the animation has to run for a bit), it still looks bad.

Because animation speed is tied to rotation amount. With very high FPS rotation amount is near 0 and we almost do not play turning animation.

**Comment by akortunov** [comment]
> turning animation continues after you jump during it and land again

As in vanilla game. Looks like movement animation blending do not work well with landing animation.

**Comment by akortunov** [comment]
I increased priority of jumping animations. Landing should work fine now.

**Comment by zinnschlag** [comment]
Missing changelog entry.

**Pull request merged**
