### PR TITLE
Slow down simulated mouse with right trigger  in menus.

### PR DESCRIPTION
**Pull request by rohit-n**
EDIT: I'm reducing the scope of this PR for something more tenable. See posts below.

### CODE REVIEW

**Comment by scrawl** [comment]
I'm not too fond of this implementation. From what I see you would need to change every menu in the game to add support.

My suggestion is to handle everything in WindowManager, walk over the currently visible MyGUI widgets (you don't need to talk to the individual menu classes to get those), filter out widgets that can't be interacted with, and then cycle through the remaining widgets with gamepad buttons.

**Comment by rohit-n** [comment]
Thanks for the feedback.

I'm looking at the code now - I'm guessing `MyGUI::VectorWidgetPtr mListWindowRoot` is what I need to look at when iterating through widgets?

**Comment by scrawl** [comment]
You can use:
<pre>
MyGUI::Gui::getInstance().getEnumerator()
</pre>

**Comment by LavenderMoon** [comment]
How does the original Xbox version of Morrowind handle the inventory? I haven't played it in forever.

**Comment by rohit-n** [comment]
@LavenderMoon I never played the Xbox version, but assume you just used the d-pad to move through items.

I haven't had much time to work on this solution, so I have an alternate proposal that sounds more elegant: if the player is in menu using the controller, what about using a button (maybe one of the triggers) to slow down the movement of the simulated mouse? This would make it much easier to make fine selections, which is especially important in the dialog and inventory menus. This would make controller gameplay much more enjoyable, in my opinion.

**Comment by scrawl** [comment]
Sounds like a stopgap solution, but I'm fine with it.

**Pull request merged**
