### PR TITLE
Enhance optimizer to reduce number of drawables

### PR DESCRIPTION
**Pull request by mp3butcher**
add an loop until convergence to redundant free node graph.
It reduces drastically number of drawables and so on FPS

### CODE REVIEW

**Comment by Capostrophic** [comment]
Have you measured the difference?

**Comment by akortunov** [comment]
I do not see any noticable difference.

**Comment by mp3butcher** [comment]
I have an old intel chipset on an old celeron...so it would'nt be significative to compare..
The nuber of drawable is divide by more than 2 so it rocks

**Comment by akortunov** [comment]
> The nuber of drawable is divide by more than 2 so it rocks

On which scene? I tested it in Ebonheart (which is known to have badly optimized meshes).
In both master and this PR testing scene had near 3100 drawables.

**Comment by akortunov** [comment]
> if you don't see any difference you're surely bound by the fragment cost

How the fragment cost affects resulting scene graph and count of drawables in it?

**Comment by mp3butcher** [comment]
mmh perhaps I mod some datavariance else where...Let me check

**Comment by akortunov** [comment]
> 12000

It is ain't right. Pofiler in Balmora shows about 2000-3000 drawables with default settings, and about 7000 with real-time shadows and water reflections for everything.

**Comment by wareya** [comment]
Uh. Where in Balmora? The position and angle where I stand make a huge difference, from 1500 to 10k. FoV matters too.

**Comment by mp3butcher** [comment]
@akortunov 
i set view distance to 66666 and watch in the worst direction and it give me 12k
(I don't know why I answer such trivial critic)
Let me the time to confirm I mod other stuff before yelling

**Pull request closed without merging**
