### PR TITLE
Fix a build issue

### PR DESCRIPTION
**Pull request by ace13**
```
C2536: 'SceneUtil::LightSource::SceneUtil::LightSource::mLight' : cannot specify explicit initializer for arrays
```

### CODE REVIEW

**Comment by scrawl** [comment]
<pre>error: ‘copy_n’ is not a member of ‘std’</pre>
Missing ```algorithm``` include?

**Comment by scrawl** [comment]
copy_n appears to be a C++11 function.

**Comment by ace13** [comment]
I'm apparently far too used to C++11.

**Comment by scrawl** [comment]
std::begin is also C++11.

I've pushed different fix to master, that should work.

**Comment by ace13** [comment]
Thanks, sorry for being too new :grin:

**Comment by ace13** [comment]
I really need to finish the final remaining AppVeyor issues, so we can have windows CI support for pull requests.
The 1h+ build time for those is not that nice though...

**Pull request closed without merging**
