### PR TITLE
[WIP] Editor: Update osgQt in extern

### PR DESCRIPTION
**Pull request by unelsson**
Very heavily WIP, but a PR for commenting and pointing out stuff early. Idea is to update osgQt in extern. It's used by the OpenMW-CS scene view. I understood it generated some errors, and it's probably a reason for a crash when exiting OpenMW-CS compiled with Qt5.

The PR is currently broken (probably should use osgQOpenGLWidget instead of Window), but it does compile. There might be additional unused clutter here too. I haven't really worked with CMakeLists or Qt MOC before.

What's done:
- scenewidget uses osgQOpenGLWindow by default instead of GraphicsWindowQt
- Added Qt5Gui to CMakeLists, because QOpenGLFunctions is part of it and osgQOpenGLWindow is derived from it.
- Added all cpp and header files from osgQt to extern
- Added namespace osgQt to osgQOpenGLWindow, osgQOpenGLWidget and OSGRenderer.
- Removed export macros from osgQt function declarations just to make stuff more clear for me, but maybe those are needed for some win compilers, I don't know (please help).
E.g. removed "OSGQOPENGL_EXPORT" present in https://github.com/openscenegraph/osgQt/blob/cf47af8c7608b1b2e0f6a70ba8b730db8a8cdff8/include/osgQOpenGL/osgQOpenGLWindow#L31 , but not in https://github.com/unelsson/openmw/blob/da16836ba3de1c5744b7b2e15437dd100386b612/extern/osgQt/osgQOpenGLWindow#L34

### CODE REVIEW

**Comment by akortunov** [comment]
Are there plans to continue development of this PR?

**Comment by psi29a** [comment]
@unelsson not sure if you're still on this but... Perhaps a read here would help?
http://www.openscenegraph.org/index.php/documentation/guides/programming-guides/93-viewer-vs-compositeviewer

Basically... we need compositeviewer (a list of views) since OpenMW-CS can have multiple views (terrain, objects, etc.).  The 'viewer' was meant purely for one camera (or more slave cameras that you switch between), while the compositeviewer was to allow for multiple viewers to be shown at once.

The examples do indeed only show osgViewer::Viewer so it looks like we'll have to maintain our own osgViewer::CompositeViewer to have a list of osgViewer::Viewer instances in OpenMW-CS.

**Comment by psi29a** [comment]
Looks like we're not the only ones to come across this problem:
https://github.com/rdiankov/openrave/pull/583/files

**Comment by psi29a** [comment]
It seems that dropped osgQt and rolled their own using QOSGViewerWidget

Could be worth looking into.

**Comment by psi29a** [comment]
```
- class ViewerWidget : public QWidget, public osgViewer::CompositeViewer
+ class QOSGViewerWidget : public QOpenGLWidget
```

**Comment by unelsson** [comment]
I've been looking at this a bit. Seems that the old GraphicsWindowQt created a GLWidget 
`_widget = new GLWidget( traits2qglFormat( _traits.get() ), parent, shareWidget, flags );` which is `class GLWidget : public QGLWidget`.

It might be what OpenMW needs. QGLWidget is in QT5: "QGLWidget provides functionality for displaying OpenGL graphics integrated into a Qt application." Anyway, the process isn't just about updating to the new osgQt, but rather dropping that and making something that works. Gotta look into this later!

**Comment by AnyOldName3** [comment]
QGLWidget was deprecated in favour of QOpenGLWidget with the 5.0 release. The whole point of this exercise is to migrate from the deprecated Qt4 approach to the non-deprecated Qt5 approach.

**Comment by psi29a** [comment]
Closing this for now since work has stalled. Feel free to continue your work here: https://gitlab.com/OpenMW/openmw

**Pull request closed without merging**
