### PR TITLE
 Fix error: invalid application of 'sizeof' to an incomplete type 'Video::VideoPlayer' (No include)

### PR DESCRIPTION
**Pull request by pineapplemachine**
Alternate solution to same problem as in https://github.com/OpenMW/openmw/pull/1888 added in response to @zinnschlag's comment https://github.com/OpenMW/openmw/pull/1888#issuecomment-415951250

### CODE REVIEW

**Comment by zinnschlag** [comment]
This looks okay. Now to some formalities (sorry about that).

1. Please file an issue on our bug tracker for this change so we have it on record. You can create a single issue for both this and your other PR, since they both basically do the same job (improve compatibility for a specific compiler in regards to use of smart pointers and forward declarations).

2. We recently changed how we handle new developers (that is not documented anywhere yet): Please add a commit to this PR, in which you add your name to the AUTHORS.md file.

**Comment by pineapplemachine** [comment]
@zinnschlag Ok, I added to AUTHORS.md and created an issue here: https://gitlab.com/OpenMW/openmw/issues/4613

**Comment by akortunov** [comment]
Add entry to CHANGELOG.md too.

**Comment by akortunov** [comment]
Looks like there is something wrong with CI itself.
And just for reference: prefer rebase over merge - additional merge commits are not good.

**Comment by pineapplemachine** [comment]
My b. I will rebase next time.

**Pull request merged**
