### PR TITLE
fix resolution on HiDPI displays under Windows

### PR DESCRIPTION
**Pull request by sthalik**
This particular Windows manifest bit fixes resolution choice on my Windows 2160p display. The operating system likes to confuse itself unless the particular piece of boilerplate is included in the executable.

Otherwise it's necessary to force "application scaling" in the executable's compatibility options.

### CODE REVIEW

**Comment by Capostrophic** [comment]
Is this related to [bug 3623](https://gitlab.com/OpenMW/openmw/issues/3623) somehow?

**Comment by sthalik** [comment]
Yes, at least in windowed mode.

**Comment by psi29a** [comment]
Is there anyone on Window that can validate this?

**Comment by lysol90** [comment]
I only have a 1440p monitor, and it is on my linux rig, so sorry no. But I think @AnyOldName3 had some nice phat resolution monitor..?

**Comment by AnyOldName3** [comment]
I've got a 1440p monitor, What do I need to do?

**Comment by AnyOldName3** [comment]
I have resolution scaling set to 100%, though, as it's not a small monitor.

**Comment by akortunov** [comment]
> I've got a 1440p monitor, What do I need to do?

I suppose you should try to increase scaling factor in Windows settings (set it to something like 120% or 150%).

**Comment by sthalik** [comment]
The following were broken for me:

- windowed native resolution without frames (was too big)
- fullscreen native resolution (display's OSD shows lower resolution)

**Comment by psi29a** [comment]
Anyone else on windows to test this?

**Comment by AnyOldName3** [comment]
I've tested this and it does indeed resolve the issues it's supposed to.

**Pull request merged**
