### PR TITLE
Started settings guide and general edits

### PR DESCRIPTION
**Pull request by rhtucker**
mod-install
settings/camera through map

### CODE REVIEW

**Comment by scrawl** [comment]
Probably not a good idea to duplicate the wiki content. Would be more work to keep information up to date. Either the wiki should link to the manual, or the manual should link to the wiki. Given that the wiki is already complete, I suggest the latter.

**Comment by rhtucker** [comment]
I had thought about that too. To be honest I think all our documentation should be on the wiki. However, if we're doing documentation that's going to be available online and offline, then I would like to have it as complete as possible. Also, our wiki actually isn't complete. There are a large number of settings not included, but I figured it would be easiest to duplicate what's on the wiki first before adding in the rest.

**Comment by rhtucker** [comment]
Also, sorry about the spam of commits. I'm trying to work on it directly in GitHub because I'm at work right now lol. Only found the preview button just now.

**Comment by rhtucker** [comment]
scrawl, what does it mean that these did not pass the Travis CI check? This is all markup and not actual code so why wouldn't it like it? Also, let's go ahead and just include the settings for now and we can delete them later if we decide upkeep is going to be too annoying. I can bring it up on the forums.

**Comment by scrawl** [comment]
Don't worry about travis, it often runs out of its build time limit. 

Duplication is out of the question. If we merge this PR then the wiki should be deleted and just point to readthedocs.

I'm now leaning towards readthedocs being a better choice than the wiki for settings documentation. So feel free to continue.

Advantages of readthedocs:
* Documentation in the repo makes it easier to update when a new feature is merged, we can just merge the documentation for that feature in the same PR
* We have different versions of the documentation for each OpenMW branch/version (e.g. one for git master, one for the current stable release). This is built into readthedocs as far as I can tell.

Advantages of wiki:
* Lower barrier to entry (everyone can use a wiki, but not everyone knows how to use github).

**Comment by rhtucker** [comment]
Here's a link to the forum thread I talked about this on in case you have anything else you want to add. https://forum.openmw.org/viewtopic.php?f=6&t=3644&start=50

Otherwise I guess we're good to go.

**Comment by jeffreyhaines** [comment]
I'm loving ReadTheDocs' I think it makes a lot of sense to bundle OpenMW documentation. I believe it will encourage more people to read it. I also think it makes it easier for us to peer review. Centralizing most of the official OpenMW development stuff on Github.

Perhaps we compile the PDF with the images we release or it could be as easy as hyperlinks in the OpenMW launcher or OpenCS menu bar.

**Comment by psi29a** [comment]
Small fix to resolve conflicts, so please pull latest commit.

@rhtucker What is the status here, is this PR ready for review/merging?

**Comment by rhtucker** [comment]
My content is all good to go. It's far from complete but I forget where I left off. The combination of SkyrimSE, the holidays starting, and finally buying Fallout 4 has completely derailed my progress lol.

Do I need to pull from the master before you can merge this?

**Comment by psi29a** [comment]
No, you don't have to do anything. :)  I was just saying I had to fix a few things, you just had to pull from upstream if you wanted it fixed on your side too.

**Comment by psi29a** [comment]
@scrawl we good with going this route? We can begin to reference the RTD in the wiki pages.

**Comment by scrawl** [comment]
No, we should merge this when complete, then delete the wiki settings page in one fell swoop.

**Comment by psi29a** [comment]
That is what I mean, are you comfortable with porting from wiki to here?  It seemed like you were still weighing the options above. Having your blessing is a good motivation to continue working on this PR.

There is still work here left to do, I was just giving it a bit more attention. :)

**Comment by scrawl** [comment]
Yes, porting seems like a good idea. My 'blessing' was here: 

> So feel free to continue.

**Comment by jeffreyhaines** [comment]
Do we have a least two eyes reading RTD to make sure it's accurate?

**Comment by rhtucker** [comment]
Ok, if we're waiting on me to finish porting the settings portion, I'll try and get on it ASAP. When I pull, it won't overwrite any of my unmerged edits correct? Still a bit new to GitHub so I'm not totally sure on it's limitations.

@jeffreyhaines For the most part I've been taking info directly from the wiki, so as long as that's been edited for accuracy, we should be good with minimal involvement. In general though, I'm not sure how deeply scrawl and psi29a have been reading the docs. I imagine they're just skimming to spot check content. If we read each others commits and at least one of them is reading somewhat closely I think we're probably good to go.

**Comment by psi29a** [comment]
I think it best to rebase this branch against master, it seems the last bit of commits does things outside of the docs directory that it shouldn't be touching.

**Comment by rhtucker** [comment]
How are scrawl's edits even in this branch? Also, apparently rebasing is what I thought merging was this whole time. Is there a way to do this while online? It would be nice if I didn't have to wait until I was home.

**Comment by rhtucker** [comment]
@psi29a I think I rebased this branch, but it didn't change anything, or at least the shell didn't show any differences. Regardless, if you and @scrawl want to look through the settings, I've finished simply moving the wiki contents over so it's ready to be merged. I'd like to get this merged, then post on the forums about it for people to go through. I'll probably wait until Atahualpa looks through it, and then have him delete the settings portion of the wiki just so he's in the loop since he seems to be spearheading all this kind of stuff.

**Comment by psi29a** [comment]
A rebase usually means: 
`git rebase master --force`
which is not the same as a merge:
`git merge master`

The former takes master and applies the patches from this branch on top, this does a bit of history cleanup. A merge will just take the patches from master and apply them on top of this branch. It is usually nicer in terms of git history to do the former and that is what we encourage here. :)

**Comment by scrawl** [comment]
@psi29a, how do we host different versions on RTD? What I see in the version selector is "master" and "latest". What does latest refer to? Is there a way to have "master" "0.41", "0.40", and so on? Also, the default for the base url https://openmw.readthedocs.io/ should be the latest stable version, not master. Could you look into this?

**Comment by rhtucker** [comment]
Alright, FINALLY got around to rebasing this properly. Please merge the request when you get a chance.

**Comment by psi29a** [comment]
@scrawl I'm looking into it. You mean, latest stable should be the latest release. Thus that is now 0.41 correct?

**Comment by psi29a** [comment]
Here is the deal, if we want a 'stable' then we need a tag 'stable' that points to the latest release. We can ask @raevol to do this in addition to making a release. This would trigger RTD to build against tag. Is this acceptable?

What should I do about 'latest' and 'master', latest mean whatever is HEAD for example. Should we drop these or just drop 'latest' and keep master but set default to 'stable'?

**Comment by psi29a** [comment]
https://openmw.readthedocs.io should not automagically go to https://openmw.readthedocs.io/en/stable/

It just requires someone to delete the 'stable' tag and re-tag when a new release is made.

**Comment by scrawl** [comment]
Thanks psi29a, version selection looks great now!

**Comment by scrawl** [comment]
There we go:

https://openmw.readthedocs.io/en/master/openmw-mods/settings/index.html

Looks very nice!

@rhtucker, are you looking for more Wiki content to port? I think any one of these 3 should be next:
https://wiki.openmw.org/index.php?title=Fonts
https://wiki.openmw.org/index.php?title=Native_Mesh_Format
https://wiki.openmw.org/index.php?title=TextureModding

**Comment by rhtucker** [comment]
The versioning is perfect. Do keep the latest and master tags, because documentation is so far behind development that everything should be available as it's written and merged.

I'm going to include Fonts as my next port, then the info on texture modding. I actually think the NIF stuff should stay on the wiki just because it deals more with specific 3rd party software and will benefit more from community involvement inherent in the wiki. I'll include all this in a forum post so we don't have to keep talking on a merged thread.

**Pull request merged**
