### PR TITLE
Correcting https://bugs.openmw.org/issues/3906

### PR DESCRIPTION
**Pull request by Siimacore**
Function "setupGameSettings" was called 2 times in "wizardFinished", so I moved the game data check in a function and called it in "showFirstRunDialog" as it is called only once at the start of the launcher.

### CODE REVIEW

**Comment by scrawl** [comment]
Since the PR the launcher will show 'Could not find data files' every time for a valid config. Reverted for now.

**Comment by Siimacore** [comment]
Do I need to redo a PR ?

**Comment by Thunderforge** [comment]
@Siimacore Are you still interested in redoing this PR? I'm starting to work on some launcher improvements and am wanting to know what to keep in mind.

**Comment by Siimacore** [comment]
Hi, yes corrected it but wasn't sure what to do, I'll try to PR this tonight Ok ?

**Comment by Siimacore** [comment]
Re-submited a PR : https://github.com/OpenMW/openmw/pull/1370

**Pull request merged**
