### PR TITLE
CS Manual - extend tour ring tutorial

### PR DESCRIPTION
**Pull request by loriel2**
Add a section for giving the ring to an npc - both as shopkeeper and for simple interaction.

Images are reasonably small files, but style isn't the same as previous images in the tour, so please consider them as placeholders until I can replicate the style

### CODE REVIEW

**Comment by psi29a** [comment]
How long would it take to replicate the style? Is it really that important?

**Comment by loriel2** [comment]
I don't think it's essential, but it would look more professional if the style is consistent.

Two issues:
Colour of top bar/border - red in mine, grey in others
"Shadow" effect on others, missing from mine

Don't yet know how to achieve these, so don't know how long it will take to do.

**Comment by rhtucker** [comment]
I agree that the style should be consistent. However, I don't necessarily like styling them at all because it means in order to be consistent, everyone contributing has to do the exact same thing. @psi29a, would we be able to add a shadow and outline via the Sphinx templates? Ideally that would all be taken care of via CSS once the document is generated. Granted this would then require us to re-screenshot the pics that are already there.

If that is going to be more trouble than it's worth, then we should decide on exactly what we want the style to be and create a very brief step by step guide on how to achieve it. Slightly more annoying would be having a single person in charge of doing the styling and just have them go through every image we use.

The OS styling for windows and window borders may end up being too difficult to realistically make everything uniform anyway so maybe all of this is moot.

**Comment by psi29a** [comment]
RTD has their own style and I'm not sure how easy that is to modify. I'm also not the person to ask about modifying CSS. ;)

My only question was trying to limit the amount of binaries introduced into the repo. If these icons are placeholders, then they will be dead weight that gets carried around and never used.

**Comment by loriel2** [comment]
Being a github novice, I hadn't appreciated that - I assumed the placeholders would be deleted/overwritten, but presumably they have to be retained to provide a full back history.
I know there are file size questions on the other PR in this area (#1363), leading to a question of "Where should the images be kept?". Would it be sensible to commit both of these with no images, pending resolution of the various questions?

**Comment by scrawl** [comment]
Yes, better to remove the images for now - both for file size and so we can possibly re-shoot them all in a consistent style.

**Comment by loriel2** [comment]
Closing this PR - now replaced by  #1451

**Pull request closed without merging**
