### PR TITLE
Add Construction Set option to launcher screen

### PR DESCRIPTION
**Pull request by h313**
Fix for issue [#4366](https://bugs.openmw.org/issues/4366). I set the CS button to `HelpRole` for convenience, but would it be better for it to have its own separate event handler and switch it to an `ActionRole`?

### CODE REVIEW

**Comment by jvoisin** [comment]
(Do feel free to add a screenshot to your PR ♥)

**Comment by zinnschlag** [comment]
This doesn't look very useful. A proper installation should already have a way to launch the editor (via the usual means provided by the respective OS).

I can kinda see the point behind this feature request. But the intention was probably to jump directly into loading with the content files selected in the launcher instead of having to load them again in the editor.

Also, it is not guaranteed the the editor is even installed. That would have to be checked and if necessary the launcher button disabled or hidden.

**Comment by scrawl** [comment]
> This doesn't look very useful. A proper installation should already have a way to launch the editor (via the usual means provided by the respective OS).

I agree. Having two ways to accomplish the same thing is usually not a good idea. Let's not make the launcher more bloated than it already is (and will be if #1623 is merged). 

> But the intention was probably to jump directly into loading with the content files selected in the launcher instead of having to load them again in the editor.

That wouldn't seem obvious to me. Plus, which file should be the 'active' file to actually edit?

**Comment by zinnschlag** [comment]
> That wouldn't seem obvious to me.

It kinda is. Here is a use-case: You set up a content file list to play. And when you hit the play button something goes wrong. As a content developer (even if it is not your content) you probably would then load up these files into the editor to have a look yourself.

This overlaps with the other PR you linked. But the target audience is a different one.  #1623 aims at a player, who probably only once to check if things work and at most report a bug to the actual content developer. Such a user may not even have OpenMW-CS installed and may not know how to use it.
On the other hand this PR is clearly aimed at content developers.

**Comment by zinnschlag** [comment]
After sleeping over this issue I have come to the conclusion that this alternative approach is indeed better (if it is found desirable to address the use-case I mentioned). We really don't want to tie in the editor into the launcher if we can avoid it. From an end-user perspective OpenMW/Launcher and OpenMW-CS are two separate products.

I will therefore close this PR and the issue. Thanks anyway.

**Pull request closed without merging**
