### PR TITLE
Fix faction requirement calculations

### PR DESCRIPTION
**Pull request by akortunov**
Fixes [bug #5499](https://gitlab.com/OpenMW/openmw/-/issues/5499).
Actually we should check `mSkill2` twice instead of once.
Also I added meaningful names, as in TES CS, instead of `mSkill1` and `mSkill2`.

### CODE REVIEW

**Comment by MAtahualpa** [comment]
I think you misunderstood my post: The int vector of skill values is sorted. That means we can test the first element for the primary skill check (which we already do) and then need to test the second one (if there are only two skills in the faction's required-skill list) or the third one (if there are more than two skills and that list). In any case, we only need one check for the primary skill and one check for the favoured ones.

**Comment by akortunov** [comment]
> In any case, we only need one check for the primary skill and one check for the favoured ones.

There is a possibility that faction has only two favoured skills. In this case access to the 3d element can lead to crash.

**Comment by MAtahualpa** [comment]
(Sorry for moving my original comment to the issue itself on GitLab.)

We essentially mean the same. I emphasised the fact that we only need to check the second element if there are two skills in the required-skills list and the third one if there are more than two in that list. How you implement these checks is up to you.

**Comment by MAtahualpa** [comment]
I also guessed from the existing code that the author made the mistake of taking all skill values into consideration for the favoured-skill checks, but forgot that the primary skill (the first element of the vector) is already "used" and needs to be ignored.

**Comment by psi29a** [comment]
Thanks both of you. :)

**Pull request merged**
