### PR TITLE
Unix console hotkeys

### PR DESCRIPTION
**Pull request by Assumeru**
Implements ^W (delete word), ^U (delete line), ^LEFT (move past word), and ^RIGHT (move past word) in the in-game console.

Mostly just because I keep trying to use them.

### CODE REVIEW

**Comment by Capostrophic** [comment]
Ctrl-Left Arrow and Ctrl-Right Arrow have been [held off](https://gitlab.com/OpenMW/openmw/issues/2648) because they're kind of supposed to be implemented on the side of MyGUI, so that every editable text field in the GUI can react to these combinations.

**Comment by wareya** [comment]
MyGUI fork when?

**Comment by Assumeru** [comment]
> 
> 
> MyGUI fork when?
https://github.com/Assumeru/mygui/commit/294c0c05a27e68a7732d9f3b07549c75870376c8

But I still haven't gotten OpenMW to compile (and run) with that so...

**Comment by Assumeru** [comment]
g++ actually gave me a useful error message unlike Visual Studio, so #2424 fixes my compilation issue and https://github.com/MyGUI/mygui/pull/161 implements stuff in MyGUI.

**Comment by Capostrophic** [comment]
Works fine.
Although this really should be implemented on MyGUI's side too, I'm merging this anyway since MyGUI development... isn't very active... and these shortcuts can always be moved there once it's revived some day.

**Pull request merged**
