### PR TITLE
Switch Appveyor CI to x64 VS2015 / 2017

### PR DESCRIPTION
**Pull request by ananace**
Just to help debug the apparent CI failures on Windows

### CODE REVIEW

**Comment by psi29a** [comment]
It's building! :)

**Comment by ananace** [comment]
Yeah, seems Appveyor have dropped lots of preinstalled pieces, along them Qt5 for VS2013.  
They also don't have 32-bit packages at all for VS2017.

Going to be redoing my CI scripts and packages to focus on 2015/2017 it seems.

**Comment by psi29a** [comment]
I noticed that Appveyor also has support for Linux; Ubuntu 16.04 and soon 18.04
This could be interesting.
https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/

**Comment by ananace** [comment]
Personally a bigger fan of Travis both when it comes to configuration and actual web UI.

But yeah, always nice to see more possibilities for CI stuff. 

And it seems like we're not using the right build environment image, we need to change it to Visual Studio 2017

**Comment by ananace** [comment]
Well, we're going to lose CI for 2013, but things seem to be working like this at least

**Comment by psi29a** [comment]
2013 is now 5 years old. I'm not worried about that.

**Comment by ananace** [comment]
Anyway, this should be ready for merging, builds are passing and keeping it on verbose mode in CI purposes should really be the default anyway.

**Comment by psi29a** [comment]
Done

**Pull request merged**
