### PR TITLE
remove BOM and fix inconsistent line endings

### PR DESCRIPTION
**Pull request by maqifrnswa**
Some line endings got turned into windows line endings:
find . -type f -exec dos2unix {} \;

UTF-16 bit BOMs were added to several .layout files which were described as UTF-8 in the header.
find . -type f -print0 | xargs -0 sed -i '1s/^\xEF\xBB\xBF//'

### CODE REVIEW

**Comment by maqifrnswa** [comment]
Thanks! I've had some time over break to actually learn about openmw's
code... I've figured out the scripting engine and dabbled with opencs, I
can look into this now too.

**Comment by maqifrnswa** [comment]
Here is the problem, I think - I'll keep looking at it
http://mariusbancila.ro/blog/2008/10/20/writing-utf-8-files-in-c/
and see Stream I/O
http://www.i18nguy.com/unicode/c-unicode.html
and
http://msdn.microsoft.com/en-us/library/c4cy2b8e.aspx
and similar problem in another project:
http://sourceforge.net/p/log4cplus/bugs/284/

In MyGUI_XmlDocument.cpp:
        bool Document::save(std::ostream& _stream)
        {
            if (!mDeclaration)
            {
                mLastError = ErrorType::NoXMLDeclaration;
                return false;
            }

            // заголовок utf8
            _stream << (char)0xEFu;
            _stream << (char)0xBBu;
            _stream << (char)0xBFu;

            mDeclaration->save(_stream, 0);
            if (mRoot)
                mRoot->save(_stream, 0);

            return true;
        }

even though you are writing a BOM to _stream, windows systems will put
the UTF-16 BOM even before you put the UTF-8 BOM into the stream.

manually inserting that BOM in Document::save might not be necessary -
just make sure that whatever is output in Element::save (that is,
mDeclaration->save(_stream, 0); and mRoot->save(_stream, 0);) are
UTF-8.

How about defining a locale facet in bool Document::save(const
std::wstring& _filename)


    std::ofstream _stream;
    std::locale loc ( std::locale(),  new std::codecvt_utf8_utf16<wchar_t> );
    _stream.imbue(loc)
    stream.open(_filename);


Since this function is only called if _filename is a wstring, we've
already identified that you're on a system with strings are wchar_t
(UTF-16, i.e. windows), so let's just put in the facet so stream <<
will be output as UTF-16.

I think this will work, but I don't have a development environment on
windows. I can give it a shot, but will probably need some tweaking to
make sure we got it totally right on windows platforms.

**Comment by scrawl** [comment]
Are you suggesting that this problem only shows up on Windows systems? That doesn't seem to be the case, as I've saved the files on Linux.

**Comment by maqifrnswa** [comment]
hmm, that's what I thought - maybe someone else edited the files in windows
and now they are stuck with the wrong BOM. I guess the test would be to
open other files in windows, save them (or save as a new file name), and
see if this happens again.

There is a lot of code trying to manage encoding, and it looks right.
That's why I feel like something is happening with the << operator using
the windows locale and UTF-16.

**Comment by maqifrnswa** [comment]
This is not a bug. I'm examining the files byte by byte, they conform to what should be output from the MyGUI Layout Editor. Files should start with 0xEFBBBF (seen in  MyGUI_XmlDocument.cpp: Document::save(std::ostream& _stream) )

But some questions for mygui devs to consider:
1) Of the 55 files in openmw/files/mygui/*.layout, 51 have no BOM and 4 have the correct UTF-8 BOM. Is this desired or intentional?
2) Is the BOM necessary? UTF-8 for xml files is a defacto standard and is declared in the declaration. Would removing explicit writing of the BOM be more consistent? The Unicode standard says it is neither required nor recommended, but is useful when converting between encodings.
3) Windows systems potentially will insert a UTF-16 BOM before the UTF-8 BOM. If a bug comes up about this in the future, the devs can look into imbuing a utf8 to 16 codecvt facet into the stream class (see above comment for how to do that).

Feel free to close this after review. Thanks.

**Comment by scrawl** [comment]
> 1) Of the 55 files in openmw/files/mygui/*.layout, 51 have no BOM and 4 have the correct UTF-8 BOM. Is this desired or intentional?

The files were originally written by hand in a text editor. The possibility to use the layout editor has only been added recently, so only a small portion of the files have since been altered with the layout editor.

**Pull request closed without merging**
