### PR TITLE
Joystick Support

### PR DESCRIPTION
**Pull request by Digmaster**
Try number 2!
So I rewrote it from scratch, because I was a really bad coder when I first started.
However, if anyone could tell me how to have the axis controls start at to .5, as opposed to 0, would be a godsend. I tried in a couple places to no effect, and it results in the camera going absolutely nuts when you first start. This is the only issue I can find presently.
Scrawl asked, last time I did this, to change A_MoveLeft/A_MoveRight to use increasing and decreasing controls, however as nothing else does this I did not know how to do this, nor do I see the benefit.
Hopefully everything works correctly! I have touched openMW nor C++ in forever so I'm rather rusty.

### CODE REVIEW

**Comment by Digmaster** [comment]
So I've solved the problems listed above, although I'm not entirely sure if I'm handling the gamecontrollerdb.txt thing right (mostly on the cmake side, this is my first foray into that language). In addition, the only way I see to fix the downgrading problem is to increment the input file version number (change it to input_v3). As it's a fairly rarely encountered problem and would clear everyone's input bindings, I'm not sure if that's what should be done?

**Comment by scrawl** [comment]
> the only way I see to fix the downgrading problem is to increment the input file version number (change it to input_v3). As it's a fairly rarely encountered problem and would clear everyone's input bindings, I'm not sure if that's what should be done?

Even if the problem is rare, it needs to be fixed. Most importantly, we need to be able to bisect earlier revisions.

How about the following: rename the output filename for writing to _v3.xml, but allow *reading* from both _v2.xml and _v3.xml (preferring the v3 variant). That would take care of the compatibility issue, while still keeping the user's input bindings when switching to a later version.

**Comment by Digmaster** [comment]
I didn't realize it was for bisections, I just changed it to be input-v3. The first commit (Uses v3 file instead of v2) adds a random file and for the life of me I can't figure out a way to undo this. I've reverted it on my machine, but I can't find any way to remove the file, it doesn't even exist on my machine anymore.

**Comment by scrawl** [comment]
There is also "OpenMW.cpb" which was added in some much earlier commit.
I like to use git commit --fixup and rebase --autosquash to get rid of unwanted files. https://stackoverflow.com/questions/3103589/how-can-i-easily-fixup-a-past-commit (if you're not familiar with this, make sure to back up your repository first).

**Comment by Digmaster** [comment]
I had to revert my change which added the file so it was tracked, then remove it from tracking. Hopefully everything is good now

**Comment by scrawl** [comment]
The files are still in the history. I would rather have them removed completely (via rebase) so that the size of the repository doesn't unnecessarily increase.

**Comment by Digmaster** [comment]
I'm having many issues with what you suggested to get rid of the files. I've checked out the bad commit, removed the file (via git rm), then git commit --fixup. However when I try to use rebase --autosquash, it throws tons of merge conflicts. Simply skipping them doesn't allow me to push the branch back to github ()as I need to add them, however it's literally like 25 merge conflicts, I'm assuming I'm doing it wrong). I'm not super experienced with git and I'm at a loss for how I'm suppose to currectly do this.

**Comment by scrawl** [comment]
Something like this should work:

1. reset to the state of the branch as it's pushed here:
<pre>
git reset --hard origin/master
</pre>
2. remove the commit "Remove unwanted files":
<pre>
git rebase -i 2ceac48d8d6b8~1
</pre>
This will open a text editor, to remove the commit you need to delete the corresponding line, save&exit.
3. remove the commit e58e8090f79, which added the qrc_wizard.cxx file and didn't add anything else:
<pre>
git rebase -i e58e8090f79~1
</pre>
(proceed as in step 2)
4. fix the commit that added OpenMW.cbp:
<pre>
git rm OpenMW.cbp
git commit --fixup 76a61c8893d325
git rebase -i --autosquash 76a61c8893d325~1
</pre>

**Comment by Digmaster** [comment]
I have to go one commit before in order to see the commit when I do git rebase -i ...(so instead of git rebase -i 2ceac48d8d6b8~1, I did  0bc645f), I was able to remove "Remove unwanted files", however trying to do the same for the commit that added qrc_wizard results in a million merge conflicts like before. I'm assuming this is because I merged in the upstream branch? Thanks for the help, it's about time tha tI learned my way around git.

**Comment by scrawl** [comment]
> I have to go one commit before in order to see the commit when I do git rebase -i ...(so instead of git rebase -i 2ceac48~1, I did 0bc645f),

That is what the "~1" is for (it means the parent of commit 2ceac48, ~2 would be the parent's parent, etc)

> however trying to do the same for the commit that added qrc_wizard results in a million merge conflicts like before. I'm assuming this is because I merged in the upstream branch?

Ah yes, the merge is causing issues. Fortunately there is a -p option to rebase "instead of ignoring merges, try to recreate them".
It looks like we have to fix the merge conflicts again, but that isn't a big issue, just back up the affected files, then copy them over.
This worked for me:
<pre>
git rebase -p -i 76a61c8893d325~1
# Change the following lines:
edit 76a61c8 Minor code cleanup
(delete line) pick e58e809 Uses v3 file instead of v2
(delete line) pick b43b0f8 Revert "Uses v3 file instead of v2"
(delete line) pick 0bc645f Revert "Revert "Uses v3 file instead of v2""
(delete line) pick 2ceac48 Removed unwanted files
# Save & exit

git rm OpenMW.cbp
git commit --amend
git rebase --continue

# Copy the results of the merge conflict resolution

# Mark conflicts as resolved
git add files/mygui/openmw_settings_window.layout extern/oics/ICSInputControlSystem_joystick.cpp apps/openmw/mwgui/settingswindow.cpp
git rebase --continue

# git fails to apply the next merge for some reason, this doesn't matter, there were no conflicts on this one so just skip it

git rebase --skip
</pre>

**Comment by Digmaster** [comment]
Ok! Hopefully this all works! Thanks again for walking me through this.

**Comment by scrawl** [comment]
That didn't do it. The rebased commits are now applied on top of the previous commits, instead of replacing them. Also commit 98625893c17 isn't squashed, so the file is still in the history. The "resolve merge conflicts" commit shouldn't be there, instead the conflicts should be resolved within the merge commit.
I suggest to hard-reset to commit 3066b9aa6c8ef and try again.

**Comment by scrawl** [comment]
I have rebased it in #501.

**Pull request closed without merging**
