### PR TITLE
hide touch camera on Android

### PR DESCRIPTION
**Pull request by sandstranger**
With this PR , touch camera hiding on Android automatically

### CODE REVIEW

**Comment by scrawl** [comment]
Can we handle this outside of the windowmanager code? E.g. by querying ```windowManager->getCursorVisible()``` every frame and set the touch state accordingly. If we can do that, can we move the code into the android-port repository just like the rest of the Java code?

**Comment by sandstranger** [comment]
Yes it is possible .we can move all  this code in t android-port repository and build it as a separate library ,because android studio can work with c ++ code . I'll do it then

**Comment by sandstranger** [comment]
I use my c++ class as
class ControlsHider : public MWGui::WindowManager {
public:
    ControlsHider();
    void* runBackgroundTask(void* arg);
    bool getCursorVisible() {
        MWGui::WindowManager::getCursorVisible();
    }
    void hideControls(bool needHideControls);
    void backgroundTask();

};:
but bool getCursorVisible() always return true even in the game . What am I doing wrong ?

**Comment by Ragora** [comment]
@sandstranger
Looks like you're not actually returning the result of the window manager get cursor visible.

**Comment by sandstranger** [comment]
even with
bool getCursorVisible() {
        return MWGui::WindowManager::getCursorVisible();
    }
it always return true . wtf

**Comment by Ragora** [comment]
That's odd, I haven't poked OpenMW in ages. I would say it's either not doing quite what you think or its bugged somewhere. Would have to wait on @scrawl or some such then. I saw the notification and the issue initially seemed simple enough (I make mistakes like that all the time personally).

**Comment by sandstranger** [comment]
maybe I get an incorrect reference to the class, because in buiding of this class I include already prebuilt openmw library with MWGui::WindowManager class

**Comment by scrawl** [comment]
You'd need to get the existing instance of the game's WindowManager:
<pre>
MWBase::Environment::get().getWindowManager()
</pre>

**Comment by sandstranger** [comment]
It is crashes , when I trying to get instance

**Comment by scrawl** [comment]
When are you trying to get it? You would need to wait until the Engine::prepareEngine() has completed.

**Comment by sandstranger** [comment]
Solved : It is crashes , because using java threads for getting cursor thread was very bad idea, because jni method must be called every frame on main java thread.
I will try to use c++ pthreads for it

**Comment by sandstranger** [comment]
Ok , with this commit everything working fine 
https://github.com/OpenMW/android-port/commit/55bf00060326d74d04556ba67ec5e44435e9bf8a

**Pull request closed without merging**
