### PR TITLE
[Testing needed] Unhardcode sunset and sunrise settings

### PR DESCRIPTION
**Pull request by akortunov**
Fixes [bug #1990](https://bugs.openmw.org/issues/1990).
Implements settings, mentioned in the bug desctiption.

It would be nice to have an independent testing of this feature.

### CODE REVIEW

**Comment by akortunov** [comment]
> Слушай, не думали над созданием дискорд канала?

OpenMW already has the [Discord channel](https://discordapp.com/invite/wd3eSas).

**Comment by Artemex** [comment]
thanks, man!

**Comment by scrawl** [comment]
I think we need to be more specific on what needs to be tested lest this PR becomes stale. Why do you want an independent test? Is it because different installations may have a different INI? And what needs to be tested, I suppose that sunset and sunrise are at the same hour as before and/or as in vanilla MW?

**Comment by zinnschlag** [comment]
This looks like another PR that we may want to merge early in the development cycle of 0.45 to get maximum testing. Any objections?

**Comment by Capostrophic** [comment]
I don't have any.

**Comment by psi29a** [comment]
<3 how everyone is just blazing through the remaining issues, 0.44 is not even yet out the door and we're doing great on 0.45!  Great job everyone! :)

**Pull request merged**
