### PR TITLE
Fix for https://bugs.openmw.org/issues/4319

### PR DESCRIPTION
**Pull request by uramer**
Tested with both the testing mesh provided by Greatness7 and problematic meshes in Tamriel Data by Project Tamriel.

### CODE REVIEW

**Comment by Capostrophic** [comment]
Why bother leaving the code in place if it's never going to be used again?

**Comment by uramer** [comment]
I guess would be more reasonable to remove it, will change in a sec
Also I've found some bugs in the current master branch when I was testing this, should I report them and if yes, where?

**Comment by akortunov** [comment]
> if yes, where?

On the bugtracker, obviously.

**Comment by scrawl** [comment]
Can you make a test mesh that has no dedicated collision mesh, then set one of it's meshes to 'Hidden' to see if the hidden one then shows in the collision mesh or not?

**Comment by uramer** [comment]
Ok, just done it, the result is the same as in vanilla: the hidden mesh doesn't draw, but still collides

**Pull request merged**
