### PR TITLE
[Incomplete, do not merge] Issue 5097: Handle ints/floats passed as strings

### PR DESCRIPTION
**Pull request by ampaulg**
https://gitlab.com/OpenMW/openmw/issues/5097

For names in quotes, Scanner::scanName now also checks for whether they're ints or floats, and then calls the appropriate parser function as necessary.

Tested by using the modcurrenthealth console command on the player with the different possible argument formats.

### CODE REVIEW

**Comment by Capostrophic** [comment]
I think this isn't wise. String parser can't parse numbers and this will probably cause something like messagebox "1.0" to fail.

**Comment by ampaulg** [comment]
You're right, passing "1.0" to functions like messagebox and streammusic has errors because the incorrect type gets passed with this strategy.

Is it possible for the scanner or parser to determine the necessary types for the function, and then try to convert to the required type as needed?

**Comment by Capostrophic** [comment]
See parseArguments(); different parsers parse different types of arguments. String parser parses strings. Expression parser parses numerical arguments, such as (in case of parseName) variables which correspond to numbers. As in the bug report's description, my thought was to make expression parser's parseName function understand not just variable names, but also quoted numbers.

**Comment by ampaulg** [comment]
Thanks for the info, I'll take another look. I'll close this PR for now and put up a new one when it's redone.

**Pull request closed without merging**
