### PR TITLE
Make sure forcePPL and clamp are defined in the editor

### PR DESCRIPTION
**Pull request by Capostrophic**
After somewhat recent changes to the initialization of these shader defines editor was logging "stuff undefined" errors for akortunov, which meant that the editor would fail to create shaders and fall back to fixed function pipeline. AnyOldName3 recommended to put the initialization of these defines for the editor here specifically. Now what gets used is the previous defaults.

### CODE REVIEW

**Comment by akortunov** [comment]
Now it complains about "Undefined shadows_enabled".

**Comment by akortunov** [comment]
And about "shadow_texture_unit_list"

**Comment by akortunov** [comment]
Additional defines:
```
    defines["shadows_enabled"] = "0";
    defines["shadow_texture_unit_list"] = "";
    defines["shadowMapsOverlap"] = "0";
    defines["useShadowDebugOverlay"] = "0";
    defines["perspectiveShadowMaps"] = "0";
    defines["disableNormalOffsetShadows"] = "0";
    defines["shadowNormalOffset"] = "0.0";
```

Basically you need to get a getShadowsDisabledDefines() as well.

**Comment by Capostrophic** [comment]
Yeah, yeah, done that independently.

**Comment by akortunov** [comment]
Seems to work for me now, despite I'd prefer to avoid code duplication.

**Comment by Capostrophic** [comment]
If I were to avoid code duplication, then it would be necessary to initialize the entirety of the shadow manager (not even possible with the data available in the scope) that as I said won't get used for anything but recovering these specific define names.

**Comment by akortunov** [comment]
It is how we handle them now:

```
        Shader::ShaderManager::DefineMap shadowDefines = mShadowManager->getShadowDefines();
        Shader::ShaderManager::DefineMap globalDefines = mResourceSystem->getSceneManager()->getShaderManager().getGlobalDefines();

        for (auto itr = shadowDefines.begin(); itr != shadowDefines.end(); itr++)
            globalDefines[itr->first] = itr->second;

        globalDefines["forcePPL"] = Settings::Manager::getBool("force per pixel lighting", "Shaders") ? "1" : "0";
        globalDefines["clamp"] = Settings::Manager::getBool("clamp lighting", "Shaders") ? "1" : "0";

        // It is unnecessary to stop/start the viewer as no frames are being rendered yet.
        mResourceSystem->getSceneManager()->getShaderManager().setGlobalDefines(globalDefines);
```

**Comment by akortunov** [comment]
> If I were to avoid code duplication, then it would be necessary to initialize the entirety of the shadow manager (not even possible with the data available in the scope) that as I said won't get used for anything but recovering these specific define names.

Well, LGTM then.

**Comment by AnyOldName3** [comment]
I'd be happier making `getShadowsDisabledDefines()` static than having duplication. I can't really think of any reason why it would need to be non-static as even if we end up having two shadow systems, we're going to need the defines to disable all of them as they'll still be present in the shader source.

**Comment by akortunov** [comment]
@Capostrophic, will you try to implement a static method for defines?

**Comment by Capostrophic** [comment]
I am willing to do that. Where should it be put though? Should it be left in ShadowManager namespace?

**Comment by AnyOldName3** [comment]
I'd leave it as a class member, yeah.

**Comment by Capostrophic** [comment]
Does this look right?

**Comment by akortunov** [comment]
> Does this look right?

Seems to work.

**Comment by AnyOldName3** [comment]
LGTM

**Pull request merged**
