### PR TITLE
[Discussion, don't merge]  Toward Oblivion (cc9cii readers adaptating/extending)

### PR DESCRIPTION
**Pull request by mp3butcher**
My fail on Oblivion 
Just for reference (commits are quite hackish)

It gave me some understanding on the **enormous gap to fill in order to think of running oblivion in openmw** so can be interesting just fo that....

Main blockage is Script syntax

NB: I extended cc9cci works so there's more readers

Edit: I haven't merged with master since october2019 so there's conflicts...(if u want i removed them)

### CODE REVIEW

**Comment by akortunov** [comment]
What is the point of this PR?

**Comment by mp3butcher** [comment]
as i said it's for reference (as i read on discord that @Capostrophic  is on it)
I extended cc9cci works so there's more readers...just for it it worth a reference
I also hack a lot script stuff in a desperate attempt of loading Oblivion StartQuest...and other stuff that one trying to launch oblivion might be intereseted in review

**Comment by akortunov** [comment]
> as i said it's for reference

The purpose of **merge** request is to be **merged**. There is no point to keep unmergeable merge requests just in case that someone ever will need them to start an OpenOblivion project.

**Comment by mp3butcher** [comment]
> There is no point to keep unmergeable merge requests just in case that someone ever will need them to start an OpenOblivion project.

it's your call admins...but i though it'd have more readbility in a PR than a lost link on discord

**Comment by psi29a** [comment]
Cool!  Thought I have to agree with @akortunov, PRs are meant for potential merges. Instead of [not for merging], use the [needs discussion]?

I have no problem with a cleaned up esm4 reader entering into the code base in /extern so that it can be further worked on. So long as it doesn't touch OpenMW itself, for now. 

Long term goal is to not have to need a esm4 (or esm5, etc.) in /extern... but that our existing esm reader eventually handles all cases.

**Comment by akortunov** [comment]
It seems that this PR slowly starts to rot. Are there things that really should be discussed here?

**Comment by psi29a** [comment]
I'm okay with closing this, if someone wants to pick this up and clean it up, they are welcome.

@Capostrophic your thoughts? Is it salvageable ?

**Comment by psi29a** [comment]
What I did like was that tes4 was in extern which kept a few things 'clean'. It could later be refactored into openmw proper later.

**Comment by psi29a** [comment]
@mp3butcher you still around?

**Comment by akortunov** [comment]
> What I did like was that tes4 was in extern which kept a few things 'clean'.

You can not keep this PR in "extern" since it affects exising files from OpenMW codebase (World, MWScript, cellrefs, etc.).

**Comment by Capostrophic** [comment]
I won't mind if this is closed.

**Comment by psi29a** [comment]
> You can not keep this PR in "extern" since it affects exising files from OpenMW codebase (World, MWScript, cellrefs, etc.).

Correct, I don't like this either.

> Also "extern" is just a workaround to do not use git submodules, and I do not like an idea to turn this folder to the junk yard for unfinished code, which in theory can be partially salvagable in the distant future.

On this particular point though, you're making a mountain out of a molehill.  Avoiding the use of submodules is just one of many reasons for extern; not the only one. It is just supposed to be code that we shouldn't have to maintain... but never the less, it is in there.

As for the removal of things under extern;  I agree with that sentiment. I'm still waiting for a real release for recastnavigation so I can package it and push it up to Debian and others can also makes pacakges for them as well. oics will be a bit more difficult and we've been carrying that for years. 

Anyway, as I said before in a previous post. I'm okay with closing this.

**Comment by mp3butcher** [comment]
I state at the beginning that this pr was not for merging.
I openend it just for new readers  i wrote to be easily accessible...It's a shame to close it ..perhaps someone would be interested (for doing something else than merging with openmw)

**Pull request closed without merging**
