### PR TITLE
Proposal of omnidirectional lighting shading for particles

### PR DESCRIPTION
**Pull request by mp3butcher**
Force particles to face each light in shader path
It may be better that vanilla arbitrary normal but diverge from ffp replication
before
screenshot283
after
screenshot292 
https://streamable.com/n8y1xq

### CODE REVIEW

**Comment by psi29a** [comment]
Cool

**Comment by mp3butcher** [comment]
perhaps to bright mult by morrowind normals norm (0.5196) could decrease this brighness

**Comment by mp3butcher** [comment]
screenshot282 without scaling
screenshot292 with scaling

**Comment by mp3butcher** [comment]
i scaled

**Comment by AnyOldName3** [comment]
> perhaps to bright scaling by morrowind normals norm (0.5196) could decrease this brighness
> https://streamable.com/n8y1xq without scaling
> https://streamable.com/goid1v with scaling

In the APITrace I was looking at the other day, vanilla had the flag to normalise normals enabled, so I don't think you should need to do any scaling.

**Comment by mp3butcher** [comment]
> 
> 
> > perhaps to bright scaling by morrowind normals norm (0.5196) could decrease this brighness
> > https://streamable.com/n8y1xq without scaling
> > https://streamable.com/goid1v with scaling
> 
> In the APITrace I was looking at the other day, vanilla had the flag to normalise normals enabled, so I don't think you should need to do any scaling.

mmh strange...I haven't normalize the normal in my last merged pr, and results seams quite good.... 

it's more dubious as this scaling has been introdued after long testing by CMAugust, who thinked (and i agree) that particle systems were too bright without this downscaling.

**Comment by psi29a** [comment]
@mp3butcher any additional work inbound? 

Was there something else you needed from our side?

Closing this for now, but feel free to re-open here: https://gitlab.com/OpenMW/openmw

**Pull request closed without merging**
