### PR TITLE
try to get cmake and boost happy again

### PR DESCRIPTION
**Pull request by psi29a**
use latest cmake as 3.11 has issues with boost 1.71

### CODE REVIEW

**Comment by AnyOldName3** [comment]
> use latest boost as 3.11 has issues with boost 1.71

to

> use latest *CMake* as 3.11 has issues with boost 1.71

**Comment by psi29a** [comment]
```
Make Warning at /usr/local/lib/cmake/boost_system-1.71.0/libboost_system-variant-shared.cmake:59 (message):
  Target Boost::system already has an imported location
  '/usr/local/lib/libboost_system-mt.dylib', which will be overwritten with
  '/usr/local/lib/libboost_system.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_system-1.71.0/boost_system-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:317 (find_package)
CMake Warning at /usr/local/lib/cmake/boost_filesystem-1.71.0/libboost_filesystem-variant-shared.cmake:59 (message):
  Target Boost::filesystem already has an imported location
  '/usr/local/lib/libboost_filesystem-mt.dylib', which will be overwritten
  with '/usr/local/lib/libboost_filesystem.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_filesystem-1.71.0/boost_filesystem-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:317 (find_package)
CMake Warning at /usr/local/lib/cmake/boost_program_options-1.71.0/libboost_program_options-variant-shared.cmake:59 (message):
  Target Boost::program_options already has an imported location
  '/usr/local/lib/libboost_program_options-mt.dylib', which will be
  overwritten with '/usr/local/lib/libboost_program_options.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_program_options-1.71.0/boost_program_options-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:317 (find_package)
CMake Warning at /usr/local/lib/cmake/boost_iostreams-1.71.0/libboost_iostreams-variant-shared.cmake:59 (message):
  Target Boost::iostreams already has an imported location
  '/usr/local/lib/libboost_iostreams-mt.dylib', which will be overwritten
  with '/usr/local/lib/libboost_iostreams.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_iostreams-1.71.0/boost_iostreams-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:317 (find_package)
```

This is the problem...

**Comment by akortunov** [comment]
https://gitlab.kitware.com/cmake/cmake/issues/19658

**Comment by akortunov** [comment]
I upgraded boost to 1.71 and encountered the same issue. With CMake 3.15.5 the issue disappeared.

**Comment by akortunov** [comment]
May be related to your linking issues: https://forum.freecadweb.org/viewtopic.php?f=4&t=39301

**Comment by akortunov** [comment]
https://github.com/OpenMW/openmw/pull/2614

Basically, it works, but I encountered this issue:

```
CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/BundleUtilities.cmake:1002 (message):
  error: fixup_bundle: not a valid bundle
Call Stack (most recent call first):
  /Users/travis/build/OpenMW/openmw/build/cmake_install.cmake:154 (fixup_bundle)
CPack Error: Error when generating package: OpenMW
make: *** [package] Error 1
The command "if [ "${COVERITY_SCAN_BRANCH}" != 1 ] && [ "${TRAVIS_OS_NAME}" = "osx" ]; then make package; fi" exited with 2.
0.40s$ if [ "${COVERITY_SCAN_BRANCH}" != 1 ] && [ "${TRAVIS_OS_NAME}" = "osx" ]; then ../CI/check_package.osx.sh; fi
hdiutil: attach failed - No such file or directory
```

But I am pretty sure that I saw this issue earlier...

**Comment by akortunov** [comment]
@nikolaykasyanov, can you take a look at MacOS CI, please?

**Comment by akortunov** [comment]
> #2614

I got a confirmation from Arch users - this PR fixes build issues for them as well.
The only thing left is to investigate MacOS X packaging.

**Comment by nikolaykasyanov** [comment]
@akortunov I'll have a look.

**Comment by nikolaykasyanov** [comment]
After a bunch of hiccups this PR is building but I persume we'd like to fix the current master (that includes #2614), right? cc @akortunov @psi29a

**Comment by akortunov** [comment]
> After a bunch of hiccups this PR is building but I presume we'd like to fix the current master

Yes, master has issues with the `fixup_bundle` command. The build process itself now works (including unit tests).

**Comment by akortunov** [comment]
#2617 addresses issue with packaging, so this PR is not needed now.

**Pull request closed without merging**
