### PR TITLE
Bug #4077 - Enchanted Items recharge on ground.

### PR DESCRIPTION
**Pull request by Langerz82**
Hopefull this pull-request is correct. It's my first pull commit so go easy on me if I've made any mistakes. thank-you. ^_^

As discussed in the bug report, this only adds items to be recharged when they've been used and only recharge once they are in the active cell. They attach a timestamp upon used so the elapsed time is taken into effect. SAVE/LOAD should work as intended.

https://bugs.openmw.org/issues/4077?issue_count=304&issue_position=8&next_issue_id=4074&prev_issue_id=4081

### CODE REVIEW

**Comment by akortunov** [comment]
Why 15 commits? What's the problem to create a new clean branch from master and insert here only changes, relevant to 4077?
For now you have a pieces of your other work here, and git history is a total mess.
Also your build failed due to some missing headers.

**Comment by kcat** [comment]
To reset a local branch to a clean OpenMW state, run ```git reset --hard [remote-name]/master```, where [remote-name] is the name you have for the remote OpenMW repo (not your fork of the repo). If you don't have a remote set for the main OpenMW repo, you can do it with:
```git remote add omw-main https://github.com/OpenMW/openmw.git
git fetch omw-main
git reset --hard omw-main/master```
... where ```omw-main``` is the remote name you want for OpenMW's main repo (it can be just about anything).

**Comment by Langerz82** [comment]
I have no idea why it wants to merge 15 commits as the files affected is correct for the patch albeit some missing headers. ill need to fix it I guess. :S

**Comment by akortunov** [comment]
> I have no idea why it wants to merge 15 commits 

Because you have 15 addidional commits in your branch history. These commits are not present in master branch.

**Comment by Langerz82** [comment]
@kcat  I got a new repo I made and just applied the patch added the missing header and made minor changes to CI and Cmake files which I needed to test the build. How do I create a pull request for it?

https://github.com/Langerz82/openmw-main

**Pull request closed without merging**
