### PR TITLE
Fix windows builds

### PR DESCRIPTION
**Pull request by ace13**
Can't instantiate a container (at least with MSVC) without knowing the exact size of the object being stored, forward-declares only work with pointers.
I couldn't see a simple way to remove the forward declare, so pointers and memory management it is.

### CODE REVIEW

**Comment by kcat** [comment]
What's the actual error MSVC is giving?

**Comment by ace13** [comment]
The full error text is;
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\deque(947): error C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwsound\loudness.cpp)
          apps\openmw\mwsound\soundmanagerimp.hpp(31) : see declaration of 'MWSound::Sound_Buffer'
          apps\openmw\mwsound\soundmanagerimp.hpp(63) : see reference to class template instantiation 'std::deque<MWSound::Sound_Buffer,std::allocator<_Ty>>' being compiled
          with
          [
              _Ty=MWSound::Sound_Buffer
          ]
          apps\openmw\mwsound\soundmanagerimp.hpp(31) : see declaration of 'MWSound::Sound_Buffer'
          apps\openmw\mwsound\soundmanagerimp.hpp(31) : see declaration of 'MWSound::Sound_Buffer'
          apps\openmw\mwsound\soundmanagerimp.hpp(31) : see declaration of 'MWSound::Sound_Buffer'
```

And the full list of C2027 errors are;
```
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwsound\soundmanagerimp.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwsound\soundmanagerimp.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwsound\loudness.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwsound\loudness.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwsound\openal_output.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwsound\movieaudiofactory.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwsound\openal_output.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwsound\movieaudiofactory.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwworld\weather.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwworld\weather.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwworld\projectilemanager.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\mwworld\projectilemanager.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\engine.cpp)
C2027: use of undefined type 'MWSound::Sound_Buffer' (apps\openmw\engine.cpp)
```

**Comment by kcat** [comment]
I think I'd prefer it if the deque itself was made an auto pointer, then. i.e. ```std::auto_ptr<std:;deque<Sound_Buffer> > mSoundBuffers;```, then ```, mSoundBuffers(new std::deque<Sound_Buffer>)```, and such.

**Comment by ace13** [comment]
Like this then?

**Pull request merged**
