### PR TITLE
Raise the required bullet version to 2.83

### PR DESCRIPTION
**Pull request by scrawl**
psi29a is going to like this one. More stuff to backport to our PPA.

Bullet 2.82 appears to have a bug that causes the player to be able to phase through certain objects (bug #1587).

### CODE REVIEW

**Comment by zinnschlag** [comment]
Not overly happy either. Will wait with the merge until we get the all clear from @psi29a

**Comment by psi29a** [comment]
Die in a fire... :'(

The good news is that 2.83 is in stretch/sid and should also be in Ubuntu Xenial, so it isn't as bad as OSG.

**Comment by psi29a** [comment]
Good news: https://launchpad.net/~openmw/+archive/ubuntu/openmw/+packages
OSG 3.4 is available for all i386 and x86_64 across our 3 currently supported Ubuntu Releases.
Bullet 2.83 had to be backported to Trusty, but is also up.

@scrawl Please do an empty commit to trigger a new build to verify that Travis is happy.

**Comment by scrawl** [comment]
Bullet is ok, but there was this:

<pre>
In file included from /usr/include/osgQt/GraphicsWindowQt:21:0,

                 from /home/travis/build/OpenMW/openmw/apps/opencs/view/render/scenewidget.cpp:9:

/usr/include/osgQt/Version:8:2: error: #error "Qt version mismatch detected! Make sure to compile applications using osgQt with the same major Qt version that osgQt has been compiled against."

 #error "Qt version mismatch detected! Make sure to compile applications using osgQt with the same major Qt version that osgQt has been compiled against."
</pre>

**Comment by psi29a** [comment]
For Qt, I'm using what is default. I'm guessing that for Debian, the default was Qt5. We should probably go that way as well with Launcher and CS.

**Comment by scrawl** [comment]
Last I checked, Qt5 had ugly font rendering on Linux and there were some other regressions. osgQt can't do threaded rendering when using Qt5.

The OpenMW/osg fork uses Qt4 by default.

**Comment by scrawl** [comment]
Ultimately I plan on doing a manual qt integration in favor of osgQt, so that this dependency hell goes away. Not sure when I'll get around to that though.

**Comment by zinnschlag** [comment]
I consider Qt4 our main platform for now (its certainly what I am using). As mentioned by scrawl there are still issues with Qt5 and I don't see the benefits of a move to Qt5. It doesn't offer a lot of improvements for us and seems overall not quite mature enough.

**Comment by psi29a** [comment]
:'(  It will take awhile to get these packages rebuilt then, need to find the right options.

**Comment by scrawl** [comment]
Not needed anymore, I've added osgQt to our repository in commit 647a5e091f4298ed390e511d7ce9fbfa64e0aa95 , this means it is built independently of OSG so it doesn't matter what version of Qt OSG was built with.

**Comment by psi29a** [comment]
Thank you @scrawl

**Comment by corristo** [comment]
@scrawl would Qt5 compatibility be kept?

**Comment by scrawl** [comment]
Yes, when building OpenMW we still have the choice of Qt4 or Qt5.

**Pull request merged**
