### PR TITLE
Break the windows build

### PR DESCRIPTION
**Pull request by scrawl**
Testing appveyor integration.

### CODE REVIEW

**Comment by ace13** [comment]
Seems to build https://ci.appveyor.com/project/ace13/openmw/build/0.38.0-c45775b

Wonder why it's not calling back with the build info

**Comment by scrawl** [comment]
> Wonder why it's not calling back with the build info

Seems to be working for other projects. https://github.com/yegor256/takes/pull/551

**Comment by ace13** [comment]
There was a report on a similar problem regarding authorization, so reauthorized AppVeyor to my account to see if that'd help

**Comment by ace13** [comment]
Ah right, this could explain the issue, pretty obvious issue too I guess...

The issue;

> Hi there,
> 
> We recently added a repo called Localization to our org at https://github.com/aspnet/Localization/ . > I've been trying to enable AppVeyor to show the CI status in the PR but it doesn't show up. We also have Travis enabled and that one shows up fine. I do have AppVeyor enabled though I had to manually create the web hook, but I can see AppVeyor running the builds and all. It's just not showing the CI status in the PR. For all our other repos this is working fine.
> 
> Is there anything special I need to do to enable the CI status to show up in the PR?

And the response;

> You said there was no webhook automatically added to that repository and then you added it manually. This is the reason why there is no status set on Pull Requests - GitHub user currently authorized in AppVeyor doesn't have "write" (and "admin" for placing webhook) rights on that repository. You can see (and re-authorize) GitHub user linked to AppVeyor account on this page: https://ci.appveyor.com/account

**Comment by scrawl** [comment]
Not sure if I follow, what should we do now? Should I open a new test PR?

**Comment by ace13** [comment]
Well, I don't have write access to the access so I guess AppVeyor can't set build statuses through my account.
Perhaps setting up a openmw organization account on AppVeyor, or letting someone else with write access host the AppVeyor project could work?

**Comment by scrawl** [comment]
I've signed in to appveyor with my github account and created an openmw repository, this added a new webhook to github automatically. Let's see if it works now.

**Comment by ace13** [comment]
You should probably update the status badge image and link then, also I think there's a g in the link to travis

**Comment by ace13** [comment]
I guess - consider the build time of the AppVeyor builds - that a good idea would be to remove the building on pushes, just disabling that part of the webhook should do.

**Comment by scrawl** [comment]
Will do.

**Pull request closed without merging**
