### PR TITLE
Bug #2281 NPCs don't scream when they die

### PR DESCRIPTION
**Pull request by jeffreyhaines**

### CODE REVIEW

**Comment by jeffreyhaines** [comment]
Is this good? I see I can get the PlayType from the code within. For example we know left right and land. Then I can put back the parsing code in Character.cpp and pass with soungen, volume and pitch.

**Comment by scrawl** [comment]
Seems like we are on the wrong track. Inspecting the death animations in base_anim.nif closer, some of them do include "moan" "roar" or "scream" keys, but not all do. Also, if you kill an NPC in vanilla MW with the console, they immediately scream even before you close the console, not during animation playback.

Furthermore, it doesn't seem like say(ptr, "hit"); is the correct scream either. Test with Ranis Athrys in Balmora, Guild of Mages. The screams generally sound different in MW, also, in OpenMW you'll get voice lines like "Stupid!" as well that are not screams.

More research needed, I guess.

**Comment by scrawl** [comment]
> Furthermore, it doesn't seem like say(ptr, "hit"); is the correct scream either. Test with Ranis Athrys in Balmora, Guild of Mages. The screams generally sound different in MW, also, in OpenMW you'll get voice lines like "Stupid!" as well that are not screams.

Ignore that. My vanilla install apparently has german voice files, my OpenMW install english voices. That's why it seemed different to me.

**Comment by scrawl** [comment]
With that said, looks like your first PR was correct all along. Sorry for the waste of time.

**Comment by jeffreyhaines** [comment]
I'm doing some more refactoring. I think its better to have the handleSoundGen with passed soundgen string, float volume and pitch.

**Pull request closed without merging**
