### PR TITLE
Menu improvements

### PR DESCRIPTION
**Pull request by akortunov**
1. Load game menu now have a confirmation dialog.
2. Added dynamic resize of confirmation dialogs
3. Disabled transparency for save/load menu, confirmation dialog widget (as in vanilla).
4. Count window: layout changes, disabled transparency (this widget is nearly unusable with transparency).

### CODE REVIEW

**Comment by scrawl** [comment]
I don't like the count dialog changes. If we're going to change the height of the horizontal scrollbars, we should change the others to match (e.g. in the rest dialog). Though, I prefer the larger scrollbar as its easier to grab. I also don't like that the item text is no longer vertically aligned with the count text.

The other changes are fine.

**Comment by akortunov** [comment]
I can rollback count dialog changes (except disabled background transparency). Should I do it?

**Comment by akortunov** [comment]
Or I can rollback only two mentioned changes.

> Though, I prefer the larger scrollbar as its easier to grab.

Ok, I will increase scrollbar height. 

> item text is no longer vertically aligned with the count text

Do you mean two-pixel difference in vertical offset between TextBox and NumericEditBox?

**Comment by scrawl** [comment]
> Do you mean two-pixel difference in vertical offset between TextBox and NumericEditBox?

I meant the difference between the vertical position of the texts.

> I can rollback count dialog changes ... Or I can rollback only two mentioned changes.

Either way is fine with me.

**Comment by akortunov** [comment]
Ok, scrollbar height is 18px again.
The item text and the count text now have an equal vertival offset again.

**Comment by scrawl** [comment]
Count dialog Ok/Cancel are no longer centered.

**Comment by akortunov** [comment]
> Ok/Cancel are no longer centered.

Do you mean that they are centered, but have different size?

**Comment by scrawl** [comment]
img

**Comment by akortunov** [comment]
Got it, I will try to investigate it.

**Comment by akortunov** [comment]
Can you test this content of openmw_count_window.layout?

```
<?xml version="1.0" encoding="UTF-8"?>
<MyGUI type="Layout" version="3.2.0">
    <Widget type="Window" skin="MW_DialogNoTransp" position="0 0 600 128" align="Center" layer="Windows" name="_Main">
        <Property key="Visible" value="false"/>
        <Widget type="TextBox" skin="SandText" position="0 4 596 24" align="Left Top HStretch" name="LabelText">
            <Property key="TextAlign" value="Center"/>
        </Widget>
        <Widget type="TextBox" skin="SandText" position="12 36 521 24" align="Left Top HStretch" name="ItemText">
            <Property key="TextAlign" value="Left"/>
        </Widget>
        <Widget type="NumericEditBox" skin="MW_TextEdit" position="535 36 50 24" align="Right Top" name="ItemEdit">
            <Property key="TextAlign" value="Center"/>
        </Widget>
        <Widget type="MWScrollBar" skin="MW_HScroll" position="7 67 578 18" align="Left Top HStretch" name="CountSlider">
            <Property key="MoveToClick" value="true"/>
            <Property key="Page" value="1"/>
            <Property key="WheelPage" value="1"/>
        </Widget>
        <Widget type="Widget" skin="" position="0 91 596 24" align="Left Bottom HStretch">
            <Property key="Stretch" value="True"/>
            <Widget type="Widget" skin="" position="0 0 140 24" align="Center Bottom">
                <Widget type="AutoSizedButton" skin="MW_Button" position="0 0 53 24" align="Center Top" name="OkButton">
                    <Property key="Caption" value="#{sOk}"/>
                </Widget>
                <Widget type="AutoSizedButton" skin="MW_Button" position="54 0 86 24" align="Center Top" name="CancelButton">
                    <Property key="Caption" value="#{sCancel}"/>
                </Widget>
            </Widget>
        </Widget>
    </Widget>
    <CodeGeneratorSettings/>
</MyGUI>
```

**Pull request merged**
