### PR TITLE
Don't issue errors for unused scripting arguments

### PR DESCRIPTION
**Pull request by Allofich**
For https://bugs.openmw.org/issues/3762.

### CODE REVIEW

**Comment by Allofich** [comment]
Note that I haven't actually been able to test the mod mentioned in the bug report. I've been trying to download it but can't seem to get the right files. But the script command in the bug report and the one suggested in the comments "tgm 1" work as expected.

**Comment by Allofich** [comment]
Don't merge, this causes problems with script parsing.

**Comment by Allofich** [comment]
It may take me a while to figure this out. A script in Bloodmoon, ColonySeler, causes problems. It has an incorrectly formed PositionCell command, with the cell name as the first argument followed by the coordinates, but the coordinates are supposed to come first. I don't think this command does anything to the NPC it's on in the original engine, and if used on the player it puts you in the 0 coordinate outside cell. It seems like if a string is passed in an integer parameter the original engine interprets it as 0.

I'll return to this later. Any advice is welcome.

**Comment by akortunov** [comment]
Hmm... It seems Morrowind handles command arguments similar to Bash shell. It is just forms an array of arguments (string values) and passes them to command handler.

Handler itself takes care about validation, missing arguments, type casting etc. 
There are no errors when too many arguments - they are just unused elemenths of array.
There are no errors when argument has wrong type - they are all strings. When handler cast string to another type (integer, for example), it can just take default value.

When I typed

`player->additem "Gold_100" aaa`

in Morrowind console, I just got a script error - 'count "0" is not allowed for "Gold_100"'.

**Comment by scrawl** [comment]
> It may take me a while to figure this out. A script in Bloodmoon, ColonySeler, causes problems.

We have a very specific workaround for that [here](0737d6cb72fd9ac15109e50acfe4ca8960877d30).

**Comment by Allofich** [comment]
The link doesn't work. Based on the URL it looks like it was linking to https://github.com/OpenMW/openmw/commit/0737d6cb72fd9ac15109e50acfe4ca8960877d30, but that doesn't seem to be related to this.

**Comment by Allofich** [comment]
I think I found the workaround you are talking about, in lineparser.cpp 

                        // workaround for broken positioncell instructions.
                        /// \todo add option to disable this
                        if (Misc::StringUtils::lowerCase (loc.mLiteral)=="positioncell")
                            errorDowngrade.reset (new ErrorDowngrade (getErrorHandler()));

and

                        // Ignore argument exceptions for positioncell.
                        /// \todo add option to disable this
                        if (Misc::StringUtils::lowerCase (loc.mLiteral)=="positioncell")
                        {
                            SkipParser skip (getErrorHandler(), getContext());
                            scanner.scan (skip);
                            return false;
                        }

**Comment by Allofich** [comment]
The script parsing is too complicated for me to understand any time soon, so I'm going to close this and remove myself from the issue on the bug tracker. There's another scripting issue that I saw in the forums and will open a bug report for.

**Pull request closed without merging**
