### PR TITLE
Extend OSG stats

### PR DESCRIPTION
**Pull request by elsid**
Add report for:
* Current frame number (it's not showed by default, probably there is other way how to do this properly).
* Number of mechanics actors
* Number of mechanics objects
* Number of physics actors
* Number of physics objects
* Number of physics heigh fields

Allows to see and analyze dependency between a number of entities and frame time.

### CODE REVIEW

**Comment by AnyOldName3** [comment]
Within my limited understanding of the OSG stats system, this looks reasonable. You do seem to have removed some empty strings, though. I'm guessing they were to add empty lines between sections, so if that's what they were doing, it's probably best to keep them.

**Comment by elsid** [comment]
These empty lines just take place on a screen making the required window size bigger. Visually it helps to separate things by categories but I'd better keep more screen clean of debug info.

**Comment by AnyOldName3** [comment]
I'm not sure I agree with that, so I guess it would help to have a before and after screenshot so we can do a comparison.

By the way, can you figure out how to make it show the number of dynamic drawables and statesets? I thought we had that information, but apparently we don't. Bonus points if it's red when non-zero. I think this would help with what Foal's doing.

**Comment by elsid** [comment]
Before:
before
After:
after

**Comment by AnyOldName3** [comment]
I definitely prefer the line breaks in those two screenshots, but I meant a before and after for just the line break removal, not adding all the settings. The line breaks have an unfair advantage as there's less information to make it huge.

Also, you might want to check if your build is working properly. That's the OSG default font, and our stats are supposed to use DejaVu Sans Mono.

**Comment by elsid** [comment]
Put empty lines back:
screenshot002

**Comment by AnyOldName3** [comment]
Yeah, I like the empty lines.

**Comment by elsid** [comment]
[Wiki](https://wiki.openmw.org/index.php?title=Development_Environment_Setup#OSG_plugins) is missing mention of `BUILD_OSG_PLUGIN_FREETYPE=1` that's why I had default font. I didn't know this is required.

**Comment by akortunov** [comment]
Added info to Wiki.

**Comment by akortunov** [comment]
Did you check if stats window works properly with low resolution (such as 600x800)?

**Comment by AnyOldName3** [comment]
800x600 is *particularly* low, so I'm not sure it's worth supporting. 1366x768 is still a pretty common screen size in laptops, though, so it's reasonably likely we'll need to know what it looks like there. Someone also might try running OpenMW on an HD Ready TV, so 1280x720 might be worth testing, too.

Regarding the wiki missing Freetype, I think it's because it's technically optional. We have graceful fallbacks for when it's not present

**Comment by elsid** [comment]
Seems to be working:
640x480:
640x480
800x600:
800x600
1024x768:
1024x768

**Comment by akortunov** [comment]
Perosonally I do not like that displayed stats lose their vertical alignment and start to overlap with profiler (for any resolution excepts of 1920x1080 for me). Is it possible to split them to two tabs, or do something else to avoid it?

**Comment by akortunov** [comment]
> Regarding the wiki missing Freetype, I think it's because it's technically optional.

We started do use DejaVuLGCSansMono.ttf in the profiler not a very long time ago. Prior to that we did not need to build a FreeType plugin for OSG, and we just forgot to update Wiki.

**Comment by AnyOldName3** [comment]
Don't we need it for TrueType UI fonts, too?

**Comment by akortunov** [comment]
No, they are handled by MyGUI, not by OSG.

**Comment by psi29a** [comment]
Thanks @elsid

**Pull request merged**
