### PR TITLE
Only disarm traps with keys when the door/container is locked (bug #5370)

### PR DESCRIPTION
**Pull request by Capostrophic**
[Bug report](https://gitlab.com/OpenMW/openmw/-/issues/5370).

Removes the undesirable "disarm unlocked doors" behavior for keys.
Containers and doors behave the same way here in Morrowind in my testing.

The behavior was added in PR #995, but somehow it doesn't seem like it's present in the vanilla game (neither in my testing nor geist's). Maybe Allofich meant something different when he said "lock level 0" like locks that were locked with `Lock 0`?..

### CODE REVIEW

**Comment by Allofich** [comment]
> Maybe Allofich meant something different when he said "lock level 0" like locks that were locked with Lock 0?

It was a long time ago but yes, I think I remember testing this by using "Lock 0" with the console, rather than "unlocking a door with other means and leaving the trap, then activating it (with the key in your inventory)" like the bug reporter said.

**Comment by Capostrophic** [comment]
So yeah, `lock 0` doesn't behave the same way as `unlock` in vanilla, it sets the lock level to the largest positive value (which isn't displayed on the tooltip). That's the way it works in OpenMW as well (since 2018).

**Comment by akortunov** [comment]
But what if the container was initially only trapped, but had an assigned key? I wonder how Morrowind handles this case.

**Comment by Capostrophic** [comment]
> I wonder how Morrowind handles this case.

Oddly enough Morrowind behaves as if there's no trap at all and the door is simply opened as a normal unlocked door that wasn't trapped.

**Comment by Capostrophic** [comment]
The latest change implements the "ignore trap" behavior noted above. It's one thing Morrowind does consistently. There's most likely something fishy about 0 lock level locks with keys assigned otherwise (as akortunov claims it's essential to get the unbreakable lock functionality in Arktwend to work) because the one situation I tested had the lock unlocked but it's not directly related to the issue at hand, so I didn't change it.

There's a feature in MCP that allows the scripter to check the cell reference's lock level instead of an actor's level using GetLevel that may help figure out the correct thing to do there, but that's a matter for another time.

**Comment by Capostrophic** [comment]
Any objections?

**Comment by psi29a** [comment]
I do not have any.

**Pull request merged**
