### PR TITLE
[WIP] Try AV with Ubuntus

### PR DESCRIPTION
**Pull request by psi29a**
Just checking what we can do with AV.

### CODE REVIEW

**Comment by akortunov** [comment]
Is there a reason to do it? IIRC, AppVeyor executes jobs one-by-one, so 4 tasks will spend near 2 hours of time.

**Comment by psi29a** [comment]
A few reasons:
1) to see if it possible
2) we get xenial and bionic
3) we get artifacts and hosting for them
4) we can set it up for nightlies only

**Comment by akortunov** [comment]
Any progress here?

**Comment by psi29a** [comment]
Still WIP but sadly AV is still serial and not parallel. Which is all kinds of sad. I'm going to close this and if I need the code I can always comes back to it.

**Pull request closed without merging**
