### PR TITLE
Explicitly instantiate unnecessarily complex templates

### PR DESCRIPTION
**Pull request by ace13**
As part if getting a working AppVeyor build of OpenMW, I'm working on getting the build time down. Right now the AppVeyor builds time out after 40 minuters.

One large compile time improvement can be had from reducing the number of headers included, so that's what I'm working towards by moving templates to explicit instantiations.

I'm mainly opening this PR for Travis right now, but should be mergable soon.

### CODE REVIEW

**Comment by scrawl** [comment]
I'm all for reduced build times. I had to disable all targets except for OpenMW on coverity-scan, else the build would time out as well.

Change looks good to me.

**Comment by ace13** [comment]
I'm currently cleaning up and redoing MWWorld::Store as well, since that's one of the heaviest headers in OpenMW and it's still only a fixed number of instantiations.

On that note, will we ever have any unsigned int ESM::StatState-s? Or are int and float the only ones we want to use on there?

**Comment by zinnschlag** [comment]
> On that note, will we ever have any unsigned int ESM::StatState-s? Or are int and float the only ones we want to use on there?

I don't see why we would ever use an unsigned int ESM::StatState. Or a MWMechanics::Stat, while we are at it (that one is a good candidate for the same procedure you did to ESM::StatState).

**Comment by ace13** [comment]
Right, MWMechanics::Stat is now explicity instantiated, still working on MWWorld::Store which is a big one.

**Comment by ace13** [comment]
Right, that should be MWWorld::Store too, I'd want to wait until I can test all the changes myself before considering merging it though. Don't have the Morrowind assets on my laptop, so I can only write the code, not test it.

**Comment by maqifrnswa** [comment]
> I'd love to sit down and run include-what-you-use on OpenMW too, to clean up all of the includes we have.

I spent a good amount of time doing that a couple months ago, there were a bunch of bugs in IWYU that prevented it from working - but I submitted patches to clang and I think it's much further along. One outstanding issue:
https://code.google.com/p/include-what-you-use/issues/detail?id=175

And you may have to use custom mappings (e.g.):
https://code.google.com/p/include-what-you-use/issues/detail?id=70

**Comment by scrawl** [comment]
> I'd want to wait until I can test all the changes myself before considering merging it though. Don't have the Morrowind assets on my laptop, so I can only write the code, not test it.

Just tested running this branch, didn't notice any issues.

I compared build times with master (3 builds each, averaged times). The result is impressive, a 23% improvement. Nicely done! I will have to try and re-enable some of Coverity-CI build targets when this is merged.

<pre>
ace13:explicit-instantiation
741s (12m 21s)

OpenMW:master
913s (15m 13s)
</pre>

**Pull request merged**
