### PR TITLE
NPC drowning

### PR DESCRIPTION
**Pull request by gugus**
fixes https://bugs.openmw.org/issues/1374

### CODE REVIEW

**Comment by Svetomech** [comment]
Great way to name a commit.

**Comment by gugus** [comment]
yeah sorry I got confused by the github gui interface (why am I even using it? ^^)

**Comment by Capostrophic** [comment]
For future: you shouldn't use tabs. Read [code formatting conventions.](https://wiki.openmw.org/index.php?title=Code_Formatting_Conventions)

**Comment by gugus** [comment]
Argh I forgot to reset my editor with tabs, thanks, I'll correct that

**Comment by Allofich** [comment]
I just tested this code out, and I think maybe you aren't making the NPC go up until too late. It's only safe to wait that long if you are near the surface of the water. I tested in the original game, and NPCs seem to go up for breath at about the time that the breath meter is halfway down. This makes sense, too, since it would usually keep an NPC from diving down further than they can safely go.

You can rename that earlier commit by doing the following from a git bash prompt
1. type `git rebase -i ~2`
2. next to the earlier commit change "pick" to "r" or "reword" (in my case, I have to press insert to start editing text, then esc to exit edit mode, then type :wq to save changes)
3. it should start rebasing and automatically bring up the commit message for you to change. After you do that you are finished.

**Comment by jeffreyhaines** [comment]
@gugus just wondering how're you doing on this issue and if you intend to continue working on it. Appreciate your response.

**Comment by akortunov** [comment]
> I tested in the original game, and NPCs seem to go up for breath at about the time that the breath meter is halfway down

We can achive this by modifying preventDrowning function:

    bool MWMechanics::AiPackage::preventDrowning(const MWWorld::Ptr& actor)
    {
        static const float fHoldBreathTime = MWBase::Environment::get().getWorld()->getStore().get<ESM::GameSetting>().find("fHoldBreathTime")->getFloat();
    
        const MWWorld::Class& actorClass = actor.getClass();
        if (actorClass.isNpc())
        {
            if (actorClass.getNpcStats(actor).getTimeToStartDrowning() < fHoldBreathTime / 2)
            {
                //go up
                //another option: create a new AiTravel package with coordinates at water level. 
                //or maybe cast a spell if available
                actor.getClass().getMovementSettings(actor).mPosition[1] = 1;
                smoothTurn(actor, -180, 0);
                return true;
            }
        }
        return false;
    } 

Also I found a bug. NPC will drown if a destination point is blocked (e.g. by another NPC) instead of reaching surface in another point.

During the test three guards from Seyda Neen used the same destination point to reach the surface - above PC. One of guards drowned, because destination point was blocked by two other guards (who tried to swim down, but their paths were blocked by the first guard).

**Comment by Allofich** [comment]
> Also I found a bug. NPC will drown if a destination point is blocked (e.g. by another NPC) instead of reaching surface in another point.

A bug in this PR or in the original engine?

I think in the original engine NPCs just move upward with no other consideration when they need air. When I was testing the behavior I put an NPC below a boat and it just floated up against the boat bottom when it needed air, got stuck there and drowned.

**Comment by akortunov** [comment]
> A bug in this PR or in the original engine?

In this PR.

**Comment by akortunov** [comment]
Are there any problems with this PR except of rebasing and preventDrowning() go up time? Maybe we can create another PR since author is inactive over half of year?

**Pull request closed without merging**
