### PR TITLE
Store raw data about fog of war instead of RGBA images

### PR DESCRIPTION
**Pull request by akortunov**
Re-incarnation of #2453.

### CODE REVIEW

**Comment by akortunov** [comment]
Just for reference - PNG with its palettes gives a better data compression (18.5% save instead of 15% with raw write). Not sure about performance, though.

**Comment by Julix91** [comment]
The "on hold" going away - does that mean work on 0.47 is starting?

Managed to confirm 0.46 is in RC:

> [...] branched openmw-46... let the RC phase begin.

https://forum.openmw.org/viewtopic.php?f=20&t=5548&start=80#p67038
https://github.com/OpenMW/openmw/tree/openmw-46

In an old issue I see a reference to 0.47
https://github.com/OpenMW/openmw/pull/2453#issuecomment-547917228
but clicking on the link https://forum.openmw.org/viewtopic.php?f=42&t=6373 it says I don't have permission to view.

Is there a thread about scope etc for 0.47 that's publicly (normal reigstered user) visible?

**Comment by Capostrophic** [comment]
There's no real scope for 0.47 in general.

**Comment by psi29a** [comment]
Went with PNG variant, thanks @akortunov

**Pull request closed without merging**
