### PR TITLE
[Testing needed] Always run startup script once at engine start (bug #4877)

### PR DESCRIPTION
**Pull request by elsid**

### CODE REVIEW

**Comment by Capostrophic** [comment]
Won't this cause Bad Things™ to happen if the script gets ran while inside main menu? It probably shouldn't be ran when the game state is not Running. But then side effects of the script won't be carried over into the first loaded save.

**Comment by elsid** [comment]
Yeah, it was bad idea to this in that way. Game just crashes in main menu.

**Comment by psi29a** [comment]
@Capostrophic @akortunov you guys ok with this?

**Comment by akortunov** [comment]
LGTM, if it really works (can not test it right now).

**Comment by psi29a** [comment]
Waiting for more testing... (confirmation)

**Comment by Capostrophic** [comment]
Appears to be fine. Though it obviously only works if the main menu is bypassed by the respective command line argument or by a saved game file command line argument.

**Pull request merged**
