### PR TITLE
Investigate where MacOS on Travis is failing

### PR DESCRIPTION
**Pull request by AnyOldName3**
I think I have to make a PR for CI to happen as I couldn't find a link to the pipeline otherwise.

### CODE REVIEW

**Comment by psi29a** [comment]
```
==> Installing gdal dependency: python@3.9
==> Pouring python@3.9-3.9.1_1.catalina.bottle.tar.gz
Unlinking /usr/local/Cellar/python@3.8/3.8.6... 25 symlinks removed
**Error: The `brew link` step did not complete successfully**
The formula built, but is not symlinked into /usr/local
Could not symlink bin/easy_install-3.9
Target /usr/local/bin/easy_install-3.9
is a symlink belonging to python@3.9. You can unlink it:
  brew unlink python@3.9
To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9
To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9
Possible conflicting files are:
/usr/local/bin/easy_install-3.9 -> /usr/local/Cellar/python@3.9/3.9.0/bin/easy_install-3.9
/usr/local/bin/pip3.9 -> /usr/local/Cellar/python@3.9/3.9.0/bin/pip3.9
==> /usr/local/Cellar/python@3.9/3.9.1_1/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.1_1/bin/pip3 install -v --global-option=--no-user-cfg --install-option=--force --install-option=--single-version-externally-managed --install-option=--record=installed.txt --upgrade --target=/usr/local/lib/python3.9/site-packages /usr/local/Cellar/python@3.9/3.9.1_1/libexec/setuptools /usr/local/Cellar/python@3.9/3.9.1_1/libexec/pip /usr/local/Cellar/python@3.9/3.9.1_1/libexec/wheel
==> Caveats
Python has been installed as
  /usr/local/bin/python3
```

**Comment by psi29a** [comment]
The conflict is between python3.8 and python3.9

**Comment by AnyOldName3** [comment]
Buried in the middle of a thousand lines of a command's output seems like the *perfect* place to put an error message. Well done, brew.

Anyhow, I'm not completely sure it's 3.8 and 3.9 conflicting. It claims to be removing the 3.8 symlinks, then lists a bunch of 3.9 files as conflicts. I think maybe it's actually two builds of 3.9 clashing somehow or something weird like that.

**Comment by akortunov** [comment]
> To force the link and overwrite all conflicting files:
>  brew link --overwrite python@3.9

Probably it would be enough.

**Comment by akortunov** [comment]
Since [MR545](https://gitlab.com/OpenMW/openmw/-/merge_requests/545) was merged, can this PR be closed?

**Pull request closed without merging**
