### PR TITLE
Make dialogue choices trigger goodbye if Goodbye option is present (bug #3897)

### PR DESCRIPTION
**Pull request by Capostrophic**
[Bug report 3897.](https://bugs.openmw.org/issues/3897)

The window closes and nothing happens in this case.

I added Goodbye to the script text of "did you bring the mushrooms" topic info of Ajira. On master Ajira answers the choice and Goodbye option is still present to be chosen, with PR the dialogue window closes immediately upon any choice.

### CODE REVIEW

**Comment by MiroslavR** [comment]
Are you sure the scripts associated with those choices are not supposed to be executed?

**Comment by Capostrophic** [comment]
Apparently the report is erroneous.

If a Goodbye command follows Choice in the dialogue response, it should practically be ignored - no option gets added and the choices don't result in a goodbye event, and if Choice follows Goodbye, then no choices should get added into the list.

**Comment by Capostrophic** [comment]
Apparently vanilla Goodbye-Choice relationship is completely different from the one described in the report and it's erroneous. I'll try again tomorrow.

**Comment by zinnschlag** [comment]
Can we close this PR then?

**Comment by Capostrophic** [comment]
Well, go ahead, though I wanted to repurpose it. The feature request should be rejected, though, because that's definitely not what's happening in the vanilla. Goodbye option and choices are mutually exclusive there: the one earlier in the dialogue response will appear and the latter won't. If Goodbye is present in script text later than choices, choices won't suddenly change their function; it's practically ignored, and if choices are present later, they won't get added and the player is forced to choose goodbye.

**Comment by zinnschlag** [comment]
Is there a reason why you re-opened this PR?

**Comment by Capostrophic** [comment]
OpenMW-CS-created plugin was giving incorrect results in the original engine, thus making the behavior invalid - Morrowind didn't handle the return symbols used in the edited script text properly. See 4443 discussion. rot tor's plugins work properly; also, it seems that the choice scripting is not handled either.

**Pull request merged**
