### PR TITLE
[Testing needed] Fix regressions in the animation system

### PR DESCRIPTION
**Pull request by akortunov**
Fixes [bug #4729](https://gitlab.com/OpenMW/openmw/issues/4729).

Needs caruful testing since it can break something else.

### CODE REVIEW

**Comment by zinnschlag** [comment]
@psi29a Sorry, not familiar enough with this part of OpenMW to contribute more than a basic sanity check on the code (nothing obvious wrong). This needs careful and preferably extensive testing, indeed. I suggest we wait a little longer and if no one else has anything to contribute we merge. That is still the best method to get more testing.

**Comment by AnyOldName3** [comment]
IIRC @Capostrophic was the one who made the changes which caused the regression, so he's probably pretty familiar with this code. I've not meddled with anything here either, so, like Zini, the best I could do would be a sanity check.

**Comment by akortunov** [comment]
> Oops, just noticed that this is meant of 0.45. That makes the lets merge it and see what breaks options less good.

Do not hurry with that. There is nothing gamebreaking in these issues.

**Comment by Capostrophic** [comment]
In short, LGTM (for real this time).

**Comment by psi29a** [comment]
This still needs to be cherry picked into openmw-45

**Pull request merged**
