### PR TITLE
Allow partial matches in NotCell condition (bug #4459)

### PR DESCRIPTION
**Pull request by Capostrophic**
[Bug report.](https://gitlab.com/OpenMW/openmw/issues/4459)

Extended the condition to return false on partially matching strings. Seems to work just fine with the plugin supplied by rot tor ([only available on redmine](https://bugs.openmw.org/issues/4459)) -- on master the greeting does appear in interiors of Balmora, with the change it does not. It should resolve the reporter's issue too.

### CODE REVIEW

**Comment by akortunov** [comment]
Are you sure that it just uses string comparison?
For example, we have two exterior cells: "Cell" and "Cell2". In your case "NotCell Cell" is true for both cells. Is this behaviour valid?
Another example: you have two interiors - "Cell, Interior" and "Cell, Interior2". "NotCell 'Cell, Interior'" is true for both cells.

Maybe it checks cell blocks, separated by comma?

**Comment by Capostrophic** [comment]
I do almost exactly the same thing as [GetPCCell](https://github.com/OpenMW/openmw/blob/openmw-44/apps/openmw/mwscript/cellextensions.cpp#L109).
However, OpenMW doesn't check if the cell argument is valid, so it appears that our understanding of this function is incomplete.

**Comment by zinnschlag** [comment]
So that means more research is needed before we can continue here?

**Comment by Capostrophic** [comment]
Just tested. Morrowind works almost exactly the same, but it also checks if the tested cell does exist.
I created a cell named toddtes and went to toddtest. GetPCCell returns 1 for toddtes argument in this case.
Since NotCell condition is supposed to be consistent with GetPCCell behavior, string comparison should work fine. A check if the tested cell actually exists can be implemented later, if that's necessary.

**Pull request merged**
