### PR TITLE
Fish stop AiCombat when can't reach target (Fixes #2678)

### PR DESCRIPTION
**Pull request by dteviot**
A possible fix for #2678.

### CODE REVIEW

**Comment by scrawl** [comment]
You could remove the TODO: start fleeing comment, which isn't relevant if AiCombat ends.

Have you tested whether this is also correct behaviour in the opposite case of isEnvironmentCompatible - i.e. a creature on land that can't swim?

**Comment by dteviot** [comment]
> Have you tested whether this is also correct behaviour in the opposite case of isEnvironmentCompatible - i.e. a creature on land that can't swim?

The short answer is: no, land creatures do not stop fighting you when you enter the water.
That said, the Vanilla behaviour is odd. 

According to the creature flags, only fish and dreugh are supposed to be able to swim.
If you pick a fight with a land creature (I tried scrib, kwama forager, & alit) the creature will not follow you into the water once you're more than around waist deep.  However, if you're levitating just above the water surface, it will happily follow you in.  Even to the point of it being fully submerged.

Note, the fully submerged creatures do not drown.

Other weird behaviour.  Once you fully submerge, the scrib and kwama freeze in their current position.  The Alit wander off.  But the combat music continues to play.

I also note that once a fish start fighting, leaving the water doesn't stop combat with them.
Also, fish will attack you, even if you're invisible.

To be honest, I wasn't really sure about this as a fix.  I should have been more clear that I was suggesting it as a possible fix, and really wanted to discuss  if it was worth perusing or not.  My personal opinion is it probably isn't the correct solution.  And possibly bug #2678 should be closed as not a bug.

**Comment by jeffreyhaines** [comment]
@dteviot do you intend to resolve this issue? If not could you close your pull-request please. Thank you

**Comment by dteviot** [comment]
closing as requested by @jeffreyhaines.

**Pull request closed without merging**
