### PR TITLE
NifSkope 1.1.3 for Linux

### PR DESCRIPTION
**Pull request by tmbutterworth**
Added information on NifSkope 1.1.3 availability in .rpm format and download like.

### CODE REVIEW

**Comment by tmbutterworth** [comment]
Added some information on using NifSkope 1.1.3 on Linux along with download information. I have a alien converted .deb package if you want to include it somewhere.

**Comment by psi29a** [comment]
This information is not correct. I spent some time there getting 2.x stable and compilable on Linux.

**Comment by tmbutterworth** [comment]
Really I fought with 2.x on Linux for quite a while and ended up porting some of it. The old info was also incorrect though as well as it did not include that 1.1.3 is available as an official download in .rpm format.

**Comment by psi29a** [comment]
Here was my PR:
https://github.com/niftools/nifskope/pull/101

it has been merged in for awhile now. Works fine on Linux, compiled from scratch.

**Pull request closed without merging**
