### PR TITLE
move rig and morph update in update thread

### PR DESCRIPTION
**Pull request by mp3butcher**
cleaner for stats

### CODE REVIEW

**Comment by akortunov** [comment]
I do not understand what do you try to achieve. From what I can tell, OpenMW performs both Update and Cull in the main thread (you can see it in the profiler), so moving rigs processing from Cull to Update does not improve situation at all. Also a separate mutex for EVERY rig in scene seems to be an overkill for me (mutex is a quite slow thing).

As about FPS: this PR drops FPS from 95 to 55 for me in testing scene with 10 NPC's. This drop is caused by DYNAMIC data variance in the MorphGeometry (the draw thread basically becomes idle when the main thread is busy).

So in its current state this PR is basically unusable.

**Comment by mp3butcher** [comment]
sorry was i bit tired doing this pr...i fixed errors
the goal of this pr is to do update in update, it is cleaner for stats

**Comment by AnyOldName3** [comment]
We intentionally do this in the cull thread because it means that a fairly time-hungry operation only happens for things that pass culling. This is a very common thing to do in game engines - Unreal doesn't do any skinning without the approval of an occlusion query against the previous frame, for example. We're not going to sacrifice performance just to make the profiler look tidier.

It also means that if we ever implement hardware skinning, it's a simpler task as things aren't shunted around as much.

**Comment by mp3butcher** [comment]
as you like

**Pull request closed without merging**
