### PR TITLE
put particle systems in  transparent bin to fix annoying bug

### PR DESCRIPTION
**Pull request by mp3butcher**
fix transparency of particle systems
these kinds
Capture d’écran de 2019-07-14 23-41-43
Capture d’écran de 2019-07-14 23-42-18

result:
https://streamable.com/c1pf71

### CODE REVIEW

**Comment by psi29a** [comment]
Does this do anything to to fix the flickering at a distance (including ghost wall) or is that unrelated?

**Comment by Capostrophic** [comment]
No, it's unrelated.

**Comment by mp3butcher** [comment]
> Does this do anything to to fix the flickering at a distance (including ghost wall) or is that unrelated?

no just alpha composition fix
but there still bugs, i pushed too fast

**Comment by mp3butcher** [comment]
a simple one this time

**Comment by psi29a** [comment]
I like it, clean simple and to the point. 
@AnyOldName3 @Capostrophic would this be recommended for 0.46 or leave it for 0.47?

**Comment by mp3butcher** [comment]
0.47

**Comment by AnyOldName3** [comment]
I remember this being brought up before and I did an APITrace to determine what the vanilla engine did. Can someone find where I posted my results? I think it was in another MP3Butcher PR.

**Comment by psi29a** [comment]
> I remember this being brought up before and I did an APITrace to determine what the vanilla engine did. Can someone find where I posted my results? I think it was in another MP3Butcher PR.

I remember this too?

**Comment by psi29a** [comment]
https://github.com/OpenMW/openmw/pull/2781#issuecomment-614357721

**Comment by AnyOldName3** [comment]
No, I'm meaning months/a year ago and specifically when particle systems were rendered relative to other things in the same frame.

**Comment by mp3butcher** [comment]
> [#2781 (comment)](https://github.com/OpenMW/openmw/pull/2781#issuecomment-614357721)
> 
> That PR was merged in for 0.46

what? @capo specifically what i put Change.log changes as 0.47 
https://github.com/OpenMW/openmw/pull/2781#discussion_r411400275

**Comment by psi29a** [comment]
My apologies, 0.47 correct.

**Comment by mp3butcher** [comment]
> I remember this being brought up before and I did an APITrace to determine what the vanilla engine did. Can someone find where I posted my results? I think it was in another MP3Butcher PR.

I would be astonished...TRANSPARENT_BIN can't be traced easily

**Comment by AnyOldName3** [comment]
I found a lamp or something where there were a lot of particles and translucent things near each other and looked at the draw order.

**Comment by mp3butcher** [comment]
@AnyOldName3 merging with https://github.com/mp3butcher/openmw/tree/precisetransparentdepth fixes it.......

**Comment by mp3butcher** [comment]
> @AnyOldName3 merging with https://github.com/mp3butcher/openmw/tree/precisetransparentdepth fixes it.......

I talked to fast...will investigate

**Comment by mp3butcher** [comment]
fixed

**Comment by mp3butcher** [comment]
for me hacking/disabling depth write for transparent is the only answer, it'd also fix an issue with occlusion culling if i remember

**Comment by mp3butcher** [comment]
arf no in fact

**Comment by AnyOldName3** [comment]
> I found a lamp or something where there were a lot of particles and translucent things near each other and looked at the draw order.

I might just have been thinking of this comment: https://github.com/OpenMW/openmw/pull/2423#issuecomment-511041020

I might not have done, though. I remember looking at a vanilla-engine trace of a candle flame in a lantern to determine the draw order.

**Pull request closed without merging**
