### PR TITLE
Improved doors detection

### PR DESCRIPTION
**Pull request by akortunov**
This PR provide a way to detect doors using rendering ray casting (as with spell projectiles) istead of iterating over all doors in an actor cell.

Allows to fix issues such as "Combat AI sometimes cannot open the door".
See my posts in [this](https://bugs.openmw.org/issues/3227) thread.

Note: maybe should we also do a rendering raycasting as fallback?

### CODE REVIEW

**Comment by psi29a** [comment]
What is the performance cost of this solution?

**Comment by akortunov** [comment]
> What is the performance cost of this solution?

What kind of speed test should I do?

**Comment by akortunov** [comment]
Do not merge it, usage of rendering ray can lead to problems with non-solid doors.
Now I am testing usage of physics castRay instead (based by bounding boxes). No problems so far.

**Comment by akortunov** [comment]
Using physics ray now. But I am not sure

**Comment by akortunov** [comment]
Using activation distance instead of hardcoded value now.
Also door AI is enabled in exteriors.
Tested on the gates outside the Census and Excise Office in Seyda Neen.

**Comment by akortunov** [comment]
Rebased 4 commits into 1.

**Comment by scrawl** [comment]
I think a raycast is overkill, and they are rather expensive. We know that actors are always facing horizontally, so it should be relatively simple to determine if they're facing a door without using a raycast. Maybe the blocking angle code in combat.cpp helps for reference.

**Comment by akortunov** [comment]
> Maybe the blocking angle code in combat.cpp helps for reference.

I do not see any help from blocking in this case:

With blocking we already know both attacker's and target's ID's and position, so can calculate angle and distantion between attacker and target easily.

With door detection we know only actor ID and position. Now we have to iterate over all doors in the cell to determine a distance between the door and actor. This algorithm is linear, so we had to disable it in exteriors. Also we have a similar check in Actors::getObjectsInRange().

How can I detect an object which NPC is facing without raycasting and iterating over all objects in the cell?

Or a current OpenMW implementation is a fast enough to enable it in exteriors, and add the angle check here?

**Comment by scrawl** [comment]
Iterating all doors in the cell should be much cheaper than a raycast. I have no idea why the code was disabled for exteriors.

**Comment by akortunov** [comment]
> Iterating all doors in the cell should be much cheaper than a raycast. 

Ok, I will try to improve a current OpenMW implementation.

**Comment by akortunov** [comment]
I uploaded a my first attempt to improve the current doors detection algorithm.

Notes:
1. I took an angle formula from Actors::updateHeadTracking().
2. I do not know how to handle Z offset properly. In current master AI sometimes fails to open a door because of difference between door Z position and actor Z position.
3. The doors detection algorithm is enabled in exteriors now.
4. On a short distances the angle between an actor position and a door position can be up to PI/2, even if the actor is facing the door directly.

Tested with these doors:
1. Gates outside the Census and Excise Office in Seyda Neen.
2. A wooden door in "Ald-ruhn, Arobar Guard Quarters".
3. A wooden door near entrance in Addamasartus.

In master implementation AI fails to open first two of these doors, with this PR AI can open all these doors.

**Comment by scrawl** [comment]
> On a short distances the angle between an actor position and a door position can be up to PI/2, even if the actor is facing the door directly.

Right, because the door position is only a point. To be more accurate maybe we could use the door's bounding box, or construct a plane through the door position based on its orientation?

**Pull request merged**
