### PR TITLE
Modifying an object instance (e.g. 3D edit) triggers the instances

### PR DESCRIPTION
**Pull request by cc9cii**
table to scroll to the corresponding record.  Should resolve Feature #2554.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Limiting this feature to instances is problematic. It will still catch other cases besides modifications in the 3D-view (like modifications in another view of the same table), which would cause an inconsistency between the instance table and all other tables.

**Comment by cc9cii** [comment]
That's fair enough.  Any idea on how we can provide the functionality without causing inconsistencies?

**Comment by cc9cii** [comment]
How about per-subview (e.g. checkbox) setting to auto update after a modify?  That way only the user has knowledge and control over how the view updates.  Also, it means that this can be applied to all tables.

**Comment by zinnschlag** [comment]
Difficult. With the bottom bar (status and creation) and the top bar (record filter and soon column filter) I don't see how we can add another checkbox in there without cluttering up things and taking away even more valuable screenspace.
Hm, a context menu item maybe?

**Comment by zinnschlag** [comment]
Or maybe add a small button (re-using the user settings icon ?) to the top panel that temporarily pops up a configuration panel over the filter panel in the same way as the add/clone panel pops up over the status bar. This configuration panel would then contain both the column filter selected widget, the checkbox you proposed and everything else that we may come up with later.

**Comment by cc9cii** [comment]
Ok, I'll think about this.

**Comment by cc9cii** [comment]
Done, please review.

**Comment by cc9cii** [comment]
temporarily closing while investigating something odd

**Comment by cc9cii** [comment]
Figured it out, reopening.

**Comment by cc9cii** [comment]
Done, ready for merge (after a review, that is)

**Comment by cc9cii** [comment]
Any feedback on this PR please?

**Comment by zinnschlag** [comment]
Looks mostly okay (except for the point I commented on inline).

There is one issue with the GUI:

Clicking on the config icon should replace the bar, not just add the checkbox. Otherwise we would have no room for the column filter UI.

**Comment by cc9cii** [comment]
Closing.  Kinda useless since osg will be merged soon.

**Pull request closed without merging**
