### PR TITLE
Bug #2281 NPCs don't scream when they die

### PR DESCRIPTION
**Pull request by jeffreyhaines**
Added dying grunt for actor deaths

### CODE REVIEW

**Comment by scrawl** [comment]
I don't think this is the right way to do it. As I wrote in the issue description:

> There is a "scream" soundgen tag in the animation

Which, when encountered, presumably should trigger the "hit" voice dialogue entry.

**Comment by jeffreyhaines** [comment]
So say we get the soundgen tag "scream" and we return with "hit" string.
When we go to the play the sound, it is safe to ask, if ("hit") say hit?

Should I use another string to return? Safer than "hit"?

**Comment by scrawl** [comment]
I presume you're talking about the Npc::getSoundIdFromSndGen function.

"hit" is not a sound ID, it's a dialogue topic ID.

**Comment by jeffreyhaines** [comment]
Right so how do we get from Npc::getSoundIdFromSndGen function with "scream" to play the hit sound?

**Comment by jeffreyhaines** [comment]
Don't we want to process the tag, and return "THIS_IS_THE_I_WAS_KILLED_TAG"
so that when we run the soundgen code we call the dialogmgr.say(ptr, "hit")...

**Comment by scrawl** [comment]
> Don't we want to process the tag, and return "THIS_IS_THE_I_WAS_KILLED_TAG"
so that when we run the soundgen code we call the dialogmgr.say(ptr, "hit")...

That's what I would call an awful hack. Better do some refactoring. For example, we could have the function handle playing the sound, instead of returning the ID to play.

<pre>
void Class::handleSndGen(const MWWorld::Ptr&, const std::string&)
</pre>

**Comment by jeffreyhaines** [comment]
Ok. Let me see what I can do.

**Pull request closed without merging**
