### PR TITLE
Add separate textures for scrollbars

### PR DESCRIPTION
**Pull request by akortunov**
Implements a [feature #5051](https://gitlab.com/OpenMW/openmw/issues/5051).

New files have a lowest priority in VFS, so modders can override them as any other texture.
Also scrollbars become scalable, so you in theory can use textures with different resolution.

### CODE REVIEW

**Comment by Capostrophic** [comment]
Looks fine to me. Since our scrollbar is not really compatible with Morrowind assets due to how its length is not fixed, this doesn't violate how it was said explicitly in the past we shouldn't supply Morrowind replacement assets, so I think this can get a pass. Any objections?

**Comment by psi29a** [comment]
I hate binaries in our repo...

first, are these assets properly licensed? What are their origins?

**Comment by akortunov** [comment]
> What are their origins?

GIMP. Arrows are based on arrow textures from minimap window, but it is not a copy-paste.

**Comment by psi29a** [comment]
So you created them? Can you provide, either here or in a text file somewhere that indicates under what license you would like these to fall under? I wish we had done this with other assets, for now we assume they _all_ fall under the GPLv3 which is absurd. 

I think have your comment here is enough that we can point back to it later saying: see, he licensed this under XXX.

**Comment by akortunov** [comment]
> I think have your comment here is enough that we can point back to it later saying: see, he licensed this under XXX.

Just as the engine itself (GPLv3, I suppose) - these textures were created specially for OpenMW.

**Comment by Capostrophic** [comment]
GPL isn't really suitable for non-software works, there's a reason why psi29a suggested to use a Creative Commons license for the new assets.

**Comment by akortunov** [comment]
> GPL isn't really suitable for non-software works, there's a reason why psi29a suggested to use a Creative Commons license for the new assets.

Use any license whatever you like.

**Comment by Capostrophic** [comment]
Then these textures are released into public domain, alright. :smile:

**Comment by psi29a** [comment]
That doesn't work, France for example (and many others) do not recognize public domain. If you want it to be that 'free' then please use 
https://creativecommons.org/publicdomain/zero/1.0/

Is that OK? I need you publicly state it instead of saying "whatever you like". I know it is obnoxious, but I want to make sure that OpenMW has the best chances.

**Comment by wareya** [comment]
If you want to license something under the public domain, yeah, just say that you license it under the CC0 license.

**Comment by akortunov** [comment]
> If you want to license something as if it were public domain, yeah, just say that you license it under the CC0 license.

All right, let it be the CC0 then.

**Pull request merged**
