### PR TITLE
[DO NOT MERGE] Std experimental filesystem

### PR DESCRIPTION
**Pull request by psi29a**
experiment in progress ;)

### CODE REVIEW

**Comment by psi29a** [comment]
It turns out that OSX does not yet support C++17, that also means no support for experimental/filesystem . We'll have to wait and sit on this branch until support is there.

https://github.com/potree/PotreeConverter/issues/260#issuecomment-321531668

Same thing for MSVC.

**Comment by m-schuetz** [comment]
> Same thing for MSVC.

What are you referring to with "same thing"? Visual Studio 2017 supports experimental/filesystem:

```C++
#include <experimental/filesystem>

namespace fs = std::experimental::filesystem;
```

**Comment by psi29a** [comment]
Same thing, as in.. it needs work. The reason it doesn't build is not the same. Now if you know where and how it fails and would like to help, please do. I do not have a windows machine.

**Comment by psi29a** [comment]
```
C:\Libraries\boost_1_60_0\boost/algorithm/string/detail/case_conv.hpp(33): error C2143: syntax error: missing ',' before '<' (compiling source file C:\projects\openmw\MSVC2015_32\components\ub_settings.cpp) [C:\projects\openmw\MSVC2015_32\components\components.vcxproj]
         C:\Libraries\boost_1_60_0\boost/algorithm/string/detail/case_conv.hpp(49): note: see reference to class template instantiation 'boost::algorithm::detail::to_lowerF<CharT>' being compiled (compiling source file C:\projects\openmw\MSVC2015_32\components\ub_settings.cpp)
    18>C:\Libraries\boost_1_60_0\boost/algorithm/string/detail/case_conv.hpp(53): error C2143: syntax error: missing ',' before '<' (compiling source file C:\projects\openmw\MSVC2015_32\components\ub_settings.cpp) [C:\projects\openmw\MSVC2015_32\components\components.vcxproj]
         C:\Libraries\boost_1_60_0\boost/algorithm/string/detail/case_conv.hpp(69): note: see reference to class template instantiation 'boost::algorithm::detail::to_upperF<CharT>' being compiled (compiling source file C:\projects\openmw\MSVC2015_32\components\ub_settings.cpp)
       The target "CopyLocalFilesOutputGroup" listed in a BeforeTargets attribute at "C:\Tools\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets (80,82)" does not exist in the project, and will be ignored.
     1>Project "C:\projects\openmw\MSVC2015_32\OpenMW.sln" (1) is building "C:\projects\openmw\MSVC2015_32\extern\osg-ffmpeg-videoplayer\osg-ffmpeg-videoplayer.vcxproj.metaproj" (13) on node 1 (default targets).
    13>Project "C:\projects\openmw\MSVC2015_32\extern\osg-ffmpeg-videoplayer\osg-ffmpeg-videoplayer.vcxproj.metaproj" (13) is building "C:\projects\openmw\MSVC2015_32\extern\osg-ffmpeg-videoplayer\osg-ffmpeg-videoplayer.vcxproj" (20) on node 1 (default targets).
```

**Comment by zinnschlag** [comment]
Ties to the C++17 PR. Therefore closing ...

**Comment by psi29a** [comment]
Indeed... cleaning the cruft.

**Pull request closed without merging**
