### PR TITLE
Do not use the QStringList::fromSet, which is deprecated since Qt 5.14

### PR DESCRIPTION
**Pull request by akortunov**
Just that.

### CODE REVIEW

**Comment by AnyOldName3** [comment]
Is there any reason for the version check? Surely the non-deprecated path would work fine with older versions.

**Comment by akortunov** [comment]
> Is there any reason for the version check?

A quote from Qt docs:

> Since Qt 5.14, range constructors are available for Qt's generic container classes and should be used in place of this method.

I have no idea if these constructors are available for old Qt versions, especially for Qt 4.x.

**Comment by AnyOldName3** [comment]
Looks like they weren't available before, so the version check makes sense if there's no alternative option that's been around for longer.

**Comment by Capostrophic** [comment]
Doesn't seem like there is.

**Pull request merged**
