### PR TITLE
Maybe resolve regression with MSVC2017

### PR DESCRIPTION
**Pull request by AnyOldName3**
Hopefully this fixes the problem caused by the async physics merge. I've not tested it, though. It's a GitHub PR rather than GitLab MR because GitLab CI doesn't do MSVC 2017, only AppVeyor.

### CODE REVIEW

**Comment by psi29a** [comment]
This is pretty ugly, any way we can set something once, project wide?

**Comment by fr3dz10** [comment]
Maybe put it in appveyor config only? Nightlies and release are built from gitlab runners I think so they're not concerned

**Comment by psi29a** [comment]
GL apparently only has MSVC2019, so this was never a problem for them.

Our policy, so far, has been to support the last 2 major releases of MSVC so putting it in AppVeyor isn't an option.

**Comment by AnyOldName3** [comment]
It's not only AppVeyor that uses MSVC2017. Because I don't want to spend a day rebuilding my self-built dependencies in all the build configurations, my everything-is-debuggable local build is still on 2017, for example, so it definitely needs to be in our build system rather than just a subset of the scripts that launch it.

There *are* ways to specify this for everything at once, but they're more error-prone, as they replace what's there rather than append, need setting up before any targets are created (as they only initialise the defaults, and don't set things on existing targets), and are generally pre-CMake 3.0 and messy.

If I knew which part of OpenMW actually needed the definition, I could keep it more contained, for example if it was in `components`, setting it as a target definition as `INTERFACE` is actually already setting it for `components` and everything that depends on `components`, which would solve all the immediate problems, but might need expanding on if/when the feature is used somewhere else. Alternatively, we could just specify the define in the source code where it's needed.

**Comment by fr3dz10** [comment]
Fair enough. When I googled that error this afternoon I found a report linked to smart pointer construction. If I had to guess I would say that it is physicssystem.cpp

**Comment by AnyOldName3** [comment]
The log says `compiling source file C:\projects\openmw\apps\openmw\mwphysics\physicssystem.cpp` in the error message, so if we're okay with not affecting the whole project, we can add it to `openmw` neatly or `components` equaly neatly and have more, but not total, coverage.

**Comment by psi29a** [comment]
Yeah, I'm okay with turning that switch on openmw and leaving it at that. MSVC2017 will yell at us if we have to do it elsewhere. We can then remove it when we drop MSVC2017.

**Comment by AnyOldName3** [comment]
`openmw` rather than `components` and (implicitly) everything that depends on it?

**Comment by psi29a** [comment]
As far as I'm aware, the only problem was related to anything that touched
`C:\projects\openmw\apps\openmw\mwphysics\physicssystem.cpp`

**Comment by AnyOldName3** [comment]
I originally applied it to everything because we might come to rely on it somewhere else in the future. The definition makes something in MSVC2017 that wasn't historically standards-compliant become standards-compliant, so it's not a bad thing to have enabled.

**Comment by psi29a** [comment]
But doesn't this setting get ignored in MSVC2019 anyway?

**Comment by AnyOldName3** [comment]
Yes, MSVC2019 never had the bug, so doesn't need to maintain backwards compatibility by optionally still having the bug.

When you say you're fine with how it is now, do you mean you're ready to press the merge button despite the existing mess?

**Comment by psi29a** [comment]
I'm fine with your choice, if you think it is better to be explicit over implicit. I'll defer to you. We can revert this when the next MSVC comes out. ;)

**Comment by AnyOldName3** [comment]
I can't force-push in the web editor, so to keep the history clean, I've superseded this with #3016

**Pull request closed without merging**
