### PR TITLE
Fix #4452

### PR DESCRIPTION
**Pull request by wareya**
I had to work around a couple different problems (underwater terrain was broken because of screen fog, statics nearly parallel to the terrain had halos - both worked around) so this probably needs to be tested on computers other than my own. Also, terrain rendering is broken when shaders fail to compile with or without this patch (without the patch it looks like https://i.imgur.com/iPMGzA2.jpg, with the patch it's pure black), so I didn't bother to update the "shaders fail to compile" terrain material codepath.

See http://bugs.openmw.org/issues/4452 and https://imgur.com/a/nzGazLY

### CODE REVIEW

**Comment by psi29a** [comment]
@lysol90 you're up I think. :)

**Comment by unelsson** [comment]
I tested this without mods, spent some time flying around Morrowind and Solstheim, and also visited Mournhold although likely not affected by this. Looks good to me, but I also can't tell if mods are affected.

**Comment by Capostrophic** [comment]
They work just fine.

fyi psi29a diffuse map is just the color map, if you see that terrain is not black then it's there

**Comment by zinnschlag** [comment]
This looks ready for a merge.

**Comment by psi29a** [comment]
Fixed merge conflict, waiting on CI to catch up for a final rebuild.

Any last comments?

@wareya you ready to take off the WIP in the title?

**Comment by zinnschlag** [comment]
@wareya It seems you are not registered on GitLab yet. Could you please fix that so we can assign the issue to you on our new tracker?

**Comment by psi29a** [comment]
LGTM, merging. Thanks!

**Pull request merged**
