### PR TITLE
OpenMW-CS: Camera resets every time cell->view is pressed

### PR DESCRIPTION
**Pull request by lohikaarme**
Camera didn't reset when right clicking cell and pressing view if world renderer was open.

PS: Shouldn't "const int cellSize = 8192" be some where it can be accessed easily rather than be local variable.

### CODE REVIEW

**Comment by zinnschlag** [comment]
It seems that this won't build and won't merge cleanly either.

Apparent from that could you elaborate which problem you are trying to fix? Its not clear to me from the issue description.

Regarding cellSize: Unfortunately we have these constants all over the place. The proper way would be to have a single constant in ESM::Cell. If you want to go through the code and collect all the constants in one place, feel free to send another pull request (after this one has been sorted out).

**Comment by lohikaarme** [comment]
I don't think there is open issue for it. Here is video showing what I am talking about:
https://www.youtube.com/watch?v=xWouSOxKROY

When _mCamPositionSet_ isn't set to false the view will not move the camera to newly open cell if there is already other cell open. After _mCamPositionSet_ is set to false then rendering update will move the camera near that cell. 

Is there any build log from AppVeyor?

**Comment by MiroslavR** [comment]
> Is there any build log from AppVeyor?

`Failure: AppVeyor was unable to build non-mergeable pull request`

You need to resolve the conflicts.

**Comment by Aesylwinn** [comment]
> Regarding cellSize: Unfortunately we have these constants all over the place. The proper way would be to have a single constant in ESM::Cell. If you want to go through the code and collect all the constants in one place, feel free to send another pull request (after this one has been sorted out).

The constant is already defined in [components/esm/loadland.hpp](https://github.com/OpenMW/openmw/blob/master/components/esm/loadland.hpp#L56)

**Comment by zinnschlag** [comment]
> The constant is already defined in components/esm/loadland.hpp

Not really the correct place for it.

**Comment by zinnschlag** [comment]
> I don't think there is open issue for it. Here is video showing what I am talking about:
https://www.youtube.com/watch?v=xWouSOxKROY

I see. You have the editor configured to re-use existing 3D scene subviews. That explains it.

**Comment by lohikaarme** [comment]
It would make more sense be attribute of cell rather than it's loader.

**Comment by lohikaarme** [comment]
> I see. You have the editor configured to re-use existing 3D scene subviews. That explains it.

Configured by how? Macro or option settings inside of the editor?

**Comment by zinnschlag** [comment]
There is a user setting for that. I think under the Windows tab.

**Comment by scrawl** [comment]
No offense but that is the messiest commit log I have ever seen. Please do a rebase next time.

**Comment by lohikaarme** [comment]
Yeah sorry about that :(

**Pull request merged**
