### PR TITLE
Store integer actor ID in AiFollow and AiEscort (bug #4036)

### PR DESCRIPTION
**Pull request by akortunov**
Fixes [bug #4036](https://bugs.openmw.org/issues/4036).

### CODE REVIEW

**Comment by akortunov** [comment]
> What sort of feedback are you looking for?

Mainly about savegame format changes. I got this feedback in #1592: I can read data from savegame, write it only in future releases.
I suppose this PR is ready for review now.

**Comment by scrawl** [comment]
Isn't the  ```MWWorld::Ptr AiEscort::getTarget() const``` content copied from another function? If so can you put that somewhere shared, e.g. AiPackage, to avoid the code duplication?

**Comment by akortunov** [comment]
> If so can you put that somewhere shared, e.g. AiPackage, to avoid the code duplication?

But in this case getTarget() will be a default behaviour for all AI packages, right?

**Comment by zinnschlag** [comment]
Had another look at this. IMO it is almost ready to merge. The save code needs to be un-out-commented (is that actually a word?) and the saved game file version number needs to be increased by 1.

I am not comfortable with the new public variables in the AiPackage class. I have seen that the class already has public variables and that is something we will need to clean up at some point. But we shouldn't make the situation worse.

As a starting point, how about a new AiPackage constructor that takes the actor as an argument and fills in both mTargetActorRefId and mTargetActorId?

**Comment by akortunov** [comment]
> As a starting point, how about a new AiPackage constructor that takes the actor as an argument and fills in both mTargetActorRefId and mTargetActorId?

There are situations, when we do not know actor, but know only actor ID (integer) or actor ref Id (string), e.g. when read data from ESM.
So we need more constructors.

**Pull request merged**
