### PR TITLE
Handle plugins that has 0x00 for levelled list types,

### PR DESCRIPTION
**Pull request by cc9cii**
for example Ravenloft v5.02d, to use 0x01.

Unfortunately the fix spams the console with error messages.

### CODE REVIEW

**Comment by scrawl** [comment]
Those are flags and not a type enum. All bitmask combinations (including 0x00) are perfectly valid. The original code is wrong.
Also, could you make it use the enum please instead of 0x01/0x02 literals.

**Comment by cc9cii** [comment]
Ok.  Where can I find information about what the bitmask flags are and what they mean?

**Comment by cc9cii** [comment]
Vanilla CS uses checkboxes.  We don't have a way of doing that for bitmasks in the dialogue subview at the moment (for nested columns).  Also, vanilla has "blocked" which we don't seem to have.

**Comment by zinnschlag** [comment]
For bitmasks each bit should form a column of its own (boolean value). And we don't use blocked. We can ignore it completely.

**Comment by cc9cii** [comment]
All done, except I seem to have found an issue with undo/redo.  Investigating...

**Comment by cc9cii** [comment]
Undo labels fixed as well.

**Pull request merged**
