### PR TITLE
Fix windows CI scripts

### PR DESCRIPTION
**Pull request by elsid**
1. Cache proper files.
2. Remove annoying white spaces and trailing spaces
3. Fix compare with empty value.

### CODE REVIEW

**Comment by Capostrophic** [comment]
>Cache proper files.

Oh, cool. This will cut the building times, right?

**Comment by elsid** [comment]
> This will cut the building times, right?

Yes, but not much.

**Comment by elsid** [comment]
One of linux builds was timeouted (has no relation to these changes). Need retry I think, but I don't have access to do it.

**Comment by psi29a** [comment]
Looks like build times for openmw-cs with clang has shot through the roof... very spammy output about possible memory leaks and more. Not related here, but should be looked at.

**Pull request merged**
