### PR TITLE
Apply weapon reload animations only for upper body

### PR DESCRIPTION
**Pull request by akortunov**
Allows to fix a lot of problems with crossbowmans.

Currently in both vanilla and OpenMW there is a twitching when actor starts or stops walking during crossbow reload animation. It looks very weird, so I decided to apply such animation only for upper body.
I managed to solve issues with missing 1th-person mode crossbow animations: I use the 1h animations as fallback.
As for me, it looks decent.

Can we fix this issue from engine side, or it is a strictly up to content developers?

An another approach would be to stop shooter until the end of reload, but I suppose players will not be happy about it.

### CODE REVIEW

**Comment by psi29a** [comment]
So long as reloading a weapon doesn't involve the whole body, this is a nice solution that fixes an issue from vanilla as well.

Realistically one will stay still while reloading a crossbow...  but TES was never really realistic and people tend to FPS it up.

**Comment by akortunov** [comment]
> Does anyone have issues with 1st-person crossbow animations during movement in upstream OpenMW?

I suppose I have issues because Morrowind does not have movement animations for crossbow for some reason, and out current approach (apply basic movement animation with BlendMask_LowerBody) does not work well for some reason for 1st-person animations.

**Comment by TaxAkla** [comment]
I use the Per-KF Animation Feature. Let's say that I get the Almalexia Casting (Three Files) from Animation Compilation and put them to overwrite the Beast ones. What I get now is Beasts castings Almalexia style spells with human legs animation only when standing still but with Beast legs while moving around.

Question: If merged will this pull give us Beasts with Almalexia Castings but with the correct legs for them?

I attached a example mod to easier tests.
[Beasts with Almalexia Casting Animations.zip](https://github.com/OpenMW/openmw/files/2127942/Beasts.with.Almalexia.Casting.Animations.zip)

**Comment by akortunov** [comment]
I managed to solve issues with missing 1th-person mode crossbow animations: I use the 1h animations as fallback.
It is not 100% vanilla behaviour (for example, vanilla does not handle sneaking pose with crossbows well), but it is much better than our current behaviour.

**Comment by akortunov** [comment]
> Question: If merged will this pull give us Beasts with Almalexia Castings but with the correct legs for them?

Nope, you are out of luck. You will need to edit cast animations anyway.

**Comment by akortunov** [comment]
Any suggestions or issues with this PR?

**Comment by psi29a** [comment]
@akortunov nothing more to discuss then I propose to merge, please remove discussion from title when you're ready. :)

**Comment by akortunov** [comment]
I'll add the issue on bugtracker and changelog entry then.

**Comment by akortunov** [comment]
> I'll add the issue on bugtracker and changelog entry then.

Done.

**Comment by Capostrophic** [comment]
Seems to be relevant to this PR: when spellcasting stance is used, the rotating animation in OpenMW is not correct. In Morrowind it's much closer to the idle position of the legs and much less twitchy. Maybe 1h animations should be used for spellcasting stance too as fallback. I'll try that out and report back.

**Comment by akortunov** [comment]
> I'll try that out and report back.

I already tried that several days ago and it did not work for me.
But probably you will achieve better results.

**Comment by Capostrophic** [comment]
It's somewhat better, but it's still twitchy and inaccurate. What does Morrowind even utilize for spellcasting animations..?

**Comment by Capostrophic** [comment]
Does anything break when you change the short group of crossbow weapon type to 1h instead (line 216)?

**Comment by akortunov** [comment]
> Does anything break when you change the short group of crossbow weapon type to 1h instead of using a workaround (line 216)?

I think it is a bad idea - it will replace ALL crossbow animations instead of just missing jumping and idle ones and only when they are missing.

**Comment by Capostrophic** [comment]
Already realized that and deleted the comment.

Maybe Morrowind uses some kind of different animation blending for spellcasting stance rotating animation specifically. I couldn't find any similar animation group. Maybe I'm missing something.

**Comment by akortunov** [comment]
I suggest to try to fix turning animations in #1666 instead.

**Comment by psi29a** [comment]
Going once... going twice... merged!

Thank you @akortunov

**Pull request merged**
